import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { backgroundColor: '#F4F7F8', flex: 1 },
  header: { alignItems: 'center', backgroundColor: '#115E59', flexDirection: 'row', minHeight: 108, paddingBottom: 16, paddingHorizontal: 18, paddingTop: 48 },
  backButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.14)', borderRadius: 12, height: 42, justifyContent: 'center', width: 42 },
  backIcon: { color: '#FFFFFF', fontSize: 34, fontWeight: '300', lineHeight: 36, marginTop: -2 },
  headerCopy: { flex: 1, marginLeft: 12 },
  eyebrow: { color: '#99F6E4', fontSize: 9, fontWeight: '900', letterSpacing: 1.1 },
  title: { color: '#FFFFFF', fontSize: 23, fontWeight: '900', marginTop: 2 },
  cancelEdit: { backgroundColor: '#FFFFFF', borderRadius: 10, paddingHorizontal: 13, paddingVertical: 9 },
  cancelEditText: { color: '#115E59', fontSize: 12, fontWeight: '800' },
  content: { flex: 1 },
  contentContainer: { padding: 14, paddingBottom: 38 },
  itemsSection: { marginVertical: 18 },
  stepHeading: { alignItems: 'center', flexDirection: 'row', marginBottom: 11, paddingHorizontal: 2 },
  stepBadge: { alignItems: 'center', backgroundColor: '#0F766E', borderRadius: 12, height: 24, justifyContent: 'center', width: 24 },
  stepBadgeText: { color: '#FFFFFF', fontSize: 12, fontWeight: '800' },
  stepCopy: { marginLeft: 10 },
  stepTitle: { color: '#0F172A', fontSize: 17, fontWeight: '800' },
  stepSubtitle: { color: '#64748B', fontSize: 12, marginTop: 1 },
  loadingState: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 14, borderWidth: 1, flexDirection: 'row', justifyContent: 'center', padding: 24 },
  loadingText: { color: '#64748B', fontSize: 13, marginLeft: 9 },
  emptyState: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 14, borderWidth: 1, padding: 22 },
  emptyTitle: { color: '#334155', fontSize: 15, fontWeight: '800' },
  emptyText: { color: '#64748B', fontSize: 12, lineHeight: 18, marginTop: 4, textAlign: 'center' },
  startHint: { alignItems: 'center', flexDirection: 'row', justifyContent: 'center', paddingVertical: 25 },
  startHintIcon: { color: '#0F766E', fontSize: 18, fontWeight: '800', marginRight: 7 },
  startHintText: { color: '#64748B', fontSize: 13, fontWeight: '600' },
});
