import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  flex: { flex: 1 },
  container: { backgroundColor: '#F4F7F8', flex: 1 },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    paddingBottom: 20,
    paddingHorizontal: 20,
    paddingTop: 48,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 16,
    height: 48,
    justifyContent: 'center',
    marginRight: 16,
    width: 48,
  },
  backText: { color: '#FFFFFF', fontSize: 38, lineHeight: 40 },
  headerCopy: { flex: 1 },
  eyebrow: { color: '#CCFBF1', fontSize: 11, fontWeight: '800', letterSpacing: 1.8 },
  title: { color: '#FFFFFF', fontSize: 26, fontWeight: '900', marginTop: 4 },
  content: { gap: 16, padding: 18, paddingBottom: 48 },
  intro: { color: '#475569', fontSize: 14, lineHeight: 21, paddingHorizontal: 4 },
  card: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 20,
    borderWidth: 1,
    padding: 18,
  },
  sectionTitle: { color: '#0F172A', fontSize: 18, fontWeight: '900', marginBottom: 14 },
  help: { color: '#64748B', fontSize: 13, lineHeight: 19, marginBottom: 14, marginTop: -6 },
  field: { marginBottom: 14 },
  label: { color: '#475569', fontSize: 13, fontWeight: '700', marginBottom: 7 },
  input: {
    backgroundColor: '#F8FAFC',
    borderColor: '#CBD5E1',
    borderRadius: 12,
    borderWidth: 1,
    color: '#0F172A',
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  multilineInput: { minHeight: 82, textAlignVertical: 'top' },
  twoColumns: { flexDirection: 'row', gap: 12 },
  column: { flex: 1 },
  toggleRow: {
    alignItems: 'center',
    borderBottomColor: '#EEF2F6',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 52,
  },
  toggleLabel: { color: '#334155', flex: 1, fontSize: 14, fontWeight: '700', paddingRight: 12 },
  saveButton: {
    alignItems: 'center',
    backgroundColor: '#0F766E',
    borderRadius: 15,
    justifyContent: 'center',
    minHeight: 56,
  },
  saveText: { color: '#FFFFFF', fontSize: 16, fontWeight: '900' },
  disabled: { opacity: 0.55 },
});
