import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { backgroundColor: '#F1F5F9', flex: 1 },
  header: { alignItems: 'center', backgroundColor: '#334155', flexDirection: 'row', minHeight: 108, paddingBottom: 16, paddingHorizontal: 18, paddingTop: 48 },
  backButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.14)', borderRadius: 12, height: 42, justifyContent: 'center', marginRight: 12, width: 42 },
  backIcon: { color: '#FFFFFF', fontSize: 34, fontWeight: '300', lineHeight: 36 },
  eyebrow: { color: '#CBD5E1', fontSize: 9, fontWeight: '900', letterSpacing: 1.1 },
  title: { color: '#FFFFFF', fontSize: 23, fontWeight: '900', marginTop: 2 },
  content: { flex: 1 },
  contentContainer: { padding: 14, paddingBottom: 48 },
  summaryCard: { backgroundColor: '#0F172A', borderRadius: 18, padding: 17 },
  summaryTop: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between' },
  summaryEyebrow: { color: '#94A3B8', fontSize: 9, fontWeight: '900', letterSpacing: 0.9 },
  summaryAmount: { color: '#FFFFFF', fontSize: 30, fontWeight: '900', marginTop: 4 },
  summaryLoader: { alignSelf: 'flex-start', marginTop: 10 },
  statusBadge: { backgroundColor: '#047857', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6 },
  statusBadgeClosed: { backgroundColor: '#475569' },
  statusText: { color: '#FFFFFF', fontSize: 9, fontWeight: '900', letterSpacing: 0.8 },
  summaryMetrics: { borderTopColor: 'rgba(255,255,255,0.14)', borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, paddingTop: 12 },
  warningCard: { backgroundColor: '#FFF7ED', borderColor: '#FDBA74', borderRadius: 14, borderWidth: 1, marginTop: 12, padding: 13 },
  warningTitle: { color: '#9A3412', fontSize: 13, fontWeight: '900' },
  warningText: { color: '#C2410C', fontSize: 11, lineHeight: 16, marginTop: 3 },
  checklistHeader: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between' },
  checklistHeadingCopy: { flex: 1, paddingRight: 8 },
  checklistEyebrow: { color: '#64748B', fontSize: 8, fontWeight: '900', letterSpacing: 0.9, marginBottom: 4 },
  checklistStatus: { alignItems: 'center', borderRadius: 9, flexDirection: 'row', gap: 4, paddingHorizontal: 8, paddingVertical: 6 },
  checklistStatusReady: { backgroundColor: '#DCFCE7' },
  checklistStatusBlocked: { backgroundColor: '#FEE2E2' },
  checklistStatusSymbol: { color: '#0F172A', fontSize: 10, fontWeight: '900' },
  checklistStatusText: { color: '#334155', fontSize: 7, fontWeight: '900', letterSpacing: 0.5 },
  activityRow: { backgroundColor: '#F8FAFC', borderRadius: 12, flexDirection: 'row', marginTop: 13, paddingVertical: 11 },
  activityMetric: { alignItems: 'center', flex: 1 },
  activityValue: { color: '#0F172A', fontSize: 15, fontWeight: '900' },
  activityLabel: { color: '#94A3B8', fontSize: 6, fontWeight: '900', marginTop: 2 },
  checkRow: { alignItems: 'center', borderBottomColor: '#F1F5F9', borderBottomWidth: 1, flexDirection: 'row', minHeight: 52 },
  checkDot: { alignItems: 'center', borderRadius: 9, height: 28, justifyContent: 'center', width: 28 },
  checkDotBlocker: { backgroundColor: '#FEE2E2' },
  checkDotWarning: { backgroundColor: '#FEF3C7' },
  checkDotText: { color: '#7F1D1D', fontSize: 12, fontWeight: '900' },
  checkCopy: { flex: 1, marginLeft: 9 },
  checkLabel: { color: '#1E293B', fontSize: 11, fontWeight: '800' },
  checkMeta: { color: '#94A3B8', fontSize: 8, marginTop: 2 },
  checkValueWrap: { alignItems: 'flex-end', marginLeft: 8 },
  checkCount: { color: '#0F172A', fontSize: 13, fontWeight: '900' },
  checkAmount: { color: '#64748B', fontSize: 8, marginTop: 2 },
  allClearText: { color: '#047857', fontSize: 11, fontWeight: '700', lineHeight: 17, marginTop: 12 },
  warningFootnote: { color: '#92400E', fontSize: 9, lineHeight: 14, marginTop: 10 },
  blockedStrip: { backgroundColor: '#FEF2F2', borderRadius: 9, marginTop: 12, padding: 9 },
  blockedStripText: { color: '#B91C1C', fontSize: 10, fontWeight: '800', textAlign: 'center' },
  metricLabel: { color: '#94A3B8', fontSize: 8, fontWeight: '900', letterSpacing: 0.6 },
  metricValue: { color: '#FFFFFF', fontSize: 13, fontWeight: '800', marginTop: 3 },
  card: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 18, borderWidth: 1, marginTop: 14, padding: 16 },
  cardTitle: { color: '#0F172A', fontSize: 17, fontWeight: '900' },
  cardSubtitle: { color: '#64748B', fontSize: 11, lineHeight: 16, marginTop: 3 },
  flowList: { marginTop: 12 },
  flowRow: { alignItems: 'center', borderBottomColor: '#F1F5F9', borderBottomWidth: 1, flexDirection: 'row', minHeight: 43 },
  flowSign: { alignItems: 'center', borderRadius: 8, height: 26, justifyContent: 'center', marginRight: 9, width: 26 },
  flowSignIn: { backgroundColor: '#DCFCE7' },
  flowSignOut: { backgroundColor: '#FEE2E2' },
  flowSignNeutral: { backgroundColor: '#E2E8F0' },
  flowSignText: { color: '#334155', fontSize: 13, fontWeight: '900' },
  flowLabel: { color: '#475569', flex: 1, fontSize: 12, fontWeight: '700' },
  flowAmount: { color: '#334155', fontSize: 12, fontWeight: '900' },
  inText: { color: '#047857' },
  outText: { color: '#B91C1C' },
  fieldLabel: { color: '#64748B', fontSize: 9, fontWeight: '900', letterSpacing: 0.8, marginBottom: 6, marginTop: 13 },
  segmentRow: { flexDirection: 'row', gap: 8 },
  segment: { alignItems: 'center', backgroundColor: '#F1F5F9', borderColor: '#E2E8F0', borderRadius: 10, borderWidth: 1, flex: 1, paddingVertical: 10 },
  segmentIn: { backgroundColor: '#047857', borderColor: '#047857' },
  segmentOut: { backgroundColor: '#B91C1C', borderColor: '#B91C1C' },
  segmentText: { color: '#475569', fontSize: 12, fontWeight: '900' },
  segmentTextOn: { color: '#FFFFFF' },
  amountInputWrap: { alignItems: 'center', backgroundColor: '#F8FAFC', borderColor: '#CBD5E1', borderRadius: 12, borderWidth: 1.5, flexDirection: 'row', height: 58, paddingHorizontal: 14 },
  currency: { color: '#334155', fontSize: 22, fontWeight: '900' },
  amountInput: { color: '#0F172A', flex: 1, fontSize: 25, fontWeight: '900', paddingHorizontal: 8 },
  input: { backgroundColor: '#F8FAFC', borderColor: '#CBD5E1', borderRadius: 11, borderWidth: 1, color: '#0F172A', minHeight: 48, paddingHorizontal: 12, paddingVertical: 11 },
  noteInput: { minHeight: 72, textAlignVertical: 'top' },
  primaryButton: { alignItems: 'center', backgroundColor: '#334155', borderRadius: 12, justifyContent: 'center', marginTop: 17, minHeight: 50 },
  closeButton: { alignItems: 'center', backgroundColor: '#0F172A', borderRadius: 12, justifyContent: 'center', marginTop: 17, minHeight: 50 },
  primaryButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
  disabled: { opacity: 0.5 },
  labelRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  useExpected: { color: '#0F766E', fontSize: 11, fontWeight: '900', marginTop: 10 },
  differenceStrip: { alignItems: 'center', backgroundColor: '#F8FAFC', borderRadius: 10, flexDirection: 'row', justifyContent: 'space-between', marginTop: 9, padding: 11 },
  differenceLabel: { color: '#475569', fontSize: 11, fontWeight: '800' },
  differenceValue: { color: '#334155', fontSize: 13, fontWeight: '900' },
  closedCard: { borderColor: '#CBD5E1' },
  closedHeading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  lockIcon: { color: '#047857', fontSize: 24, fontWeight: '900' },
  closedTotals: { backgroundColor: '#F8FAFC', borderRadius: 12, flexDirection: 'row', justifyContent: 'space-between', marginTop: 13, padding: 13 },
  metricDarkLabel: { color: '#64748B', fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  metricDarkValue: { color: '#0F172A', fontSize: 18, fontWeight: '900', marginTop: 3 },
  alignRight: { alignItems: 'flex-end' },
  closingNote: { color: '#64748B', fontSize: 11, fontStyle: 'italic', marginTop: 11 },
  secondaryButton: { alignItems: 'center', borderColor: '#94A3B8', borderRadius: 11, borderWidth: 1, justifyContent: 'center', marginTop: 13, minHeight: 45 },
  secondaryButtonText: { color: '#475569', fontSize: 12, fontWeight: '900' },
  entriesSection: { marginTop: 20 },
  entriesHeading: { alignItems: 'center', flexDirection: 'row' },
  sectionTitle: { color: '#0F172A', fontSize: 18, fontWeight: '900' },
  countBadge: { alignItems: 'center', backgroundColor: '#E2E8F0', borderRadius: 12, height: 26, justifyContent: 'center', marginLeft: 'auto', minWidth: 26, paddingHorizontal: 8 },
  countText: { color: '#334155', fontSize: 11, fontWeight: '900' },
  empty: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 14, borderWidth: 1, marginTop: 10, padding: 24 },
  emptyTitle: { color: '#334155', fontSize: 14, fontWeight: '800' },
  emptyText: { color: '#94A3B8', fontSize: 11, marginTop: 4, textAlign: 'center' },
  entryRow: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 14, borderWidth: 1, flexDirection: 'row', marginTop: 8, padding: 12 },
  voidedRow: { backgroundColor: '#F8FAFC' },
  entryDirection: { alignItems: 'center', borderRadius: 10, height: 40, justifyContent: 'center', width: 40 },
  entryDirectionIn: { backgroundColor: '#DCFCE7' },
  entryDirectionOut: { backgroundColor: '#FEE2E2' },
  entryDirectionText: { color: '#334155', fontSize: 18, fontWeight: '900' },
  entryCopy: { flex: 1, marginLeft: 10 },
  entryLabel: { color: '#0F172A', fontSize: 13, fontWeight: '900' },
  entryMeta: { color: '#64748B', fontSize: 9, marginTop: 3 },
  entryAmountCopy: { alignItems: 'flex-end', marginLeft: 7 },
  entryAmount: { fontSize: 13, fontWeight: '900' },
  voidAction: { color: '#B91C1C', fontSize: 10, fontWeight: '900', marginTop: 6 },
  voidReason: { color: '#B91C1C', fontSize: 9, marginTop: 3 },
  voidedText: { color: '#94A3B8', textDecorationLine: 'line-through' },
  modalOverlay: { alignItems: 'center', backgroundColor: 'rgba(15,23,42,0.58)', flex: 1, justifyContent: 'center', padding: 20 },
  modalCard: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 18, width: '100%' },
  modalTitle: { color: '#0F172A', fontSize: 18, fontWeight: '900' },
  modalMessage: { color: '#64748B', fontSize: 12, lineHeight: 18, marginBottom: 12, marginTop: 5 },
  modalActions: { flexDirection: 'row', gap: 9, marginTop: 14 },
  modalCancel: { alignItems: 'center', borderColor: '#CBD5E1', borderRadius: 10, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 46 },
  modalCancelText: { color: '#475569', fontSize: 12, fontWeight: '900' },
  modalConfirm: { alignItems: 'center', backgroundColor: '#334155', borderRadius: 10, flex: 1, justifyContent: 'center', minHeight: 46 },
});
