import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  header: {
    backgroundColor: '#0F766E',
    paddingHorizontal: 18,
    paddingBottom: 17,
    paddingTop: 54,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  headerCopy: { flex: 1 },
  backButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.14)', borderRadius: 18, height: 36, justifyContent: 'center', width: 36 },
  backButtonText: { color: '#FFF', fontSize: 20, fontWeight: '800' },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  title: {
    fontSize: 22,
    fontWeight: '900',
    color: '#fff',
    marginBottom: 4,
  },
  headerSubtitle: { color: '#CCFBF1', fontSize: 11 },
  userEmail: {
    fontSize: 12,
    color: '#DBEAFE',
  },
  languageButton: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 10,
  },
  languageButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  logoutButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  logoutText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  dateButton: {
    padding: 12,
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    marginHorizontal: 8,
  },
  dateButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#374151',
  },
  dateText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginHorizontal: 12,
  },
  todayButton: {
    padding: 12,
    backgroundColor: '#3B82F6',
    borderRadius: 8,
    marginLeft: 8,
  },
  todayButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  contentContainer: { paddingBottom: 30 },
  loader: {
    marginTop: 32,
  },
  summaryContainer: {
    padding: 14,
  },
  summaryCard: {
    backgroundColor: '#0F172A',
    borderRadius: 18,
    padding: 17,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    minHeight: 142,
  },
  purchaseCard: {
    borderBottomColor: '#10B981',
  },
  salesCard: {
    borderBottomColor: '#F59E0B',
  },
  balanceCard: {
    borderBottomColor: '#3B82F6',
  },
  summaryLabel: {
    fontSize: 9,
    color: '#94A3B8',
    marginBottom: 6,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryValue: {
    fontSize: 25,
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: 2,
  },
  summarySubValue: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  negativeValue: {
    color: '#FCA5A5',
  },
  summaryFlowRow: { borderTopColor: 'rgba(255,255,255,0.14)', borderTopWidth: 1, flexDirection: 'row', marginTop: 15, paddingTop: 12 },
  summaryFlowItem: { flex: 1 },
  summaryFlowDivider: { borderLeftColor: 'rgba(255,255,255,0.14)', borderLeftWidth: 1, paddingLeft: 13 },
  summaryFlowLabel: { color: '#94A3B8', fontSize: 8, fontWeight: '800', letterSpacing: 0.5, textTransform: 'uppercase' },
  summaryFlowIn: { color: '#5EEAD4', fontSize: 12, fontWeight: '800', marginTop: 4 },
  summaryFlowOut: { color: '#FDBA74', fontSize: 12, fontWeight: '800', marginTop: 4 },
  positiveValue: {
    color: '#10B981',
  },
  salesColor: {
    color: '#F59E0B',
  },
  balanceColor: {
    color: '#3B82F6',
  },
  balanceNumber: {
    fontWeight: 'bold',
  },
  balancePositive: {
    color: '#10B981',
  },
  balanceNegative: {
    color: '#DC2626',
  },
  balanceTotal: {
    color: '#6B7280',
    fontWeight: 'normal',
  },
  stockOverviewContainer: {
    backgroundColor: '#fff',
    margin: 14,
    marginTop: 0,
    borderRadius: 16,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 2,
    letterSpacing: 0.3,
  },
  sectionHeading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 13 },
  sectionSubtitle: { color: '#94A3B8', fontSize: 10, marginTop: 2 },
  itemCountBadge: { alignItems: 'center', backgroundColor: '#ECFDF5', borderRadius: 12, justifyContent: 'center', minWidth: 30, paddingHorizontal: 8, paddingVertical: 5 },
  itemCountText: { color: '#047857', fontSize: 11, fontWeight: '900' },
  emptyText: {
    textAlign: 'center',
    color: '#6B7280',
    fontSize: 16,
    paddingVertical: 32,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F9FAFB',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  tableHeaderText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  tableHeaderRight: {
    textAlign: 'right',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  criticalRow: {
    backgroundColor: '#FFF7F7',
  },
  lowRow: {
    backgroundColor: '#FFFFFF',
  },
  fishColumn: {
    flex: 2.5,
    justifyContent: 'center',
    paddingRight: 16,
  },
  dataColumn: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingHorizontal: 8,
  },
  fishNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  fishName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111827',
  },
  sizeBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    minWidth: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sizeBadgeBig: {
    backgroundColor: '#DBEAFE',
    borderWidth: 1,
    borderColor: '#3B82F6',
  },
  sizeBadgeOverBig: {
    backgroundColor: '#F3E8FF',
    borderWidth: 1,
    borderColor: '#9333EA',
  },
  sizeBadgeMedium: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#F59E0B',
  },
  sizeBadgeSmall: {
    backgroundColor: '#D1FAE5',
    borderWidth: 1,
    borderColor: '#10B981',
  },
  sizeBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#374151',
  },
  dataValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#111827',
    textAlign: 'right',
  },
  dataSubValue: {
    fontSize: 10,
    color: '#6B7280',
    marginTop: 2,
    textAlign: 'right',
  },
  salesDetailsContainer: {
    backgroundColor: '#fff',
    margin: 16,
    marginTop: 0,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 32,
  },
  salesDetailsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  customersBadge: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  customersBadgeText: {
    color: '#1E40AF',
    fontSize: 12,
    fontWeight: '600',
  },
  customerCard: {
    backgroundColor: '#FAFAFA',
    borderRadius: 10,
    marginBottom: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  customerCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
    backgroundColor: '#F9FAFB',
  },
  customerCardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  collapseIcon: {
    fontSize: 10,
    color: '#6B7280',
    width: 12,
    flexShrink: 0,
  },
  customerCardNameContainer: {
    flex: 1,
    minWidth: 0,
  },
  customerCardName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 2,
  },
  customerCardSubtext: {
    fontSize: 11,
    color: '#6B7280',
  },
  customerCardHeaderRight: {
    alignItems: 'flex-end',
    marginLeft: 12,
    flexShrink: 0,
    minWidth: 60,
  },
  customerCardTotal: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F59E0B',
  },
  customerCardTotalKg: {
    fontSize: 11,
    color: '#9CA3AF',
    marginTop: 2,
  },
  customerCardBody: {
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingTop: 8,
  },
  saleItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingLeft: 22,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  saleItemRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 12,
  },
  saleItemName: {
    fontSize: 13,
    fontWeight: '500',
    color: '#374151',
    flex: 1,
  },
  saleItemQuantity: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
  },
});
