import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { backgroundColor: '#FFF7ED', flex: 1 },
  header: { alignItems: 'center', backgroundColor: '#9A3412', flexDirection: 'row', minHeight: 108, paddingBottom: 16, paddingHorizontal: 18, paddingTop: 48 },
  backButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.14)', borderRadius: 12, height: 42, justifyContent: 'center', marginRight: 12, width: 42 },
  backIcon: { color: '#FFFFFF', fontSize: 34, fontWeight: '300', lineHeight: 36 },
  eyebrow: { color: '#FED7AA', fontSize: 9, fontWeight: '900', letterSpacing: 1.1 },
  title: { color: '#FFFFFF', fontSize: 23, fontWeight: '900', marginTop: 2 },
  content: { flex: 1 },
  contentContainer: { padding: 14, paddingBottom: 44 },
  summaryCard: { backgroundColor: '#7C2D12', borderRadius: 18, padding: 17 },
  summaryLabel: { color: '#FED7AA', fontSize: 9, fontWeight: '900', letterSpacing: 0.9 },
  summaryTotal: { color: '#FFFFFF', fontSize: 30, fontWeight: '900', marginTop: 4 },
  summaryMetrics: { borderTopColor: 'rgba(255,255,255,0.18)', borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, paddingTop: 12 },
  metricLabel: { color: '#FDBA74', fontSize: 8, fontWeight: '900', letterSpacing: 0.6 },
  metricValue: { color: '#FFFFFF', fontSize: 13, fontWeight: '800', marginTop: 3 },
  formCard: { backgroundColor: '#FFFFFF', borderColor: '#FED7AA', borderRadius: 18, borderWidth: 1, marginTop: 14, padding: 16 },
  formHeading: { alignItems: 'center', flexDirection: 'row', marginBottom: 16 },
  formIcon: { alignItems: 'center', backgroundColor: '#FFEDD5', borderRadius: 12, height: 38, justifyContent: 'center', marginRight: 10, width: 38 },
  formIconText: { color: '#C2410C', fontSize: 18, fontWeight: '900' },
  formTitle: { color: '#0F172A', fontSize: 17, fontWeight: '900' },
  formSubtitle: { color: '#64748B', fontSize: 11, marginTop: 2 },
  labelRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  fieldLabel: { color: '#64748B', fontSize: 9, fontWeight: '900', letterSpacing: 0.8, marginBottom: 6, marginTop: 13 },
  addCategory: { color: '#C2410C', fontSize: 11, fontWeight: '900', marginTop: 10 },
  quickCategorySection: { marginBottom: 8 },
  quickCategoryLabel: { color: '#94A3B8', fontSize: 8, fontWeight: '900', letterSpacing: 0.7, marginBottom: 6 },
  quickCategoryRow: { gap: 7, paddingRight: 4 },
  quickCategoryChip: { backgroundColor: '#FFF7ED', borderColor: '#FED7AA', borderRadius: 10, borderWidth: 1, maxWidth: 130, paddingHorizontal: 11, paddingVertical: 8 },
  quickCategoryChipOn: { backgroundColor: '#C2410C', borderColor: '#C2410C' },
  quickCategoryText: { color: '#9A3412', fontSize: 10, fontWeight: '800' },
  quickCategoryTextOn: { color: '#FFFFFF' },
  categorySelect: { alignItems: 'center', backgroundColor: '#F8FAFC', borderColor: '#CBD5E1', borderRadius: 12, borderWidth: 1, flexDirection: 'row', minHeight: 56, paddingHorizontal: 13, paddingVertical: 9 },
  categorySelectCopy: { flex: 1 },
  categorySelectHint: { color: '#94A3B8', fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  categorySelectValue: { color: '#0F172A', fontSize: 15, fontWeight: '800', marginTop: 3 },
  categorySelectPlaceholder: { color: '#94A3B8' },
  categorySelectChevron: { color: '#64748B', fontSize: 20, fontWeight: '800', marginLeft: 10 },
  amountWrap: { alignItems: 'center', backgroundColor: '#FFF7ED', borderColor: '#FDBA74', borderRadius: 12, borderWidth: 1.5, flexDirection: 'row', height: 58, paddingHorizontal: 14 },
  currency: { color: '#C2410C', fontSize: 22, fontWeight: '900' },
  amountInput: { color: '#0F172A', flex: 1, fontSize: 25, fontWeight: '900', paddingHorizontal: 8 },
  methodRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  moreMethodRow: { backgroundColor: '#F8FAFC', borderRadius: 10, flexDirection: 'row', gap: 7, marginTop: 7, padding: 8 },
  methodChip: { backgroundColor: '#F1F5F9', borderColor: '#E2E8F0', borderRadius: 9, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 9 },
  methodChipOn: { backgroundColor: '#9A3412', borderColor: '#9A3412' },
  methodText: { color: '#475569', fontSize: 11, fontWeight: '800' },
  methodTextOn: { color: '#FFFFFF' },
  input: { backgroundColor: '#F8FAFC', borderColor: '#CBD5E1', borderRadius: 11, borderWidth: 1, color: '#0F172A', minHeight: 48, paddingHorizontal: 12, paddingVertical: 11 },
  notesInput: { minHeight: 76, textAlignVertical: 'top' },
  submitButton: { alignItems: 'center', backgroundColor: '#C2410C', borderRadius: 12, justifyContent: 'center', marginTop: 18, minHeight: 52 },
  submitText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' },
  disabled: { opacity: 0.5 },
  listSection: { marginTop: 20 },
  listHeading: { alignItems: 'center', flexDirection: 'row' },
  listTitle: { color: '#0F172A', fontSize: 18, fontWeight: '900' },
  listSubtitle: { color: '#64748B', fontSize: 11, marginTop: 2 },
  countBadge: { alignItems: 'center', backgroundColor: '#FFEDD5', borderRadius: 12, height: 26, justifyContent: 'center', marginLeft: 'auto', minWidth: 26, paddingHorizontal: 8 },
  countText: { color: '#C2410C', fontSize: 11, fontWeight: '900' },
  search: { backgroundColor: '#FFFFFF', borderColor: '#FED7AA', borderRadius: 11, borderWidth: 1, color: '#0F172A', height: 46, marginTop: 12, paddingHorizontal: 12 },
  filterRow: { flexDirection: 'row', gap: 7, marginVertical: 9 },
  filterChip: { backgroundColor: '#FFEDD5', borderRadius: 9, paddingHorizontal: 13, paddingVertical: 8 },
  filterChipOn: { backgroundColor: '#9A3412' },
  filterText: { color: '#9A3412', fontSize: 11, fontWeight: '800' },
  filterTextOn: { color: '#FFFFFF' },
  loader: { marginVertical: 28 },
  empty: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#FED7AA', borderRadius: 14, borderWidth: 1, padding: 24 },
  emptyTitle: { color: '#334155', fontSize: 14, fontWeight: '800' },
  emptyText: { color: '#94A3B8', fontSize: 11, marginTop: 4 },
  expenseRow: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#FED7AA', borderRadius: 14, borderWidth: 1, flexDirection: 'row', marginBottom: 8, padding: 12 },
  voidedRow: { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0' },
  categoryIcon: { alignItems: 'center', backgroundColor: '#FFEDD5', borderRadius: 10, height: 42, justifyContent: 'center', width: 42 },
  voidedIcon: { backgroundColor: '#E2E8F0' },
  categoryInitial: { color: '#9A3412', fontSize: 16, fontWeight: '900' },
  expenseCopy: { flex: 1, marginLeft: 11 },
  categoryName: { color: '#0F172A', fontSize: 14, fontWeight: '900' },
  expenseMeta: { color: '#64748B', fontSize: 9, marginTop: 3 },
  expenseNote: { color: '#94A3B8', fontSize: 10, marginTop: 3 },
  voidReason: { color: '#B91C1C', fontSize: 9, fontWeight: '700', marginTop: 4 },
  amountCopy: { alignItems: 'flex-end', marginLeft: 8 },
  rowAmount: { color: '#9A3412', fontSize: 14, fontWeight: '900' },
  voidAction: { color: '#B91C1C', fontSize: 10, fontWeight: '800', marginTop: 7 },
  voidedText: { color: '#94A3B8', textDecorationLine: 'line-through' },
  modalOverlay: { alignItems: 'center', backgroundColor: 'rgba(15,23,42,0.55)', flex: 1, justifyContent: 'center', padding: 20 },
  modalCard: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 18, width: '100%' },
  modalTitle: { color: '#0F172A', fontSize: 19, fontWeight: '900' },
  modalText: { color: '#64748B', fontSize: 13, lineHeight: 19, marginTop: 6 },
  modalActions: { flexDirection: 'row', gap: 9, marginTop: 16 },
  modalCancel: { alignItems: 'center', borderColor: '#CBD5E1', borderRadius: 10, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 46 },
  modalCancelText: { color: '#475569', fontSize: 13, fontWeight: '800' },
  modalConfirm: { alignItems: 'center', backgroundColor: '#C2410C', borderRadius: 10, flex: 1, justifyContent: 'center', minHeight: 46 },
  voidConfirm: { alignItems: 'center', backgroundColor: '#B91C1C', borderRadius: 10, flex: 1, justifyContent: 'center', minHeight: 46 },
  modalConfirmText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
});
