import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { backgroundColor: '#F4F8F7', flex: 1 },
  header: { alignItems: 'center', backgroundColor: '#0F766E', flexDirection: 'row', minHeight: 108, paddingBottom: 16, paddingHorizontal: 18, paddingTop: 48 },
  backButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: 12, height: 42, justifyContent: 'center', marginRight: 12, width: 42 },
  backIcon: { color: '#FFF', fontSize: 34, fontWeight: '300', lineHeight: 36 },
  eyebrow: { color: '#99F6E4', fontSize: 9, fontWeight: '900', letterSpacing: 1.1 },
  title: { color: '#FFF', fontSize: 23, fontWeight: '900', marginTop: 2 },
  weekNavigator: { alignItems: 'center', backgroundColor: '#FFF', borderBottomColor: '#DCE9E6', borderBottomWidth: 1, flexDirection: 'row', minHeight: 74, paddingHorizontal: 12 },
  weekArrow: { alignItems: 'center', backgroundColor: '#F0FDFA', borderRadius: 10, height: 42, justifyContent: 'center', width: 42 },
  weekArrowDisabled: { backgroundColor: '#F8FAFC' },
  weekArrowText: { color: '#0F766E', fontSize: 22, fontWeight: '800' },
  weekArrowTextDisabled: { color: '#CBD5E1' },
  weekCopy: { alignItems: 'center', flex: 1 },
  weekLabel: { color: '#94A3B8', fontSize: 8, fontWeight: '900', letterSpacing: 0.8 },
  weekDates: { color: '#0F172A', fontSize: 11, fontWeight: '900', marginTop: 3 },
  nextButton: { backgroundColor: '#0F766E', borderRadius: 9, marginLeft: 7, paddingHorizontal: 8, paddingVertical: 9 },
  nextButtonText: { color: '#FFF', fontSize: 8, fontWeight: '900' },
  content: { flex: 1 },
  contentContainer: { padding: 13, paddingBottom: 90 },
  advisory: { alignItems: 'center', backgroundColor: '#CCFBF1', borderColor: '#99F6E4', borderRadius: 13, borderWidth: 1, flexDirection: 'row', marginBottom: 12, padding: 12 },
  advisoryCopy: { flex: 1, paddingRight: 8 },
  advisoryTitle: { color: '#115E59', fontSize: 11, fontWeight: '900' },
  advisoryText: { color: '#0F766E', fontSize: 9, lineHeight: 14, marginTop: 2 },
  refreshButton: { backgroundColor: '#FFF', borderColor: '#5EEAD4', borderRadius: 8, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 8 },
  refreshText: { color: '#0F766E', fontSize: 9, fontWeight: '900' },
  dayTabs: { gap: 7, paddingBottom: 11 },
  dayTab: { alignItems: 'center', backgroundColor: '#FFF', borderColor: '#DCE9E6', borderRadius: 11, borderWidth: 1, minWidth: 58, paddingHorizontal: 8, paddingVertical: 8 },
  dayTabOn: { backgroundColor: '#0F766E', borderColor: '#0F766E' },
  dayTabName: { color: '#64748B', fontSize: 8, fontWeight: '900', textTransform: 'uppercase' },
  dayTabNameOn: { color: '#99F6E4' },
  dayTabDate: { color: '#0F172A', fontSize: 14, fontWeight: '900', marginTop: 1 },
  dayTabDateOn: { color: '#FFF' },
  dayTabTotal: { color: '#0F766E', fontSize: 8, fontWeight: '800', marginTop: 2 },
  dayTabTotalOn: { color: '#CCFBF1' },
  viewSwitch: { backgroundColor: '#E2E8F0', borderRadius: 11, flexDirection: 'row', marginBottom: 11, padding: 3 },
  viewOption: { alignItems: 'center', borderRadius: 8, flex: 1, paddingVertical: 8 },
  viewOptionOn: { backgroundColor: '#FFF' },
  viewOptionText: { color: '#64748B', fontSize: 10, fontWeight: '800' },
  viewOptionTextOn: { color: '#0F766E' },
  loading: { alignItems: 'center', paddingVertical: 54 },
  loadingText: { color: '#64748B', fontSize: 11, marginTop: 10 },
  empty: { alignItems: 'center', backgroundColor: '#FFF', borderColor: '#DCE9E6', borderRadius: 15, borderWidth: 1, padding: 28 },
  emptyTitle: { color: '#334155', fontSize: 14, fontWeight: '900' },
  emptyText: { color: '#94A3B8', fontSize: 10, marginTop: 4, textAlign: 'center' },
  dayCard: { backgroundColor: '#FFF', borderColor: '#DCE9E6', borderRadius: 16, borderWidth: 1, marginBottom: 11, overflow: 'hidden' },
  dayHeader: { alignItems: 'center', backgroundColor: '#F0FDFA', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 14, paddingVertical: 11 },
  dayName: { color: '#134E4A', fontSize: 14, fontWeight: '900' },
  dayDate: { color: '#5E7E79', fontSize: 9, marginTop: 2 },
  totalPill: { alignItems: 'center', backgroundColor: '#0F766E', borderRadius: 10, minWidth: 54, paddingHorizontal: 9, paddingVertical: 5 },
  totalValue: { color: '#FFF', fontSize: 16, fontWeight: '900' },
  totalLabel: { color: '#99F6E4', fontSize: 6, fontWeight: '900', letterSpacing: 0.6 },
  itemRow: { alignItems: 'center', borderBottomColor: '#EDF4F2', borderBottomWidth: 1, flexDirection: 'row', minHeight: 61, paddingHorizontal: 13, paddingVertical: 8 },
  itemRowLast: { borderBottomWidth: 0 },
  itemCopy: { flex: 1, paddingRight: 10 },
  itemName: { color: '#0F172A', fontSize: 12, fontWeight: '900' },
  metaRow: { alignItems: 'center', flexDirection: 'row', gap: 7, marginTop: 4 },
  confidence: { borderRadius: 7, fontSize: 7, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 6, paddingVertical: 3 },
  confidenceHigh: { backgroundColor: '#D1FAE5', color: '#047857' },
  confidenceMedium: { backgroundColor: '#FEF3C7', color: '#A16207' },
  confidenceLow: { backgroundColor: '#FEE2E2', color: '#B91C1C' },
  accuracy: { color: '#0F766E', fontSize: 7, fontWeight: '800' },
  range: { color: '#94A3B8', fontSize: 8, fontWeight: '700' },
  quantityBox: { alignItems: 'center', flexDirection: 'row' },
  quantityInput: { backgroundColor: '#F8FAFC', borderColor: '#CBD5E1', borderRadius: 9, borderWidth: 1, color: '#0F766E', fontSize: 16, fontWeight: '900', height: 40, paddingHorizontal: 5, textAlign: 'center', width: 52 },
  quantityInputChanged: { backgroundColor: '#FFFBEB', borderColor: '#F59E0B' },
  quantityUnit: { color: '#64748B', fontSize: 9, fontWeight: '800', marginLeft: 4 },
  customerNote: { color: '#64748B', fontSize: 8, fontWeight: '700', marginBottom: 7, paddingHorizontal: 2 },
  customerCard: { backgroundColor: '#FFF', borderColor: '#DCE9E6', borderRadius: 14, borderWidth: 1, marginBottom: 9, overflow: 'hidden' },
  customerHeader: { alignItems: 'center', backgroundColor: '#F0FDFA', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 10 },
  customerCopy: { flex: 1, paddingRight: 8 },
  customerName: { color: '#134E4A', fontSize: 13, fontWeight: '900' },
  customerLocation: { color: '#5E7E79', fontSize: 8, marginTop: 2 },
  customerTotal: { alignItems: 'center', backgroundColor: '#0F766E', borderRadius: 9, minWidth: 49, paddingHorizontal: 8, paddingVertical: 4 },
  customerTotalValue: { color: '#FFF', fontSize: 14, fontWeight: '900' },
  customerTotalUnit: { color: '#99F6E4', fontSize: 6, fontWeight: '900' },
  customerItem: { alignItems: 'center', borderBottomColor: '#EDF4F2', borderBottomWidth: 1, flexDirection: 'row', minHeight: 39, paddingHorizontal: 12 },
  customerItemLast: { borderBottomWidth: 0 },
  customerItemName: { color: '#1E293B', flex: 1, fontSize: 10, fontWeight: '800' },
  customerItemRange: { color: '#94A3B8', fontSize: 7, marginRight: 9 },
  customerItemQty: { color: '#0F766E', fontSize: 11, fontWeight: '900', minWidth: 35, textAlign: 'right' },
  saveBar: { alignItems: 'center', backgroundColor: '#FFF', borderTopColor: '#DCE9E6', borderTopWidth: 1, bottom: 0, flexDirection: 'row', justifyContent: 'space-between', left: 0, paddingBottom: 18, paddingHorizontal: 14, paddingTop: 10, position: 'absolute', right: 0 },
  saveHint: { color: '#92400E', fontSize: 10, fontWeight: '800' },
  saveButton: { backgroundColor: '#0F766E', borderRadius: 10, minWidth: 100, paddingHorizontal: 16, paddingVertical: 11 },
  saveButtonText: { color: '#FFF', fontSize: 11, fontWeight: '900', textAlign: 'center' },
});
