import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { backgroundColor: '#F6F8FB', flex: 1 },
  header: { alignItems: 'center', borderBottomLeftRadius: 24, borderBottomRightRadius: 24, flexDirection: 'row', justifyContent: 'space-between', paddingBottom: 22, paddingHorizontal: 18, paddingTop: 42 },
  businessName: { color: '#FFF', fontSize: 24, fontWeight: '900' },
  tagline: { color: 'rgba(255,255,255,0.78)', fontSize: 12, marginTop: 3 },
  logoutButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.16)', borderRadius: 11, height: 40, justifyContent: 'center', width: 40 },
  logoutText: { color: '#FFF', fontSize: 19, fontWeight: '800' },
  scroll: { flex: 1 },
  content: { padding: 14, paddingBottom: 42 },
  inventoryCard: { backgroundColor: '#0F172A', borderRadius: 20, marginBottom: 12, overflow: 'hidden', padding: 16 },
  inventoryHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  inventoryEyebrow: { color: '#7DD3FC', fontSize: 8, fontWeight: '900', letterSpacing: 0.9 },
  inventoryTitle: { color: '#FFF', fontSize: 17, fontWeight: '900', marginTop: 3 },
  liveBadge: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 10, flexDirection: 'row', paddingHorizontal: 8, paddingVertical: 5 },
  liveDot: { backgroundColor: '#34D399', borderRadius: 4, height: 6, marginRight: 5, width: 6 },
  liveText: { color: '#D1FAE5', fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  inventoryLoading: { alignItems: 'flex-start', height: 83, justifyContent: 'center' },
  inventoryQuantity: { color: '#FFF', fontSize: 28, fontWeight: '900', marginTop: 16 },
  inventoryQuantityLabel: { color: '#94A3B8', fontSize: 10, marginTop: 2 },
  inventoryMetrics: { borderTopColor: 'rgba(255,255,255,0.12)', borderTopWidth: 1, flexDirection: 'row', marginTop: 14, paddingTop: 12 },
  inventoryMetric: { flex: 1 },
  metricDivider: { borderLeftColor: 'rgba(255,255,255,0.12)', borderLeftWidth: 1, paddingLeft: 10 },
  metricLabel: { color: '#64748B', fontSize: 7, fontWeight: '900', letterSpacing: 0.7 },
  metricValue: { color: '#E2E8F0', fontSize: 11, fontWeight: '800', marginTop: 4 },
  inventoryFooter: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.06)', flexDirection: 'row', justifyContent: 'space-between', marginBottom: -16, marginHorizontal: -16, marginTop: 14, paddingHorizontal: 16, paddingVertical: 10 },
  inventoryFooterText: { color: '#BAE6FD', fontSize: 10, fontWeight: '800' },
  inventoryArrow: { color: '#7DD3FC', fontSize: 21 },
  section: { marginTop: 22 },
  firstSection: { marginTop: 16 },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, paddingHorizontal: 2 },
  sectionTitle: { color: '#0F172A', fontSize: 16, fontWeight: '900' },
  sectionHint: { color: '#94A3B8', fontSize: 10, fontWeight: '700' },
  actionGrid: { flexDirection: 'row', gap: 8 },
  actionCard: { backgroundColor: '#FFF', borderColor: '#E2E8F0', borderRadius: 15, borderWidth: 1, flex: 1, minHeight: 116, padding: 11 },
  actionIcon: { alignItems: 'center', borderRadius: 9, height: 32, justifyContent: 'center', marginBottom: 9, width: 32 },
  actionIconText: { fontSize: 18, fontWeight: '900' },
  actionTitle: { color: '#0F172A', fontSize: 12, fontWeight: '900' },
  actionSubtitle: { color: '#64748B', fontSize: 9, lineHeight: 12, marginTop: 4 },
  moreButton: { alignItems: 'center', backgroundColor: '#FFF', borderColor: '#CBD5E1', borderRadius: 14, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: 24, paddingHorizontal: 16, paddingVertical: 14 },
  moreTitle: { color: '#334155', fontSize: 14, fontWeight: '900' },
  moreSubtitle: { color: '#94A3B8', fontSize: 10, marginTop: 2 },
  moreChevron: { color: '#64748B', fontSize: 14, fontWeight: '900' },
  secondarySection: { marginTop: 18 },
  secondaryTitle: { color: '#64748B', fontSize: 10, fontWeight: '900', letterSpacing: 0.9, marginBottom: 8, paddingHorizontal: 2 },
  secondaryGrid: { backgroundColor: '#FFF', borderColor: '#E2E8F0', borderRadius: 14, borderWidth: 1, overflow: 'hidden' },
  secondaryRow: { alignItems: 'center', borderBottomColor: '#F1F5F9', borderBottomWidth: 1, flexDirection: 'row', minHeight: 52, paddingHorizontal: 13 },
  secondaryRowLast: { borderBottomWidth: 0 },
  secondaryIcon: { color: '#475569', fontSize: 17, textAlign: 'center', width: 30 },
  secondaryCopy: { flex: 1, marginLeft: 8 },
  secondaryLabel: { color: '#1E293B', fontSize: 13, fontWeight: '800' },
  secondaryHint: { color: '#94A3B8', fontSize: 9, marginTop: 2 },
  secondaryArrow: { color: '#CBD5E1', fontSize: 18 },
  footer: { alignItems: 'center', paddingTop: 28 },
  footerText: { color: '#CBD5E1', fontSize: 10, fontWeight: '700' },
});
