import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { backgroundColor: '#F4F8FA', flex: 1 },
  header: { alignItems: 'center', backgroundColor: '#0E7490', flexDirection: 'row', paddingBottom: 18, paddingHorizontal: 18, paddingTop: 44 },
  backButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: 12, height: 42, justifyContent: 'center', marginRight: 14, width: 42 },
  backText: { color: '#FFFFFF', fontSize: 30, lineHeight: 32 },
  eyebrow: { color: '#A5F3FC', fontSize: 9, fontWeight: '900', letterSpacing: 1 },
  title: { color: '#FFFFFF', fontSize: 25, fontWeight: '900', marginTop: 2 },
  moneyButton: { backgroundColor: '#FFFFFF', borderRadius: 9, marginLeft: 'auto', paddingHorizontal: 11, paddingVertical: 9 },
  moneyButtonText: { color: '#0E7490', fontSize: 10, fontWeight: '900' },
  content: { flex: 1 },
  contentContainer: { padding: 14, paddingBottom: 40 },
  summaryCard: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#CFFAFE', borderRadius: 16, borderWidth: 1, flexDirection: 'row', padding: 14 },
  primarySummary: { minWidth: 72 },
  primaryValue: { color: '#047857', fontSize: 28, fontWeight: '900' },
  primaryLabel: { color: '#64748B', fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  summaryDivider: { alignSelf: 'stretch', borderLeftColor: '#E2E8F0', borderLeftWidth: 1, marginHorizontal: 8 },
  summaryMetric: { flex: 1 },
  metricValue: { color: '#0F172A', fontSize: 13, fontWeight: '900' },
  metricLabel: { color: '#94A3B8', fontSize: 6.5, fontWeight: '900', letterSpacing: 0.3, marginTop: 3 },
  stageSummary: { flex: 1.8, flexDirection: 'row', flexWrap: 'wrap' },
  stageMetric: { alignItems: 'baseline', flexDirection: 'row', marginRight: 8 },
  stageSymbol: { color: '#A16207', fontSize: 11, fontWeight: '900', marginRight: 2 },
  stageValue: { color: '#0F172A', fontSize: 13, fontWeight: '900' },
  stageLabel: { color: '#94A3B8', fontSize: 6.5, fontWeight: '900', letterSpacing: 0.3, marginTop: 2, width: '100%' },
  exceptionSummary: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: '#F5F3FF', borderColor: '#DDD6FE', borderRadius: 12, borderWidth: 1, flexDirection: 'row', marginTop: 8, paddingHorizontal: 10, paddingVertical: 6 },
  exceptionSummaryDot: { backgroundColor: '#7C3AED', borderRadius: 4, height: 7, marginRight: 6, width: 7 },
  exceptionSummaryText: { color: '#6D28D9', fontSize: 10, fontWeight: '800' },
  sampleCard: { backgroundColor: '#ECFEFF', borderColor: '#A5F3FC', borderRadius: 12, borderWidth: 1, marginTop: 9, paddingHorizontal: 10, paddingVertical: 8 },
  sampleHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  sampleTitleRow: { alignItems: 'center', flexDirection: 'row' },
  sampleEyebrow: { color: '#0E7490', fontSize: 8, fontWeight: '900', letterSpacing: 0.6 },
  sampleTitle: { color: '#164E63', fontSize: 15, fontWeight: '900', marginLeft: 9 },
  changeColumnButton: { backgroundColor: '#FFFFFF', borderColor: '#A5F3FC', borderRadius: 8, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 6 },
  changeColumnText: { color: '#0E7490', fontSize: 10, fontWeight: '900' },
  columnPicker: { flexDirection: 'row', gap: 4, marginTop: 8 },
  columnButton: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#C7E8ED', borderRadius: 7, borderWidth: 1, flex: 1, height: 28, justifyContent: 'center' },
  columnButtonSelected: { backgroundColor: '#0E7490', borderColor: '#0E7490' },
  columnButtonText: { color: '#475569', fontSize: 9, fontWeight: '900' },
  columnButtonTextSelected: { color: '#FFFFFF' },
  instruction: { color: '#334155', fontSize: 11, fontWeight: '700', lineHeight: 15, marginBottom: 8, marginTop: 14 },
  legend: { flexDirection: 'row', justifyContent: 'space-between' },
  legendItem: { alignItems: 'center', flexDirection: 'row' },
  legendBadge: { alignItems: 'center', borderRadius: 5, height: 21, justifyContent: 'center', width: 21 },
  legendShort: { fontSize: 10, fontWeight: '900' },
  legendLabel: { color: '#64748B', fontSize: 7, fontWeight: '700', marginLeft: 3 },
  gridCard: { alignSelf: 'center', backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 14, borderWidth: 1, marginTop: 12, padding: 7 },
  gridHeader: { alignItems: 'center', flexDirection: 'row', marginBottom: 3 },
  gridRow: { alignItems: 'center', flexDirection: 'row', marginBottom: 3 },
  rowLabel: { alignItems: 'center', justifyContent: 'center', width: 22 },
  rowNumber: { color: '#64748B', fontSize: 8, fontWeight: '800', lineHeight: 10, textAlign: 'center' },
  rowChecked: { color: '#059669', fontSize: 7, fontWeight: '900', lineHeight: 7 },
  columnLabel: { color: '#64748B', fontSize: 8, fontWeight: '900', textAlign: 'center' },
  regularColumn: { width: 21 },
  sampleColumnLabel: { color: '#0E7490', fontSize: 11, width: 30 },
  cell: { alignItems: 'center', borderRadius: 4, borderWidth: 1, height: 25, justifyContent: 'center' },
  regularCell: { width: 21 },
  cellText: { fontSize: 10, fontWeight: '900' },
  carriedCell: { opacity: 0.62 },
  sampleCell: { borderRadius: 6, borderWidth: 2, height: 29, opacity: 1, width: 30 },
  uncheckedSampleCell: { borderStyle: 'dashed' },
  overrideCell: { borderColor: '#7C3AED', borderWidth: 2 },
  overrideDot: { backgroundColor: '#7C3AED', borderRadius: 2, height: 4, position: 'absolute', right: 2, top: 2, width: 4 },
  savingCell: { opacity: 0.3 },
  removedCell: { backgroundColor: '#E2E8F0', borderColor: '#94A3B8' },
  removedText: { color: '#64748B', fontSize: 13, fontWeight: '900' },
  loading: { alignItems: 'center', height: 490, justifyContent: 'center', width: 308 },
  loadingText: { color: '#64748B', fontSize: 11, marginTop: 8 },
  gridNote: { alignItems: 'center', flexDirection: 'row', marginTop: 9 },
  highlightSample: { backgroundColor: '#E0F2FE', borderColor: '#0369A1', borderRadius: 3, borderStyle: 'dashed', borderWidth: 2, height: 18, marginRight: 7, width: 18 },
  gridNoteText: { color: '#64748B', flex: 1, fontSize: 9, lineHeight: 13 },
  exceptionLegend: { alignItems: 'center', flexDirection: 'row', marginLeft: 2, marginTop: 6 },
  exceptionLegendDot: { backgroundColor: '#7C3AED', borderRadius: 4, height: 7, marginRight: 7, width: 7 },
  exceptionLegendText: { color: '#64748B', fontSize: 9, lineHeight: 13 },
  verifyButton: { alignItems: 'center', backgroundColor: '#0E7490', borderRadius: 12, justifyContent: 'center', marginTop: 14, minHeight: 48 },
  verifyButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
  completeCard: { alignItems: 'center', backgroundColor: '#D1FAE5', borderColor: '#6EE7B7', borderRadius: 12, borderWidth: 1, marginTop: 14, padding: 14 },
  completeText: { color: '#047857', fontSize: 13, fontWeight: '900' },
  modalOverlay: { alignItems: 'center', backgroundColor: 'rgba(15, 23, 42, 0.58)', flex: 1, justifyContent: 'center', padding: 24 },
  statusPicker: { backgroundColor: '#FFFFFF', borderRadius: 18, maxWidth: 360, padding: 18, width: '100%' },
  statusPickerEyebrow: { color: '#0E7490', fontSize: 9, fontWeight: '900', letterSpacing: 0.8 },
  statusPickerTitle: { color: '#0F172A', fontSize: 21, fontWeight: '900', marginTop: 3 },
  statusOptions: { gap: 8, marginTop: 16 },
  statusOption: { alignItems: 'center', borderColor: '#E2E8F0', borderRadius: 12, borderWidth: 1, flexDirection: 'row', minHeight: 50, paddingHorizontal: 12 },
  statusOptionSelected: { backgroundColor: '#F0FDFA', borderColor: '#5EEAD4', borderWidth: 2 },
  statusOptionBadge: { alignItems: 'center', borderRadius: 8, height: 32, justifyContent: 'center', width: 32 },
  statusOptionShort: { fontSize: 15, fontWeight: '900' },
  statusOptionLabel: { color: '#334155', fontSize: 14, fontWeight: '800', marginLeft: 12 },
  statusOptionCheck: { color: '#0F766E', fontSize: 17, fontWeight: '900', marginLeft: 'auto' },
  statusCancel: { alignItems: 'center', marginTop: 10, paddingVertical: 10 },
  statusCancelText: { color: '#64748B', fontSize: 13, fontWeight: '800' },
});
