import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F3F4F6' },
  header: { backgroundColor: '#0F766E', paddingTop: 56, paddingHorizontal: 20, paddingBottom: 20 },
  title: { color: '#FFFFFF', fontSize: 24, fontWeight: '700' },
  subtitle: { color: '#CCFBF1', fontSize: 13, marginTop: 4 },
  content: { padding: 16, paddingBottom: 40 },
  formCard: { backgroundColor: '#FFFFFF', padding: 16, borderRadius: 14, marginBottom: 16 },
  sectionTitle: { color: '#111827', fontSize: 18, fontWeight: '700', marginBottom: 12 },
  label: { color: '#374151', fontSize: 13, fontWeight: '600', marginTop: 10, marginBottom: 6 },
  input: { borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 9, paddingHorizontal: 12, paddingVertical: 11, color: '#111827', backgroundColor: '#FFFFFF' },
  readOnlyField: { borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 9, paddingHorizontal: 12, paddingVertical: 12, backgroundColor: '#F3F4F6' },
  readOnlyValue: { color: '#374151', fontSize: 15, fontWeight: '700', letterSpacing: 0.4 },
  readOnlyPlaceholder: { color: '#9CA3AF', fontSize: 14 },
  gradeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  gradeChip: { minWidth: 68, borderWidth: 1, borderColor: '#99F6E4', backgroundColor: '#F0FDFA', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 10, alignItems: 'center' },
  gradeChipSelected: { backgroundColor: '#0F766E', borderColor: '#0F766E' },
  gradeChipText: { color: '#0F766E', fontSize: 16, fontWeight: '800' },
  gradeChipLabel: { color: '#115E59', fontSize: 10, marginTop: 2 },
  gradeChipTextSelected: { color: '#FFFFFF' },
  unitRow: { flexDirection: 'row', gap: 10 },
  unitField: { flex: 1 },
  pickerFrame: { borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 9, overflow: 'hidden', backgroundColor: '#FFFFFF' },
  helperText: { color: '#6B7280', fontSize: 12, lineHeight: 17, marginTop: 6 },
  validationText: { color: '#B91C1C', fontSize: 13, marginTop: 10 },
  formActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 16 },
  saveButton: { backgroundColor: '#0F766E', borderRadius: 9, paddingHorizontal: 18, paddingVertical: 12 },
  saveButtonText: { color: '#FFFFFF', fontWeight: '700' },
  cancelButton: { borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 9, paddingHorizontal: 18, paddingVertical: 12 },
  cancelButtonText: { color: '#374151', fontWeight: '600' },
  listTitle: { color: '#111827', fontSize: 18, fontWeight: '700', marginBottom: 8 },
  searchSection: { marginBottom: 10 },
  searchFrame: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 10, minHeight: 44, paddingHorizontal: 11 },
  searchInput: { flex: 1, color: '#111827', fontSize: 14, paddingVertical: 10 },
  searchClearButton: { paddingVertical: 7, paddingLeft: 10 },
  searchClearText: { color: '#0F766E', fontSize: 12, fontWeight: '700' },
  searchMeta: { color: '#6B7280', fontSize: 11, marginTop: 5, marginLeft: 2 },
  emptyCard: { backgroundColor: '#FFFFFF', padding: 24, borderRadius: 14, alignItems: 'center' },
  emptyText: { color: '#6B7280', textAlign: 'center' },
  loader: { marginVertical: 32 },
  itemCard: { backgroundColor: '#FFFFFF', borderRadius: 11, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 8 },
  itemHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  itemIdentity: { flex: 1 },
  itemTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  itemName: { flexShrink: 1, color: '#111827', fontSize: 15, fontWeight: '700' },
  itemCode: { color: '#6B7280', fontSize: 10, fontWeight: '600', backgroundColor: '#F3F4F6', borderRadius: 5, paddingHorizontal: 5, paddingVertical: 2 },
  cardActions: { flexDirection: 'row', gap: 10 },
  editText: { color: '#0369A1', fontSize: 12, fontWeight: '700' },
  archiveText: { color: '#B91C1C', fontSize: 12, fontWeight: '700' },
  variantRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 7 },
  variantBadge: { backgroundColor: '#CCFBF1', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
  variantBadgeText: { color: '#115E59', fontSize: 11, fontWeight: '800' },
  unitSummary: { color: '#6B7280', fontSize: 11, marginTop: 3 },
});
