import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F8FB',
  },
  header: {
    backgroundColor: '#B45309',
    paddingHorizontal: 18,
    paddingBottom: 16,
    paddingTop: 54,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerIdentity: { alignItems: 'center', flexDirection: 'row', flex: 1, gap: 10 },
  backButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.16)', borderRadius: 18, height: 36, justifyContent: 'center', width: 36 },
  backText: { color: '#FFF', fontSize: 20, fontWeight: '900' },
  title: {
    fontSize: 22,
    fontWeight: '900',
    color: '#fff',
  },
  subtitle: { color: '#FFEDD5', fontSize: 10, marginTop: 2 },
  headerButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  shareButton: {
    backgroundColor: '#FFF7ED',
    borderRadius: 9,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  shareText: { color: '#9A3412', fontSize: 11, fontWeight: '900' },
  resetButton: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  resetText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  logoutButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  logoutText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  daySelector: { alignItems: 'center', backgroundColor: '#FFF', borderBottomColor: '#E5E7EB', borderBottomWidth: 1, flexDirection: 'row', gap: 7, paddingHorizontal: 14, paddingVertical: 12 },
  dayOption: { backgroundColor: '#F1F5F9', borderRadius: 10, paddingHorizontal: 13, paddingVertical: 9 },
  dayOptionActive: { backgroundColor: '#B45309' },
  dayOptionText: { color: '#64748B', fontSize: 11, fontWeight: '800' },
  dayOptionTextActive: { color: '#FFF' },
  selectedDate: { color: '#334155', flex: 1, fontSize: 11, fontWeight: '800', textAlign: 'right' },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  dateButton: {
    padding: 12,
    marginHorizontal: 8,
  },
  dateButtonText: {
    fontSize: 24,
    color: '#3B82F6',
    fontWeight: 'bold',
  },
  dateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
    minWidth: 150,
    textAlign: 'center',
  },
  todayButton: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    marginLeft: 8,
  },
  todayButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 14,
    paddingBottom: 50,
  },
  loader: {
    marginTop: 40,
  },
  emptyContainer: {
    padding: 40,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
  },
  progressCard: { alignItems: 'center', backgroundColor: '#0F172A', borderRadius: 16, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 14, padding: 15 },
  progressLabel: { color: '#94A3B8', fontSize: 8, fontWeight: '900', letterSpacing: 0.8 },
  progressValue: { color: '#FFF', fontSize: 15, fontWeight: '900', marginTop: 5 },
  progressCount: { alignItems: 'center', borderLeftColor: 'rgba(255,255,255,0.14)', borderLeftWidth: 1, minWidth: 66, paddingLeft: 14 },
  progressCountValue: { color: '#FDBA74', fontSize: 21, fontWeight: '900' },
  progressCountLabel: { color: '#94A3B8', fontSize: 7, fontWeight: '900', marginTop: 2 },
  sectionHeader: {
    paddingHorizontal: 2,
    paddingVertical: 10,
    marginTop: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0F172A',
    flex: 1,
  },
  sectionMeta: { color: '#94A3B8', fontSize: 10, fontWeight: '700' },
  sectionExpandIcon: {
    fontSize: 16,
    color: '#374151',
    marginLeft: 8,
  },
  customerCard: {
    backgroundColor: '#fff',
    borderColor: '#E2E8F0',
    borderRadius: 13,
    borderWidth: 1,
    borderLeftColor: '#F59E0B',
    borderLeftWidth: 4,
    marginBottom: 9,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
    overflow: 'hidden',
  },
  customerHeader: {
    backgroundColor: '#FFF',
    paddingHorizontal: 12,
    paddingVertical: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  customerName: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0F172A',
    flex: 1,
  },
  customerTotal: {
    fontSize: 12,
    fontWeight: '900',
    color: '#B45309',
    marginRight: 8,
  },
  expandIcon: {
    fontSize: 11,
    color: '#64748B',
    minWidth: 20,
    textAlign: 'center',
  },
  itemCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  fishName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#111827',
    flex: 1,
  },
  boxCount: {
    fontSize: 12,
    fontWeight: '900',
    color: '#B45309',
    marginRight: 10,
    minWidth: 88,
    textAlign: 'right',
  },
  checkbox: {
    width: 36,
    height: 36,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  checkboxChecked: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
  },
  checkmark: {
    fontSize: 20,
    color: '#fff',
    fontWeight: 'bold',
  },
  completedCard: {
    borderLeftColor: '#94A3B8',
  },
  completedHeader: {
    backgroundColor: '#F8FAFC',
  },
  completedItem: {
    backgroundColor: '#F9FAFB',
  },
  completedText: {
    color: '#9CA3AF',
    textDecorationLine: 'line-through',
  },
  modalBackdrop: {
    backgroundColor: 'rgba(15, 23, 42, 0.58)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  shareSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '88%',
    paddingBottom: 26,
    paddingHorizontal: 18,
    paddingTop: 9,
  },
  shareSheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#CBD5E1',
    borderRadius: 2,
    height: 4,
    marginBottom: 16,
    width: 42,
  },
  shareSheetHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 12 },
  shareSheetTitleBlock: { flex: 1 },
  shareSheetEyebrow: { color: '#B45309', fontSize: 9, fontWeight: '900', letterSpacing: 1.1 },
  shareSheetTitle: { color: '#0F172A', fontSize: 22, fontWeight: '900', marginTop: 4 },
  shareSheetSubtitle: { color: '#64748B', fontSize: 12, lineHeight: 17, marginTop: 4 },
  modalCloseButton: { alignItems: 'center', backgroundColor: '#F1F5F9', borderRadius: 16, height: 32, justifyContent: 'center', width: 32 },
  modalCloseText: { color: '#475569', fontSize: 23, lineHeight: 25 },
  selectAllRow: { alignItems: 'center', borderBottomColor: '#E2E8F0', borderBottomWidth: 1, flexDirection: 'row', marginTop: 18, paddingBottom: 12 },
  selectBox: { alignItems: 'center', borderColor: '#CBD5E1', borderRadius: 7, borderWidth: 2, height: 24, justifyContent: 'center', width: 24 },
  selectBoxChecked: { backgroundColor: '#B45309', borderColor: '#B45309' },
  selectCheck: { color: '#FFFFFF', fontSize: 15, fontWeight: '900' },
  selectAllLabel: { color: '#334155', flex: 1, fontSize: 13, fontWeight: '800', marginLeft: 10 },
  selectionCount: { color: '#B45309', fontSize: 12, fontWeight: '900' },
  shareCustomerList: { maxHeight: 285 },
  shareCustomerListContent: { gap: 7, paddingVertical: 12 },
  shareCustomerRow: { alignItems: 'center', borderColor: '#E2E8F0', borderRadius: 12, borderWidth: 1, flexDirection: 'row', padding: 11 },
  shareCustomerRowSelected: { backgroundColor: '#FFF7ED', borderColor: '#FED7AA' },
  shareCustomerName: { color: '#0F172A', flex: 1, fontSize: 13, fontWeight: '800', marginLeft: 10 },
  shareCustomerQuantity: { color: '#92400E', fontSize: 11, fontWeight: '900' },
  sharePermissionRow: { alignItems: 'center', backgroundColor: '#F8FAFC', borderRadius: 13, flexDirection: 'row', gap: 12, padding: 12 },
  sharePermissionCopy: { flex: 1 },
  sharePermissionTitle: { color: '#0F172A', fontSize: 13, fontWeight: '900' },
  sharePermissionSubtitle: { color: '#64748B', fontSize: 10, lineHeight: 14, marginTop: 2 },
  shareExpiryNote: { color: '#64748B', fontSize: 10, lineHeight: 15, marginTop: 10 },
  shareActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  revokeLinkButton: { alignItems: 'center', borderColor: '#FCA5A5', borderRadius: 12, borderWidth: 1, justifyContent: 'center', paddingHorizontal: 14, paddingVertical: 13 },
  revokeLinkText: { color: '#B91C1C', fontSize: 12, fontWeight: '900' },
  createLinkButton: { alignItems: 'center', backgroundColor: '#B45309', borderRadius: 12, flex: 1, justifyContent: 'center', minHeight: 46, paddingHorizontal: 14 },
  createLinkButtonDisabled: { opacity: 0.45 },
  createLinkText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
});
