import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { backgroundColor: '#F5F7FB', flex: 1 },
  header: { alignItems: 'center', backgroundColor: '#312E81', flexDirection: 'row', minHeight: 108, paddingBottom: 16, paddingHorizontal: 18, paddingTop: 48 },
  backButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.14)', borderRadius: 12, height: 42, justifyContent: 'center', marginRight: 12, width: 42 },
  backIcon: { color: '#FFF', fontSize: 34, fontWeight: '300', lineHeight: 36 },
  eyebrow: { color: '#C7D2FE', fontSize: 9, fontWeight: '900', letterSpacing: 1.1 },
  title: { color: '#FFF', fontSize: 23, fontWeight: '900', marginTop: 2 },
  content: { flex: 1 },
  contentContainer: { padding: 14, paddingBottom: 48 },
  summaryCard: { backgroundColor: '#FFF', borderColor: '#E2E8F0', borderRadius: 16, borderWidth: 1, flexDirection: 'row', paddingVertical: 15 },
  summaryColumn: { flex: 1, paddingHorizontal: 10 },
  summaryDivider: { borderLeftColor: '#E2E8F0', borderLeftWidth: 1 },
  summaryLabel: { color: '#94A3B8', fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  receivedValue: { color: '#047857', fontSize: 16, fontWeight: '900', marginTop: 5 },
  paidValue: { color: '#B91C1C', fontSize: 16, fontWeight: '900', marginTop: 5 },
  netValue: { color: '#312E81', fontSize: 16, fontWeight: '900', marginTop: 5 },
  negativeNet: { color: '#B91C1C' },
  searchInput: { backgroundColor: '#FFF', borderColor: '#CBD5E1', borderRadius: 12, borderWidth: 1, color: '#0F172A', fontSize: 14, marginTop: 12, minHeight: 48, paddingHorizontal: 14 },
  filterLabel: { color: '#64748B', fontSize: 9, fontWeight: '900', letterSpacing: 0.9, marginBottom: 7, marginTop: 13 },
  chipRow: { flexDirection: 'row', gap: 8 },
  chip: { alignItems: 'center', backgroundColor: '#FFF', borderColor: '#CBD5E1', borderRadius: 10, borderWidth: 1, flex: 1, paddingVertical: 9 },
  chipActive: { backgroundColor: '#4338CA', borderColor: '#4338CA' },
  chipText: { color: '#475569', fontSize: 12, fontWeight: '800' },
  chipTextActive: { color: '#FFF' },
  methodRow: { gap: 7, paddingRight: 14 },
  methodChip: { backgroundColor: '#FFF', borderColor: '#CBD5E1', borderRadius: 9, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8 },
  methodChipActive: { backgroundColor: '#EEF2FF', borderColor: '#6366F1' },
  methodText: { color: '#64748B', fontSize: 11, fontWeight: '800' },
  methodTextActive: { color: '#3730A3' },
  listHeading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, marginTop: 22 },
  listTitle: { color: '#0F172A', fontSize: 18, fontWeight: '900' },
  listSubtitle: { color: '#64748B', fontSize: 10, marginTop: 2 },
  auditChip: { backgroundColor: '#FFF', borderColor: '#CBD5E1', borderRadius: 9, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 7 },
  auditChipActive: { backgroundColor: '#FEF2F2', borderColor: '#FCA5A5' },
  auditText: { color: '#64748B', fontSize: 10, fontWeight: '800' },
  auditTextActive: { color: '#B91C1C' },
  loading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'center', paddingVertical: 38 },
  loadingText: { color: '#64748B', marginLeft: 9 },
  emptyCard: { alignItems: 'center', backgroundColor: '#FFF', borderColor: '#E2E8F0', borderRadius: 15, borderWidth: 1, padding: 30 },
  emptyIcon: { color: '#A5B4FC', fontSize: 26, fontWeight: '900' },
  emptyTitle: { color: '#334155', fontSize: 15, fontWeight: '900', marginTop: 8 },
  emptyText: { color: '#94A3B8', fontSize: 11, marginTop: 4, textAlign: 'center' },
  paymentCard: { backgroundColor: '#FFF', borderColor: '#E2E8F0', borderLeftWidth: 4, borderRadius: 14, borderWidth: 1, marginBottom: 9, padding: 13 },
  receivedCard: { borderLeftColor: '#10B981' },
  paidCard: { borderLeftColor: '#F87171' },
  voidedCard: { backgroundColor: '#F8FAFC', borderLeftColor: '#94A3B8', opacity: 0.78 },
  paymentTopRow: { alignItems: 'center', flexDirection: 'row' },
  directionBadge: { alignItems: 'center', borderRadius: 10, height: 38, justifyContent: 'center', width: 38 },
  receivedBadge: { backgroundColor: '#D1FAE5' },
  paidBadge: { backgroundColor: '#FEE2E2' },
  directionSymbol: { fontSize: 20, fontWeight: '900' },
  receivedSymbol: { color: '#047857' },
  paidSymbol: { color: '#B91C1C' },
  paymentIdentity: { flex: 1, marginLeft: 10 },
  partyName: { color: '#0F172A', fontSize: 15, fontWeight: '900' },
  directionText: { color: '#64748B', fontSize: 10, marginTop: 2 },
  amountColumn: { alignItems: 'flex-end', marginLeft: 8 },
  amount: { fontSize: 17, fontWeight: '900' },
  receivedAmount: { color: '#047857' },
  paidAmount: { color: '#B91C1C' },
  struckText: { color: '#64748B', textDecorationLine: 'line-through' },
  voidedLabel: { color: '#B91C1C', fontSize: 8, fontWeight: '900', letterSpacing: 0.6, marginTop: 2 },
  metaRow: { alignItems: 'center', borderTopColor: '#F1F5F9', borderTopWidth: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 11, paddingTop: 9 },
  methodBadge: { backgroundColor: '#EEF2FF', borderRadius: 7, paddingHorizontal: 8, paddingVertical: 4 },
  methodBadgeText: { color: '#4338CA', fontSize: 9, fontWeight: '900' },
  metaText: { color: '#64748B', fontSize: 10, maxWidth: '48%' },
  notes: { color: '#64748B', fontSize: 10, fontStyle: 'italic', marginTop: 8 },
  voidReason: { color: '#B91C1C', fontSize: 10, marginTop: 7 },
});
