import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { backgroundColor: '#F5F3FF', flex: 1 },
  header: { alignItems: 'center', backgroundColor: '#5B21B6', flexDirection: 'row', minHeight: 108, paddingBottom: 16, paddingHorizontal: 18, paddingTop: 48 },
  backButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.14)', borderRadius: 12, height: 42, justifyContent: 'center', marginRight: 12, width: 42 },
  backIcon: { color: '#FFFFFF', fontSize: 34, fontWeight: '300', lineHeight: 36 },
  eyebrow: { color: '#DDD6FE', fontSize: 9, fontWeight: '900', letterSpacing: 1.1 },
  title: { color: '#FFFFFF', fontSize: 23, fontWeight: '900', marginTop: 2 },
  content: { flex: 1 },
  contentContainer: { padding: 14, paddingBottom: 48 },
  rangeRow: { backgroundColor: '#EDE9FE', borderRadius: 12, flexDirection: 'row', gap: 5, marginBottom: 12, padding: 4 },
  rangeChip: { alignItems: 'center', borderRadius: 9, flex: 1, paddingVertical: 9 },
  rangeChipOn: { backgroundColor: '#FFFFFF' },
  rangeText: { color: '#7C3AED', fontSize: 11, fontWeight: '800' },
  rangeTextOn: { color: '#4C1D95' },
  periodText: { color: '#64748B', fontSize: 10, marginBottom: 9, textAlign: 'center' },
  summaryCard: { backgroundColor: '#2E1065', borderRadius: 18, padding: 17 },
  summaryTop: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between' },
  summaryEyebrow: { color: '#C4B5FD', fontSize: 9, fontWeight: '900', letterSpacing: 0.9 },
  summaryAmount: { color: '#FFFFFF', fontSize: 30, fontWeight: '900', marginTop: 4 },
  loader: { alignSelf: 'flex-start', marginTop: 10 },
  statusBadge: { borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6 },
  completeBadge: { backgroundColor: '#047857' },
  provisionalBadge: { backgroundColor: '#B45309' },
  statusText: { color: '#FFFFFF', fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  metricRow: { borderTopColor: 'rgba(255,255,255,0.15)', borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, paddingTop: 12 },
  metricLabel: { color: '#A78BFA', fontSize: 8, fontWeight: '900', letterSpacing: 0.5 },
  metricValue: { color: '#FFFFFF', fontSize: 12, fontWeight: '800', marginTop: 3 },
  warningCard: { backgroundColor: '#FFFBEB', borderColor: '#FCD34D', borderRadius: 14, borderWidth: 1, marginTop: 12, padding: 13 },
  warningTitle: { color: '#92400E', fontSize: 13, fontWeight: '900' },
  warningText: { color: '#B45309', fontSize: 11, lineHeight: 16, marginTop: 3 },
  coverageTrack: { backgroundColor: '#FDE68A', borderRadius: 4, height: 6, marginTop: 9, overflow: 'hidden' },
  coverageFill: { backgroundColor: '#D97706', borderRadius: 4, height: 6 },
  card: { backgroundColor: '#FFFFFF', borderColor: '#DDD6FE', borderRadius: 16, borderWidth: 1, marginTop: 14, padding: 15 },
  cardTitle: { color: '#1E1B4B', fontSize: 16, fontWeight: '900', marginBottom: 6 },
  bridgeRow: { alignItems: 'center', borderBottomColor: '#F5F3FF', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 40 },
  bridgeLabel: { color: '#64748B', fontSize: 12, fontWeight: '700' },
  inValue: { color: '#047857', fontSize: 12, fontWeight: '900' },
  outValue: { color: '#B91C1C', fontSize: 12, fontWeight: '900' },
  bridgeStrong: { borderBottomWidth: 0, borderTopColor: '#DDD6FE', borderTopWidth: 1, marginTop: 3 },
  bridgeStrongLabel: { color: '#4C1D95', fontSize: 13, fontWeight: '900' },
  bridgeStrongValue: { color: '#5B21B6', fontSize: 15, fontWeight: '900' },
  sectionHeading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8, marginTop: 20 },
  sectionTitle: { color: '#1E1B4B', fontSize: 17, fontWeight: '900' },
  sectionMeta: { color: '#7C3AED', fontSize: 10, fontWeight: '800' },
  itemRow: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#DDD6FE', borderRadius: 14, borderWidth: 1, flexDirection: 'row', marginBottom: 8, padding: 13 },
  itemCopy: { flex: 1, paddingRight: 8 },
  itemName: { color: '#1E1B4B', fontSize: 13, fontWeight: '900' },
  itemMeta: { color: '#64748B', fontSize: 9, marginTop: 3 },
  itemValues: { alignItems: 'flex-end' },
  itemProfit: { color: '#5B21B6', fontSize: 14, fontWeight: '900' },
  itemRevenue: { color: '#94A3B8', fontSize: 8, marginTop: 3 },
  dayRow: { alignItems: 'center', backgroundColor: '#FFFFFF', borderBottomColor: '#EDE9FE', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 13, paddingVertical: 11 },
  dayDate: { color: '#475569', fontSize: 11, fontWeight: '800' },
  dayValues: { alignItems: 'flex-end' },
  dayProfit: { color: '#5B21B6', fontSize: 12, fontWeight: '900' },
  dayWarning: { color: '#B45309', fontSize: 8, marginTop: 2 },
  empty: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#DDD6FE', borderRadius: 14, borderWidth: 1, padding: 24 },
  emptyTitle: { color: '#475569', fontSize: 14, fontWeight: '800' },
  emptyText: { color: '#94A3B8', fontSize: 11, marginTop: 4 },
  methodCard: { backgroundColor: '#EDE9FE', borderRadius: 14, marginTop: 18, padding: 13 },
  methodTitle: { color: '#4C1D95', fontSize: 11, fontWeight: '900' },
  methodText: { color: '#6D28D9', fontSize: 10, lineHeight: 15, marginTop: 3 },
});
