import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#FFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingTop: 50,
  },
  backButton: {
    fontSize: 16,
    color: '#0EA5E9',
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
  },
  content: {
    flex: 1,
  },
  farmerInfoCard: {
    backgroundColor: '#FFF',
    padding: 16,
    marginTop: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  farmerName: {
    fontSize: 20,
    fontWeight: '600',
    color: '#111827',
  },
  farmerSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 4,
  },
  billDate: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 8,
  },
  section: {
    backgroundColor: '#FFF',
    padding: 16,
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 12,
  },
  itemCard: {
    backgroundColor: '#F9FAFB',
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  itemHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
    gap: 12,
  },
  itemHeaderLeft: {
    flex: 1,
  },
  varietyName: {
    fontSize: 17,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  weightInfoText: {
    fontSize: 13,
    color: '#6B7280',
  },
  totalWeightBold: {
    fontWeight: '600',
    color: '#374151',
  },
  rateInputCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: '#0EA5E9',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minWidth: 100,
  },
  rupeeSymbol: {
    fontSize: 16,
    color: '#6B7280',
    marginRight: 4,
    fontWeight: '500',
  },
  rateInputSmall: {
    fontSize: 18,
    color: '#111827',
    fontWeight: '600',
    flex: 1,
    textAlign: 'right',
    padding: 0,
  },
  deductionToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    borderRadius: 3,
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#E5E7EB',
    borderColor: '#9CA3AF',
  },
  checkmark: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: 'bold',
  },
  deductionText: {
    fontSize: 13,
    color: '#6B7280',
  },
  amountDisplay: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
    marginHorizontal: -12,
    marginBottom: -12,
    paddingHorizontal: 12,
    paddingBottom: 12,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  amountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  amountLabel: {
    fontSize: 14,
    color: '#6B7280',
    flex: 1,
  },
  amountValue: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '500',
  },
  amountLabelBold: {
    fontSize: 15,
    color: '#111827',
    fontWeight: '600',
  },
  amountValueBold: {
    fontSize: 20,
    color: '#059669',
    fontWeight: '700',
  },
  commissionCard: {
    borderWidth: 1,
    borderColor: '#A7F3D0',
    backgroundColor: '#ECFDF5',
    borderRadius: 10,
    padding: 12,
    marginBottom: 14,
  },
  commissionToggle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  commissionIdentity: {
    flex: 1,
  },
  commissionTitle: {
    color: '#065F46',
    fontSize: 14,
    fontWeight: '700',
  },
  commissionSubtitle: {
    color: '#047857',
    fontSize: 11,
    marginTop: 2,
  },
  commissionRateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#A7F3D0',
  },
  commissionFormula: {
    color: '#065F46',
    fontSize: 12,
    fontWeight: '600',
  },
  commissionRateInput: {
    minWidth: 58,
    borderWidth: 1,
    borderColor: '#6EE7B7',
    backgroundColor: '#FFFFFF',
    borderRadius: 7,
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    paddingHorizontal: 7,
    paddingVertical: 6,
    marginRight: 4,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  inputLabel: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
  },
  input: {
    width: 120,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 6,
    padding: 10,
    fontSize: 14,
    backgroundColor: '#FFF',
    textAlign: 'right',
  },
  summaryCard: {
    backgroundColor: '#FFF',
    padding: 16,
    marginTop: 8,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#6B7280',
    flex: 1,
  },
  summaryValue: {
    fontSize: 15,
    color: '#111827',
    fontWeight: '600',
  },
  totalRow: {
    marginTop: 12,
    paddingTop: 16,
    borderTopWidth: 2,
    borderTopColor: '#D1D5DB',
  },
  totalLabel: {
    fontSize: 17,
    fontWeight: '700',
    color: '#111827',
  },
  totalValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#059669',
  },
  balanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    padding: 12,
    backgroundColor: '#FEF3C7',
    borderRadius: 6,
  },
  balanceLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#92400E',
  },
  balanceValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#92400E',
  },
  balancePositive: {
    color: '#B91C1C',
  },
  generateButton: {
    backgroundColor: '#0EA5E9',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    margin: 16,
  },
  generateButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
  },
  bottomPadding: {
    height: 20,
  },
  notesInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 6,
    padding: 12,
    fontSize: 14,
    backgroundColor: '#FFF',
    textAlignVertical: 'top',
    minHeight: 80,
  },
  finalTotalCard: {
    backgroundColor: '#FFF',
    padding: 20,
    marginTop: 8,
    borderWidth: 2,
    borderColor: '#059669',
    borderRadius: 8,
  },
  finalTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  finalTotalLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  finalTotalValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#059669',
  },
  paymentNote: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 8,
    fontStyle: 'italic',
  },
  helpText: {
    fontSize: 13,
    color: '#9CA3AF',
    marginBottom: 12,
  },
  paymentItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  paymentItemLeft: {
    flex: 1,
  },
  paymentItemAmount: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 2,
  },
  paymentItemDetails: {
    fontSize: 12,
    color: '#6B7280',
  },
  removePaymentBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removePaymentText: {
    fontSize: 16,
    color: '#DC2626',
    fontWeight: 'bold',
  },
  addPaymentContainer: {
    marginTop: 16,
    backgroundColor: '#F9FAFB',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  addPaymentTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 12,
  },
  paymentFormRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  paymentFormField: {
    flex: 1,
  },
  paymentFormLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 4,
    fontWeight: '500',
  },
  paymentFormInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 6,
    padding: 10,
    fontSize: 14,
    backgroundColor: '#FFF',
  },
  paymentMethodPicker: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 6,
    backgroundColor: '#FFF',
    overflow: 'hidden',
  },
  miniPicker: {
    height: 44,
  },
  addPaymentBtnNew: {
    backgroundColor: '#0EA5E9',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  addPaymentBtnText: {
    fontSize: 14,
    color: '#FFF',
    fontWeight: '600',
  },
  paymentsSummary: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  paymentsSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  paymentsSummaryLabel: {
    fontSize: 14,
    color: '#6B7280',
  },
  paymentsSummaryValue: {
    fontSize: 14,
    color: '#059669',
    fontWeight: '600',
  },
  correctionCard: {
    backgroundColor: '#FFF7ED',
    borderColor: '#FED7AA',
    borderRadius: 12,
    borderWidth: 1,
    margin: 16,
    marginBottom: 0,
    padding: 12,
  },
  correctionTitle: {
    color: '#9A3412',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  correctionText: {
    color: '#C2410C',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  paymentMethodRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
    marginTop: 8,
  },
  paymentMethodChip: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#CBD5E1',
    borderRadius: 9,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 10,
  },
  paymentMethodChipActive: {
    backgroundColor: '#0F766E',
    borderColor: '#0F766E',
  },
  paymentMethodText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '800',
  },
  paymentMethodTextActive: {
    color: '#FFFFFF',
  },
  paymentReferenceInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 9,
    borderWidth: 1,
    color: '#0F172A',
    marginBottom: 10,
    padding: 10,
  },
  correctionFieldLabel: {
    color: '#64748B',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.7,
    marginBottom: 5,
  },
  correctionSelect: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#CBD5E1',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    minHeight: 46,
    paddingHorizontal: 11,
  },
  correctionSelectValue: {
    color: '#0F172A',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
  },
  correctionSelectAction: {
    color: '#0F766E',
    fontSize: 11,
    fontWeight: '800',
    marginLeft: 8,
  },
  correctionQuantityRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 13,
  },
  correctionQuantityField: {
    flex: 1,
  },
  correctionQuantityInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 9,
    borderWidth: 1,
    color: '#0F172A',
    fontSize: 14,
    minHeight: 44,
    paddingHorizontal: 10,
  },
});
