import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F3F4F6' },
  header: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#0F766E', paddingTop: 54, paddingHorizontal: 18, paddingBottom: 16 },
  backButton: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.15)' },
  backButtonText: { color: '#FFFFFF', fontSize: 22, fontWeight: '700' },
  title: { color: '#FFFFFF', fontSize: 22, fontWeight: '800' },
  subtitle: { color: '#CCFBF1', fontSize: 12, marginTop: 2 },
  content: { padding: 14, paddingBottom: 40 },
  formCard: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 14, marginTop: 12, marginBottom: 18 },
  sectionTitle: { color: '#111827', fontSize: 18, fontWeight: '800', marginBottom: 5 },
  subsectionTitle: { color: '#111827', fontSize: 15, fontWeight: '700', marginBottom: 8 },
  label: { color: '#374151', fontSize: 12, fontWeight: '700', marginTop: 10, marginBottom: 5 },
  input: { borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 9, backgroundColor: '#FFFFFF', color: '#111827', fontSize: 14, paddingHorizontal: 11, paddingVertical: 10 },
  pickerFrame: { borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 9, overflow: 'hidden', backgroundColor: '#FFFFFF', marginBottom: 2 },
  selectField: { minHeight: 46, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 9, backgroundColor: '#FFFFFF', paddingHorizontal: 12 },
  selectIdentity: { flex: 1, paddingVertical: 8 },
  selectValue: { flex: 1, color: '#111827', fontSize: 14, fontWeight: '600' },
  selectPlaceholder: { flex: 1, color: '#9CA3AF', fontSize: 14 },
  selectDetail: { color: '#6B7280', fontSize: 10, marginTop: 2 },
  selectChevron: { color: '#6B7280', fontSize: 25, marginLeft: 8 },
  quickAddRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8 },
  flexInput: { flex: 1 },
  secondaryButton: { minHeight: 42, justifyContent: 'center', borderWidth: 1, borderColor: '#0F766E', borderRadius: 9, paddingHorizontal: 15 },
  secondaryButtonText: { color: '#0F766E', fontSize: 13, fontWeight: '800' },
  divider: { height: 1, backgroundColor: '#E5E7EB', marginVertical: 16 },
  frequentSection: { marginBottom: 10 },
  frequentTitle: { color: '#6B7280', fontSize: 11, fontWeight: '700', marginBottom: 7 },
  frequentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  frequentChip: { maxWidth: '48%', borderWidth: 1, borderColor: '#99F6E4', backgroundColor: '#F0FDFA', borderRadius: 9, paddingHorizontal: 10, paddingVertical: 8 },
  frequentChipSelected: { borderColor: '#0F766E', backgroundColor: '#0F766E' },
  frequentChipText: { color: '#115E59', fontSize: 12, fontWeight: '700' },
  frequentChipTextSelected: { color: '#FFFFFF' },
  quantityRow: { flexDirection: 'row', gap: 10 },
  fieldColumn: { flex: 1 },
  quantityHint: { color: '#6B7280', fontSize: 10, lineHeight: 14, marginTop: 5 },
  addItemButton: { alignItems: 'center', backgroundColor: '#ECFDF5', borderWidth: 1, borderColor: '#6EE7B7', borderRadius: 9, paddingVertical: 11, marginTop: 12 },
  addItemButtonText: { color: '#047857', fontSize: 14, fontWeight: '800' },
  draftList: { marginTop: 12, borderTopWidth: 1, borderTopColor: '#E5E7EB' },
  draftRow: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  draftIdentity: { flex: 1 },
  draftName: { color: '#111827', fontSize: 13, fontWeight: '700' },
  draftQuantity: { color: '#6B7280', fontSize: 11, marginTop: 2 },
  editText: { color: '#0369A1', fontSize: 12, fontWeight: '700' },
  deleteText: { color: '#B91C1C', fontSize: 12, fontWeight: '700' },
  saveButton: { minHeight: 46, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0F766E', borderRadius: 10, marginTop: 14 },
  saveButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  disabledButton: { opacity: 0.45 },
  listTitle: { color: '#111827', fontSize: 17, fontWeight: '800', marginBottom: 9 },
  loader: { marginVertical: 30 },
  emptyCard: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 22, alignItems: 'center' },
  emptyText: { color: '#6B7280', fontSize: 13, textAlign: 'center' },
  groupCard: { backgroundColor: '#FFFFFF', borderRadius: 12, marginBottom: 9, overflow: 'hidden' },
  groupHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 11, paddingTop: 10, paddingBottom: 7 },
  collapseIcon: { color: '#6B7280', fontSize: 11, marginRight: 7 },
  groupIdentity: { flex: 1 },
  mediatorName: { color: '#111827', fontSize: 14, fontWeight: '800' },
  groupSubtitle: { color: '#6B7280', fontSize: 11, marginTop: 2 },
  totalBadge: { alignItems: 'flex-end', backgroundColor: '#F0FDFA', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  totalBadgeText: { color: '#115E59', fontSize: 12, fontWeight: '800' },
  totalBadgeSubtext: { color: '#0F766E', fontSize: 10, marginTop: 1 },
  groupMetaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 11, paddingBottom: 9 },
  groupActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  editGroupButton: { borderWidth: 1, borderColor: '#0F766E', borderRadius: 7, paddingHorizontal: 10, paddingVertical: 5 },
  editGroupButtonText: { color: '#0F766E', fontSize: 11, fontWeight: '800' },
  statusText: { color: '#B45309', fontSize: 11, fontWeight: '700' },
  billedText: { color: '#047857' },
  billButton: { backgroundColor: '#0F766E', borderRadius: 7, paddingHorizontal: 10, paddingVertical: 6 },
  billButtonText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  purchaseRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 9, borderTopWidth: 1, borderTopColor: '#F3F4F6' },
  purchaseName: { flex: 1, color: '#1F2937', fontSize: 13, fontWeight: '700', paddingRight: 12 },
  purchaseQuantity: { color: '#374151', fontSize: 12, fontWeight: '700', textAlign: 'right' },
  rowActions: { flexDirection: 'row', gap: 11 },
  modalOverlay: { flex: 1, justifyContent: 'center', padding: 20, backgroundColor: 'rgba(17,24,39,0.55)' },
  modalCard: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 16 },
  groupEditModal: { maxHeight: '88%' },
  editLineCard: { borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 10, padding: 10, marginTop: 12, backgroundColor: '#F9FAFB' },
  editLineHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  editLineTitle: { color: '#374151', fontSize: 12, fontWeight: '700' },
  modalTitle: { color: '#111827', fontSize: 17, fontWeight: '800', marginBottom: 5 },
  modalSubtitle: { color: '#6B7280', fontSize: 11 },
  mediatorModalCard: { maxHeight: '88%' },
  optionalSectionTitle: { color: '#0F766E', fontSize: 13, fontWeight: '800', marginTop: 18, marginBottom: 1 },
  textArea: { minHeight: 76, textAlignVertical: 'top' },
  typeSelector: { flexDirection: 'row', gap: 8 },
  typeOption: { flex: 1, alignItems: 'center', borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 9, paddingVertical: 10, backgroundColor: '#FFFFFF' },
  typeOptionSelected: { backgroundColor: '#0F766E', borderColor: '#0F766E' },
  typeOptionText: { color: '#374151', fontSize: 13, fontWeight: '700' },
  typeOptionTextSelected: { color: '#FFFFFF' },
  directInfoCard: { backgroundColor: '#ECFDF5', borderWidth: 1, borderColor: '#A7F3D0', borderRadius: 9, paddingHorizontal: 11, paddingVertical: 9, marginTop: 10 },
  directInfoTitle: { color: '#047857', fontSize: 12, fontWeight: '800' },
  directInfoText: { color: '#065F46', fontSize: 11, lineHeight: 16, marginTop: 2 },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 9, marginTop: 15 },
  modalCancelButton: { borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 9, paddingHorizontal: 15, paddingVertical: 11 },
  modalCancelText: { color: '#374151', fontWeight: '700' },
  modalSaveButton: { backgroundColor: '#0F766E', borderRadius: 9, paddingHorizontal: 16, paddingVertical: 11 },
  modalSaveText: { color: '#FFFFFF', fontWeight: '800' },
  sheetOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(17,24,39,0.45)' },
  sheetCard: { height: '78%', backgroundColor: '#F9FAFB', borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 16, paddingTop: 16, paddingBottom: 28 },
  sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  sheetTitle: { color: '#111827', fontSize: 18, fontWeight: '800' },
  sheetClose: { color: '#0F766E', fontSize: 13, fontWeight: '800' },
  searchInput: { borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 10, backgroundColor: '#FFFFFF', color: '#111827', paddingHorizontal: 12, paddingVertical: 11 },
  sheetCreateButton: { alignItems: 'center', borderWidth: 1, borderColor: '#5EEAD4', backgroundColor: '#F0FDFA', borderRadius: 9, paddingVertical: 10, marginTop: 10 },
  sheetCreateText: { color: '#0F766E', fontSize: 13, fontWeight: '800' },
  resultMeta: { color: '#6B7280', fontSize: 11, marginVertical: 9 },
  optionRow: { backgroundColor: '#FFFFFF', borderRadius: 9, paddingHorizontal: 12, paddingVertical: 11, marginBottom: 7 },
  optionGroup: { color: '#475569', fontSize: 10, fontWeight: '900', letterSpacing: 0.8, marginBottom: 6, marginTop: 8, textTransform: 'uppercase' },
  optionLabel: { color: '#111827', fontSize: 14, fontWeight: '700' },
  optionDetail: { color: '#6B7280', fontSize: 11, marginTop: 3 },
  sheetEmptyText: { color: '#6B7280', textAlign: 'center', paddingVertical: 28 },
  catalogModalContainer: { flex: 1, backgroundColor: '#F3F4F6' },
  catalogModalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFFFFF', paddingTop: 54, paddingHorizontal: 17, paddingBottom: 14 },
  catalogModalTitle: { color: '#111827', fontSize: 18, fontWeight: '800' },
  catalogModalContent: { padding: 14, paddingBottom: 40 },
});
