import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  listContainer: {
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 32,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  listTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#111827',
  },
  toggleAllButton: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  toggleAllText: {
    color: '#1D4ED8',
    fontSize: 13,
    fontWeight: '600',
  },
  loader: {
    marginTop: 32,
  },
  emptyText: {
    textAlign: 'center',
    color: '#6B7280',
    fontSize: 16,
    marginTop: 32,
  },
  customerGroup: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 10,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  customerHeader: {
    backgroundColor: '#F3F4F6',
    padding: 12,
  },
  customerHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  customerHeaderBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 22,
  },
  customerHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  collapseIcon: {
    fontSize: 12,
    color: '#6B7280',
    width: 16,
  },
  customerName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#111827',
    flexShrink: 1,
  },
  quantityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    gap: 6,
  },
  quantityIcon: {
    fontSize: 16,
  },
  customerCount: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E40AF',
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  billingStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4,
  },
  billingStatusBilled: {
    backgroundColor: '#D1FAE5',
  },
  billingStatusUnbilled: {
    backgroundColor: '#FEE2E2',
  },
  billingStatusPartial: {
    backgroundColor: '#FEF3C7',
  },
  billingStatusIcon: {
    fontSize: 12,
  },
  billingStatusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  generateBillButton: {
    backgroundColor: '#DBEAFE',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  generateBillButtonText: {
    color: '#1E40AF',
    fontSize: 13,
    fontWeight: '600',
  },
  saleItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  saleInfo: {
    flex: 1,
  },
  varietyName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  quantity: {
    fontSize: 14,
    color: '#6B7280',
  },
  deleteButton: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  deleteButtonText: {
    color: '#DC2626',
    fontSize: 14,
    fontWeight: '600',
  },
  customerHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  editButton: {
    backgroundColor: '#DBEAFE',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  editButtonText: {
    color: '#1D4ED8',
    fontSize: 13,
    fontWeight: '600',
  },
  paymentButton: {
    backgroundColor: '#0F766E',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 7,
  },
  paymentButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  existingSaleBackdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,0.5)', justifyContent: 'center', padding: 22 },
  existingSaleModal: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 22, alignItems: 'center' },
  existingSaleIcon: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#DBEAFE', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  existingSaleIconText: { color: '#2563EB', fontSize: 24, fontWeight: '800' },
  existingSaleTitle: { color: '#111827', fontSize: 20, fontWeight: '800', marginBottom: 8 },
  existingSaleBody: { color: '#4B5563', fontSize: 15, lineHeight: 22, textAlign: 'center' },
  existingSaleHint: { color: '#92400E', backgroundColor: '#FFFBEB', fontSize: 13, lineHeight: 19, textAlign: 'center', padding: 10, borderRadius: 8, marginTop: 12 },
  existingSaleActions: { flexDirection: 'row', gap: 10, alignSelf: 'stretch', marginTop: 20 },
  existingSaleCancel: { flex: 1, borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
  existingSaleCancelText: { color: '#374151', fontSize: 15, fontWeight: '700' },
  existingSaleEdit: { flex: 1, backgroundColor: '#2563EB', borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
  existingSaleEditText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  quickPaymentBackdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,0.55)', justifyContent: 'flex-end' },
  quickPaymentModal: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22, paddingBottom: 30 },
  quickPaymentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 18 },
  quickPaymentEyebrow: { color: '#0F766E', fontSize: 11, fontWeight: '800', letterSpacing: 1.2, marginBottom: 4 },
  quickPaymentTitle: { color: '#111827', fontSize: 22, fontWeight: '800' },
  quickPaymentSubtitle: { color: '#6B7280', fontSize: 15, marginTop: 4 },
  quickPaymentClose: { color: '#6B7280', fontSize: 30, lineHeight: 30 },
  quickPaymentLoader: { marginVertical: 42 },
  quickPaymentBalance: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#F0FDFA', borderRadius: 12, padding: 14, marginBottom: 18 },
  quickPaymentBalanceLabel: { color: '#0F766E', fontSize: 11, fontWeight: '800', letterSpacing: 0.8 },
  quickPaymentBalanceValue: { color: '#115E59', fontSize: 20, fontWeight: '800' },
  quickPaymentLabel: { color: '#64748B', fontSize: 11, fontWeight: '800', letterSpacing: 0.8, marginBottom: 7, marginTop: 12 },
  quickPaymentAmountWrap: { flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: '#99F6E4', backgroundColor: '#F8FAFC', borderRadius: 12, paddingHorizontal: 14 },
  quickPaymentCurrency: { color: '#0F766E', fontSize: 22, fontWeight: '800', marginRight: 8 },
  quickPaymentAmount: { flex: 1, color: '#111827', fontSize: 25, fontWeight: '800', paddingVertical: 13 },
  quickPaymentFull: { alignSelf: 'flex-end', paddingVertical: 8 },
  quickPaymentFullText: { color: '#0F766E', fontSize: 13, fontWeight: '700' },
  quickPaymentMethods: { flexDirection: 'row', gap: 8 },
  quickPaymentMethod: { flex: 1, borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 10, paddingVertical: 11, alignItems: 'center' },
  quickPaymentMethodOn: { backgroundColor: '#0F766E', borderColor: '#0F766E' },
  quickPaymentMethodText: { color: '#475569', fontSize: 14, fontWeight: '700' },
  quickPaymentMethodTextOn: { color: '#FFFFFF' },
  quickPaymentReference: { borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 10, paddingHorizontal: 13, paddingVertical: 11, color: '#111827', fontSize: 14 },
  quickPaymentError: { color: '#B91C1C', backgroundColor: '#FEF2F2', padding: 10, borderRadius: 8, marginTop: 12, fontSize: 13 },
  quickPaymentSubmit: { backgroundColor: '#0F766E', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 18, alignSelf: 'stretch' },
  quickPaymentSubmitDisabled: { opacity: 0.55 },
  quickPaymentSubmitText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  paymentSuccess: { alignItems: 'center', paddingVertical: 12 },
  paymentSuccessIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#D1FAE5', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  paymentSuccessIconText: { color: '#059669', fontSize: 30, fontWeight: '800' },
  paymentSuccessAmount: { color: '#059669', fontSize: 28, fontWeight: '800', marginTop: 8 },
});
