import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  header: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: 18,
    paddingBottom: 18,
    paddingTop: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerBackButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  headerBackText: { color: '#FFF', fontSize: 22, fontWeight: '700' },
  headerSubtitle: { color: '#DBEAFE', fontSize: 12, marginTop: 2 },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  dateButton: {
    padding: 12,
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    marginHorizontal: 8,
  },
  dateButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#374151',
  },
  dateText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginHorizontal: 12,
  },
  todayButton: {
    padding: 12,
    backgroundColor: '#3B82F6',
    borderRadius: 8,
    marginLeft: 8,
  },
  todayButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  stockContainer: {
    backgroundColor: '#fff',
    margin: 16,
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  stockTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#111827',
  },
  stockItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  stockVariety: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
    flex: 1,
  },
  stockDetails: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  stockCrates: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#10B981',
  },
  stockCratesLow: {
    color: '#DC2626',
  },
  stockKg: {
    fontSize: 13,
    fontWeight: 'normal',
    color: '#6B7280',
  },
  stockLabel: {
    fontSize: 12,
    color: '#6B7280',
  },
  stockValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#10B981',
  },
  stockValueLow: {
    color: '#DC2626',
  },
  emptyStock: {
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 14,
    fontStyle: 'italic',
    paddingVertical: 16,
  },
  formContainer: {
    backgroundColor: '#fff',
    margin: 16,
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  compactStockSection: {
    backgroundColor: '#FFF',
    borderBottomColor: '#E5E7EB',
    borderBottomWidth: 1,
    paddingBottom: 12,
    paddingTop: 12,
  },
  compactStockHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 16 },
  compactStockTitle: { color: '#111827', fontSize: 14, fontWeight: '700' },
  compactStockHint: { color: '#9CA3AF', fontSize: 11 },
  stockChipRow: { gap: 8, paddingHorizontal: 16, paddingTop: 9 },
  stockChip: { backgroundColor: '#ECFDF5', borderColor: '#A7F3D0', borderRadius: 10, borderWidth: 1, minWidth: 126, paddingHorizontal: 11, paddingVertical: 8 },
  stockChipName: { color: '#064E3B', fontSize: 12, fontWeight: '700', maxWidth: 150 },
  stockChipQty: { color: '#059669', fontSize: 11, fontWeight: '600', marginTop: 3 },
  formHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#111827',
    flex: 1,
  },
  subsectionTitle: { color: '#111827', fontSize: 15, fontWeight: '700', marginBottom: 10, marginTop: 20 },
  selectField: { alignItems: 'center', backgroundColor: '#F9FAFB', borderColor: '#D1D5DB', borderRadius: 10, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, padding: 12 },
  selectIdentity: { flex: 1, paddingRight: 8 },
  selectValue: { color: '#111827', fontSize: 15, fontWeight: '600' },
  selectPlaceholder: { color: '#9CA3AF', fontSize: 15 },
  selectDetail: { color: '#6B7280', fontSize: 11, marginTop: 3 },
  selectChevron: { color: '#6B7280', fontSize: 24 },
  quickPickSection: { marginBottom: 10 },
  quickPickTitle: { color: '#6B7280', fontSize: 11, fontWeight: '700', marginBottom: 6, textTransform: 'uppercase' },
  quickPickRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  quickPickChip: { backgroundColor: '#EFF6FF', borderColor: '#BFDBFE', borderRadius: 14, borderWidth: 1, maxWidth: '31%', paddingHorizontal: 9, paddingVertical: 6 },
  quickPickChipActive: { backgroundColor: '#2563EB', borderColor: '#2563EB' },
  quickPickText: { color: '#1D4ED8', fontSize: 10, fontWeight: '700' },
  quickPickTextActive: { color: '#FFF' },
  changeCustomerButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#F3F4F6',
    borderRadius: 6,
  },
  changeCustomerText: {
    color: '#3B82F6',
    fontSize: 14,
    fontWeight: '600',
  },
  tempItemsContainer: {
    backgroundColor: '#F0F9FF',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  removeDraftText: { color: '#DC2626', fontSize: 13, fontWeight: '600', marginLeft: 10 },
  tempItemsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  tempItemsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E40AF',
  },
  tempTotalContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tempTotalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
  },
  tempTotalValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#3B82F6',
  },
  tempItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#DBEAFE',
  },
  tempItemInfo: {
    flex: 1,
  },
  tempItemName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
  },
  tempItemQty: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 2,
  },
  tempItemActions: {
    flexDirection: 'row',
    gap: 8,
  },
  editTempButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#DBEAFE',
    borderRadius: 6,
  },
  editTempText: {
    color: '#1D4ED8',
    fontSize: 13,
    fontWeight: '600',
  },
  removeTempButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeTempText: {
    color: '#DC2626',
    fontSize: 20,
    fontWeight: 'bold',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  flexButton: {
    flex: 1,
  },
  addItemButton: {
    backgroundColor: '#10B981',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  addItemButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  saveAllButton: {
    backgroundColor: '#3B82F6',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  saveAllButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  pickerContainer: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  quantityHint: { color: '#6B7280', fontSize: 11, marginBottom: 12, marginTop: -8 },
  picker: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    color: '#111827',
    paddingHorizontal: 12,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 6,
  },
  availableText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#10B981',
  },
  availableTextLow: {
    color: '#DC2626',
  },
  row: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  inputContainer: {
    flex: 1,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#111827',
  },
  submitButton: {
    backgroundColor: '#3B82F6',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.5,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  sheetOverlay: { backgroundColor: 'rgba(0,0,0,0.45)', flex: 1, justifyContent: 'flex-end' },
  createCustomerSheet: { backgroundColor: '#FFF', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '90%' },
  sheetHeader: { alignItems: 'center', borderBottomColor: '#E5E7EB', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 18 },
  sheetTitle: { color: '#111827', fontSize: 19, fontWeight: '800' },
  sheetSubtitle: { color: '#6B7280', fontSize: 11, marginTop: 2 },
  sheetCloseText: { color: '#2563EB', fontSize: 14, fontWeight: '700' },
  sheetBody: { padding: 18, paddingBottom: 32 },
  businessPicker: { borderColor: '#D1D5DB', borderRadius: 8, borderWidth: 1, marginBottom: 18, overflow: 'hidden' },
});
