import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { backgroundColor: '#F3F4F6', flex: 1 },
  header: { alignItems: 'center', backgroundColor: '#0F766E', flexDirection: 'row', paddingBottom: 16, paddingHorizontal: 16, paddingTop: 52 },
  backText: { color: '#CCFBF1', fontSize: 15, width: 64 },
  headerTitleWrap: { alignItems: 'center', flex: 1 },
  headerTitle: { color: '#FFF', fontSize: 20, fontWeight: '700' },
  headerSubtitle: { color: '#99F6E4', fontSize: 11, marginTop: 2 },
  adjustButton: { backgroundColor: '#FFF', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8 },
  adjustButtonText: { color: '#0F766E', fontSize: 13, fontWeight: '700' },
  summaryGrid: { backgroundColor: '#FFF', borderBottomColor: '#E5E7EB', borderBottomWidth: 1, flexDirection: 'row', padding: 10 },
  summaryItem: { borderRightColor: '#E5E7EB', borderRightWidth: 1, flex: 1, paddingHorizontal: 7 },
  closingSummary: { borderRightWidth: 0 },
  summaryLabel: { color: '#9CA3AF', fontSize: 10, marginBottom: 4, textTransform: 'uppercase' },
  summaryValue: { color: '#374151', fontSize: 12, fontWeight: '700' },
  inwardValue: { color: '#059669', fontSize: 12, fontWeight: '700' },
  outwardValue: { color: '#DC2626', fontSize: 12, fontWeight: '700' },
  closingValue: { color: '#0F766E', fontSize: 12, fontWeight: '800' },
  toolbar: { backgroundColor: '#FFF', borderBottomColor: '#E5E7EB', borderBottomWidth: 1, gap: 10, padding: 12 },
  searchInput: { backgroundColor: '#F9FAFB', borderColor: '#D1D5DB', borderRadius: 9, borderWidth: 1, color: '#111827', paddingHorizontal: 12, paddingVertical: 10 },
  viewToggle: { backgroundColor: '#F3F4F6', borderRadius: 9, flexDirection: 'row', padding: 3 },
  toggleButton: { alignItems: 'center', borderRadius: 7, flex: 1, paddingVertical: 8 },
  toggleButtonActive: { backgroundColor: '#FFF' },
  toggleText: { color: '#6B7280', fontSize: 13, fontWeight: '600' },
  toggleTextActive: { color: '#0F766E' },
  loading: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  content: { padding: 12, paddingBottom: 32 },
  emptyText: { color: '#6B7280', padding: 36, textAlign: 'center' },
  stockCard: { backgroundColor: '#FFF', borderColor: '#E5E7EB', borderRadius: 12, borderWidth: 1, marginBottom: 9, padding: 14 },
  stockCardHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  stockIdentity: { flex: 1, paddingRight: 10 },
  stockName: { color: '#111827', fontSize: 15, fontWeight: '700' },
  stockStatus: { color: '#059669', fontSize: 11, marginTop: 4 },
  lowStock: { color: '#D97706' },
  closingWrap: { alignItems: 'flex-end' },
  closingLabel: { color: '#9CA3AF', fontSize: 10, textTransform: 'uppercase' },
  stockClosing: { color: '#0F766E', fontSize: 16, fontWeight: '800', marginTop: 2 },
  stockFlowRow: { borderTopColor: '#F3F4F6', borderTopWidth: 1, flexDirection: 'row', gap: 12, marginTop: 12, paddingTop: 10 },
  flowText: { color: '#6B7280', fontSize: 11 },
  flowIn: { color: '#059669', fontSize: 11 },
  flowOut: { color: '#DC2626', fontSize: 11 },
  movementCard: { alignItems: 'center', backgroundColor: '#FFF', borderColor: '#E5E7EB', borderRadius: 10, borderWidth: 1, flexDirection: 'row', marginBottom: 8, padding: 13 },
  voidedCard: { backgroundColor: '#F9FAFB', opacity: 0.7 },
  movementMain: { flex: 1, paddingRight: 8 },
  movementName: { color: '#111827', fontSize: 14, fontWeight: '700' },
  movementMeta: { color: '#6B7280', fontSize: 11, marginTop: 4 },
  movementRight: { alignItems: 'flex-end' },
  movementQty: { fontSize: 14, fontWeight: '800' },
  positiveQty: { color: '#059669' },
  negativeQty: { color: '#DC2626' },
  mixedQty: { color: '#7C3AED' },
  voidedQty: { color: '#6B7280', textDecorationLine: 'line-through' },
  voidLink: { color: '#DC2626', fontSize: 11, fontWeight: '600', marginTop: 7 },
  voidedBadge: { color: '#991B1B', fontSize: 10, fontWeight: '700', marginTop: 5 },
  voidReason: { color: '#991B1B', fontSize: 11, marginTop: 5 },
  sheetOverlay: { backgroundColor: 'rgba(0,0,0,0.45)', flex: 1, justifyContent: 'flex-end' },
  adjustmentSheet: { backgroundColor: '#FFF', borderTopLeftRadius: 22, borderTopRightRadius: 22, maxHeight: '94%' },
  sheetHeader: { alignItems: 'center', borderBottomColor: '#E5E7EB', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 18 },
  sheetTitle: { color: '#111827', fontSize: 19, fontWeight: '800' },
  sheetSubtitle: { color: '#6B7280', fontSize: 11, marginTop: 2 },
  closeText: { color: '#0F766E', fontSize: 14, fontWeight: '700' },
  sheetBody: { padding: 18, paddingBottom: 34 },
  fieldLabel: { color: '#374151', fontSize: 13, fontWeight: '700', marginBottom: 7, marginTop: 14 },
  selectField: { alignItems: 'center', backgroundColor: '#F9FAFB', borderColor: '#D1D5DB', borderRadius: 9, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 13 },
  selectValue: { color: '#111827', flex: 1, fontSize: 15, fontWeight: '600' },
  selectPlaceholder: { color: '#9CA3AF', flex: 1, fontSize: 15 },
  chevron: { color: '#6B7280', fontSize: 24 },
  currentStockBanner: { backgroundColor: '#ECFDF5', borderRadius: 9, flexDirection: 'row', justifyContent: 'space-between', marginTop: 10, padding: 11 },
  currentStockLabel: { color: '#047857', fontSize: 12 },
  currentStockValue: { color: '#065F46', fontSize: 12, fontWeight: '800' },
  modeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  modeChip: { backgroundColor: '#F3F4F6', borderColor: '#E5E7EB', borderRadius: 16, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 8 },
  modeChipActive: { backgroundColor: '#CCFBF1', borderColor: '#14B8A6' },
  modeChipText: { color: '#6B7280', fontSize: 12, fontWeight: '600' },
  modeChipTextActive: { color: '#0F766E' },
  quantityRow: { flexDirection: 'row', gap: 10 },
  quantityField: { flex: 1 },
  quantityLabel: { color: '#6B7280', fontSize: 11, marginBottom: 5 },
  input: { backgroundColor: '#F9FAFB', borderColor: '#D1D5DB', borderRadius: 9, borderWidth: 1, color: '#111827', fontSize: 15, padding: 12 },
  differenceHint: { color: '#0F766E', fontSize: 12, marginTop: 8 },
  reasonChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 8 },
  reasonChip: { backgroundColor: '#F3F4F6', borderRadius: 14, paddingHorizontal: 10, paddingVertical: 6 },
  reasonChipActive: { backgroundColor: '#CCFBF1' },
  reasonChipText: { color: '#6B7280', fontSize: 11 },
  reasonChipTextActive: { color: '#0F766E', fontWeight: '700' },
  notesInput: { minHeight: 70, textAlignVertical: 'top' },
  saveButton: { alignItems: 'center', backgroundColor: '#0F766E', borderRadius: 10, marginTop: 20, padding: 15 },
  disabledButton: { opacity: 0.55 },
  saveButtonText: { color: '#FFF', fontSize: 15, fontWeight: '800' },
  centerOverlay: { alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)', flex: 1, justifyContent: 'center', padding: 20 },
  voidDialog: { backgroundColor: '#FFF', borderRadius: 16, padding: 20, width: '100%' },
  dialogTitle: { color: '#111827', fontSize: 18, fontWeight: '800' },
  dialogHelp: { color: '#6B7280', fontSize: 13, lineHeight: 19, marginBottom: 14, marginTop: 7 },
  voidInput: { minHeight: 70, textAlignVertical: 'top' },
  dialogActions: { flexDirection: 'row', gap: 9, marginTop: 14 },
  cancelButton: { alignItems: 'center', backgroundColor: '#F3F4F6', borderRadius: 8, flex: 1, padding: 13 },
  cancelText: { color: '#374151', fontWeight: '700' },
  confirmVoidButton: { alignItems: 'center', backgroundColor: '#DC2626', borderRadius: 8, flex: 1, padding: 13 },
  confirmVoidText: { color: '#FFF', fontWeight: '800' },
});
