import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { backgroundColor: '#F3F4F6', flex: 1 },
  center: { alignItems: 'center', backgroundColor: '#F3F4F6', flex: 1, justifyContent: 'center' },
  header: { alignItems: 'center', backgroundColor: '#FFF', borderBottomColor: '#E5E7EB', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 16, paddingTop: 50 },
  back: { color: '#0EA5E9', fontSize: 16, width: 62 },
  title: { color: '#111827', fontSize: 18, fontWeight: '700' },
  headerSpacer: { width: 62 },
  summaryCard: { backgroundColor: '#0F172A', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 18, paddingVertical: 16 },
  summaryLabel: { color: '#94A3B8', fontSize: 12, marginBottom: 4 },
  summaryValue: { color: '#FFF', fontSize: 15, fontWeight: '700' },
  summaryPaid: { color: '#6EE7B7', fontSize: 15, fontWeight: '700' },
  summaryDue: { color: '#FCA5A5', fontSize: 15, fontWeight: '700' },
  filters: { backgroundColor: '#FFF', borderBottomColor: '#E5E7EB', borderBottomWidth: 1, gap: 10, padding: 12 },
  searchInput: { backgroundColor: '#F9FAFB', borderColor: '#D1D5DB', borderRadius: 10, borderWidth: 1, color: '#111827', fontSize: 15, paddingHorizontal: 12, paddingVertical: 11 },
  filterChip: { alignSelf: 'flex-start', backgroundColor: '#F3F4F6', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 7 },
  filterChipActive: { backgroundColor: '#E0F2FE' },
  filterText: { color: '#6B7280', fontSize: 13, fontWeight: '600' },
  filterTextActive: { color: '#0369A1' },
  content: { padding: 12, paddingBottom: 30 },
  empty: { alignItems: 'center', padding: 40 },
  emptyTitle: { color: '#6B7280', fontSize: 15 },
  accountCard: { backgroundColor: '#FFF', borderColor: '#E5E7EB', borderRadius: 12, borderWidth: 1, marginBottom: 10, overflow: 'hidden' },
  accountHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', padding: 14 },
  accountNameWrap: { flex: 1, paddingRight: 12 },
  accountName: { color: '#111827', fontSize: 16, fontWeight: '700', marginBottom: 4 },
  accountMeta: { color: '#6B7280', fontSize: 12 },
  accountDueWrap: { alignItems: 'flex-end' },
  accountDue: { color: '#DC2626', fontSize: 16, fontWeight: '700' },
  dueLabel: { color: '#9CA3AF', fontSize: 11, marginTop: 2 },
  entries: { borderTopColor: '#E5E7EB', borderTopWidth: 1 },
  entry: { alignItems: 'center', borderBottomColor: '#F3F4F6', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 14, paddingVertical: 11 },
  voidedEntry: { backgroundColor: '#F9FAFB', opacity: 0.7 },
  entryLeft: { flex: 1, paddingRight: 8 },
  entryTitle: { color: '#374151', fontSize: 14, fontWeight: '600' },
  entryMeta: { color: '#9CA3AF', fontSize: 11, marginTop: 3 },
  entryRight: { alignItems: 'flex-end' },
  billAmount: { color: '#B45309', fontSize: 14, fontWeight: '700' },
  paidAmount: { color: '#059669', fontSize: 14, fontWeight: '700' },
  voidedAmount: { color: '#6B7280', fontSize: 13, textDecorationLine: 'line-through' },
  runningBalance: { color: '#9CA3AF', fontSize: 10, marginTop: 3 },
});
