-- Isolated development schema for the mobile application.
-- This file does not copy or mutate data in public.

CREATE SCHEMA IF NOT EXISTS working;

CREATE TABLE working.units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(16) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL UNIQUE,
  decimal_places SMALLINT NOT NULL DEFAULT 2 CHECK (decimal_places BETWEEN 0 AND 4),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.item_grades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(16) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL UNIQUE,
  sort_order SMALLINT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL UNIQUE,
  primary_unit_id BIGINT NOT NULL REFERENCES working.units(id) ON DELETE RESTRICT,
  secondary_unit_id BIGINT REFERENCES working.units(id) ON DELETE RESTRICT,
  inventory_unit_id BIGINT NOT NULL REFERENCES working.units(id) ON DELETE RESTRICT,
  default_kg_per_crate NUMERIC(8,2) CHECK (default_kg_per_crate > 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (secondary_unit_id IS NULL OR secondary_unit_id <> primary_unit_id)
);

CREATE TABLE working.item_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL REFERENCES working.items(id) ON DELETE RESTRICT,
  grade_id BIGINT NOT NULL REFERENCES working.item_grades(id) ON DELETE RESTRICT,
  variant_code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (item_id, grade_id)
);

INSERT INTO working.units (code, name, decimal_places)
VALUES ('CRATE', 'Crate', 0), ('KG', 'Kilogram', 2);

INSERT INTO working.item_grades (code, name, sort_order)
VALUES
  ('S', 'Small', 10),
  ('M', 'Medium', 20),
  ('B', 'Big', 30),
  ('OB', 'Over Big', 40);

CREATE TABLE working.farmers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(255),
  address TEXT,
  city VARCHAR(100),
  state VARCHAR(100),
  bank_account VARCHAR(50),
  bank_name VARCHAR(255),
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(255),
  address TEXT,
  city VARCHAR(100),
  state VARCHAR(100),
  contact_person VARCHAR(255),
  business_type VARCHAR(100),
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.purchase_bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_number VARCHAR(32) NOT NULL UNIQUE,
  farmer_id BIGINT NOT NULL REFERENCES working.farmers(id) ON DELETE RESTRICT,
  bill_date DATE NOT NULL,
  gross_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  weight_deduction_percentage NUMERIC(5,2) NOT NULL DEFAULT 5,
  weight_deduction_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  subtotal NUMERIC(14,2) NOT NULL DEFAULT 0,
  commission_per_kg NUMERIC(12,2) NOT NULL DEFAULT 0,
  commission_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  other_deductions JSONB NOT NULL DEFAULT '[]'::JSONB,
  other_deductions_total NUMERIC(14,2) NOT NULL DEFAULT 0,
  total NUMERIC(14,2) NOT NULL DEFAULT 0,
  payment_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (payment_status IN ('pending', 'partial', 'paid')),
  amount_paid NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
  balance_due NUMERIC(14,2) NOT NULL DEFAULT 0,
  notes TEXT,
  location VARCHAR(255),
  secondary_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_number VARCHAR(32) NOT NULL UNIQUE,
  customer_id BIGINT NOT NULL REFERENCES working.customers(id) ON DELETE RESTRICT,
  bill_date DATE NOT NULL,
  subtotal NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  discount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  total NUMERIC(14,2) NOT NULL DEFAULT 0,
  previous_balance NUMERIC(14,2) NOT NULL DEFAULT 0,
  amount_paid NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
  balance_due NUMERIC(14,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'unpaid'
    CHECK (status IN ('unpaid', 'paid')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (customer_id, bill_date)
);

CREATE TABLE working.purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farmer_id BIGINT NOT NULL REFERENCES working.farmers(id) ON DELETE RESTRICT,
  fish_variety_id BIGINT NOT NULL REFERENCES working.item_variants(id) ON DELETE RESTRICT,
  quantity_crates INTEGER NOT NULL DEFAULT 0 CHECK (quantity_crates >= 0),
  quantity_kg NUMERIC(12,2) NOT NULL CHECK (quantity_kg > 0),
  purchase_date DATE NOT NULL DEFAULT CURRENT_DATE,
  location VARCHAR(255),
  secondary_name VARCHAR(255),
  billing_status VARCHAR(20) NOT NULL DEFAULT 'unbilled'
    CHECK (billing_status IN ('unbilled', 'billed')),
  billed_in_bill_id BIGINT REFERENCES working.purchase_bills(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (quantity_crates >= 0),
  CHECK (
    (billing_status = 'unbilled' AND billed_in_bill_id IS NULL)
    OR (billing_status = 'billed' AND billed_in_bill_id IS NOT NULL)
  )
);

CREATE TABLE working.sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES working.customers(id) ON DELETE RESTRICT,
  fish_variety_id BIGINT NOT NULL REFERENCES working.item_variants(id) ON DELETE RESTRICT,
  quantity_crates INTEGER NOT NULL DEFAULT 0 CHECK (quantity_crates >= 0),
  quantity_kg NUMERIC(12,2) NOT NULL CHECK (quantity_kg > 0),
  sale_date DATE NOT NULL DEFAULT CURRENT_DATE,
  billing_status VARCHAR(20) NOT NULL DEFAULT 'unbilled'
    CHECK (billing_status IN ('unbilled', 'billed')),
  billed_in_bill_id BIGINT REFERENCES working.bills(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (quantity_crates >= 0),
  CHECK (
    (billing_status = 'unbilled' AND billed_in_bill_id IS NULL)
    OR (billing_status = 'billed' AND billed_in_bill_id IS NOT NULL)
  ),
  UNIQUE (customer_id, fish_variety_id, sale_date)
);

CREATE TABLE working.packing_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT NOT NULL UNIQUE REFERENCES working.sales(id) ON DELETE CASCADE,
  loaded BOOLEAN NOT NULL DEFAULT FALSE,
  loaded_at TIMESTAMPTZ,
  loaded_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.bill_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id BIGINT NOT NULL REFERENCES working.bills(id) ON DELETE CASCADE,
  fish_variety_id BIGINT NOT NULL REFERENCES working.item_variants(id) ON DELETE RESTRICT,
  fish_variety_name VARCHAR(255) NOT NULL,
  quantity_crates INTEGER NOT NULL DEFAULT 0 CHECK (quantity_crates >= 0),
  quantity_kg NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (quantity_kg >= 0),
  crate_weight NUMERIC(12,2) NOT NULL DEFAULT 35 CHECK (crate_weight > 0),
  rate_per_crate NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (rate_per_crate >= 0),
  rate_per_kg NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (rate_per_kg >= 0),
  amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.bill_item_sales (
  bill_item_id BIGINT NOT NULL REFERENCES working.bill_items(id) ON DELETE CASCADE,
  sale_id BIGINT NOT NULL UNIQUE REFERENCES working.sales(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (bill_item_id, sale_id)
);

CREATE TABLE working.bill_other_charges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id BIGINT NOT NULL REFERENCES working.bills(id) ON DELETE CASCADE,
  charge_type VARCHAR(50) NOT NULL
    CHECK (charge_type IN ('packing', 'ice', 'transport', 'loading', 'unloading', 'other')),
  description VARCHAR(255),
  amount NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES working.customers(id) ON DELETE RESTRICT,
  payment_date DATE NOT NULL,
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
  payment_method VARCHAR(50) NOT NULL DEFAULT 'cash'
    CHECK (payment_method IN ('cash', 'bank_transfer', 'upi', 'cheque', 'other')),
  reference_number VARCHAR(100),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.purchase_bill_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_bill_id BIGINT NOT NULL REFERENCES working.purchase_bills(id) ON DELETE CASCADE,
  purchase_id BIGINT NOT NULL UNIQUE REFERENCES working.purchases(id) ON DELETE RESTRICT,
  fish_variety_id BIGINT NOT NULL REFERENCES working.item_variants(id) ON DELETE RESTRICT,
  fish_variety_name VARCHAR(255) NOT NULL,
  quantity_crates INTEGER NOT NULL DEFAULT 0 CHECK (quantity_crates >= 0),
  quantity_kg NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (quantity_kg >= 0),
  actual_weight NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (actual_weight >= 0),
  billable_weight NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (billable_weight >= 0),
  rate_per_kg NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (rate_per_kg >= 0),
  amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.purchase_bill_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_bill_id BIGINT NOT NULL REFERENCES working.purchase_bills(id) ON DELETE CASCADE,
  payment_date DATE NOT NULL,
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
  payment_mode VARCHAR(20) NOT NULL DEFAULT 'cash'
    CHECK (payment_mode IN ('cash', 'bank_transfer', 'upi', 'cheque', 'other')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN working.purchases.quantity_kg IS
  'Actual total catch weight in kilograms; not loose kilograms added to crate estimates.';
COMMENT ON COLUMN working.sales.quantity_kg IS
  'Actual total catch weight in kilograms; not loose kilograms added to crate estimates.';

CREATE UNIQUE INDEX uq_bills_one_active_per_customer
  ON working.bills(customer_id) WHERE is_active;
CREATE INDEX idx_items_active_name ON working.items(is_active, name);
CREATE INDEX idx_item_variants_item_active ON working.item_variants(item_id, is_active);
CREATE INDEX idx_purchases_date_farmer ON working.purchases(purchase_date DESC, farmer_id);
CREATE INDEX idx_sales_date_customer ON working.sales(sale_date DESC, customer_id);
CREATE INDEX idx_bills_customer_date ON working.bills(customer_id, bill_date DESC, id DESC);
CREATE INDEX idx_payments_customer_date ON working.payments(customer_id, payment_date, id);
CREATE INDEX idx_purchase_bills_farmer_date ON working.purchase_bills(farmer_id, bill_date DESC, id DESC);
CREATE INDEX idx_purchase_bill_payments_bill_date
  ON working.purchase_bill_payments(purchase_bill_id, payment_date DESC);

CREATE SEQUENCE working.customer_bill_number_seq;
CREATE SEQUENCE working.purchase_bill_number_seq;

CREATE OR REPLACE FUNCTION working.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = working
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION working.protect_catalog_item_code()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = working
AS $$
BEGIN
  IF NEW.code IS DISTINCT FROM OLD.code
     AND EXISTS (
       SELECT 1
       FROM working.item_variants variant
       WHERE variant.item_id = OLD.id
         AND (
           EXISTS (SELECT 1 FROM working.purchases purchase WHERE purchase.fish_variety_id = variant.id)
           OR EXISTS (SELECT 1 FROM working.sales sale WHERE sale.fish_variety_id = variant.id)
           OR EXISTS (SELECT 1 FROM working.bill_items bill_item WHERE bill_item.fish_variety_id = variant.id)
           OR EXISTS (
             SELECT 1 FROM working.purchase_bill_items purchase_bill_item
             WHERE purchase_bill_item.fish_variety_id = variant.id
           )
         )
     ) THEN
    RAISE EXCEPTION 'Item code cannot change after the item has transaction history';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER protect_catalog_item_code
BEFORE UPDATE OF code ON working.items
FOR EACH ROW
EXECUTE FUNCTION working.protect_catalog_item_code();

REVOKE ALL ON FUNCTION working.protect_catalog_item_code() FROM PUBLIC;

DO $$
DECLARE
  target_table TEXT;
BEGIN
  FOREACH target_table IN ARRAY ARRAY[
    'units', 'item_grades', 'items', 'item_variants',
    'farmers', 'customers', 'purchases', 'sales',
    'packing_status', 'bills', 'payments', 'purchase_bills'
  ] LOOP
    EXECUTE format(
      'CREATE TRIGGER set_updated_at BEFORE UPDATE ON working.%I '
      'FOR EACH ROW EXECUTE FUNCTION working.set_updated_at()',
      target_table
    );
  END LOOP;
END;
$$;
