-- Normalized item catalog for the isolated development schema.
-- Safe for the current empty working schema; production/public is never addressed.

COMMENT ON COLUMN working.purchases.quantity_kg IS
  'Actual total catch weight in kilograms; not loose kilograms added to crate estimates.';
COMMENT ON COLUMN working.sales.quantity_kg IS
  'Actual total catch weight in kilograms; not loose kilograms added to crate estimates.';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'working.purchases'::regclass
      AND conname = 'purchases_actual_weight_positive'
  ) THEN
    ALTER TABLE working.purchases
      ADD CONSTRAINT purchases_actual_weight_positive CHECK (quantity_kg > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'working.sales'::regclass
      AND conname = 'sales_actual_weight_positive'
  ) THEN
    ALTER TABLE working.sales
      ADD CONSTRAINT sales_actual_weight_positive CHECK (quantity_kg > 0);
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS working.units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(16) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL UNIQUE,
  decimal_places SMALLINT NOT NULL DEFAULT 2 CHECK (decimal_places BETWEEN 0 AND 4),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS working.item_grades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(16) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL UNIQUE,
  sort_order SMALLINT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO working.units (code, name, decimal_places)
VALUES ('CRATE', 'Crate', 0), ('KG', 'Kilogram', 2)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    decimal_places = EXCLUDED.decimal_places,
    is_active = TRUE;

INSERT INTO working.item_grades (code, name, sort_order)
VALUES
  ('S', 'Small', 10),
  ('M', 'Medium', 20),
  ('B', 'Big', 30),
  ('OB', 'Over Big', 40)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE;

CREATE TABLE IF NOT EXISTS working.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL UNIQUE,
  primary_unit_id BIGINT NOT NULL REFERENCES working.units(id) ON DELETE RESTRICT,
  secondary_unit_id BIGINT REFERENCES working.units(id) ON DELETE RESTRICT,
  inventory_unit_id BIGINT NOT NULL REFERENCES working.units(id) ON DELETE RESTRICT,
  default_kg_per_crate NUMERIC(8,2) CHECK (default_kg_per_crate > 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (secondary_unit_id IS NULL OR secondary_unit_id <> primary_unit_id)
);

DO $$
BEGIN
  IF to_regclass('working.item_variants') IS NULL
     AND to_regclass('working.fish_varieties') IS NOT NULL THEN
    IF EXISTS (SELECT 1 FROM working.fish_varieties) THEN
      RAISE EXCEPTION
        'working.fish_varieties contains data; define an explicit legacy item/grade mapping before catalog migration';
    END IF;

    ALTER TABLE working.fish_varieties RENAME TO item_variants;
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS working.item_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL REFERENCES working.items(id) ON DELETE RESTRICT,
  grade_id BIGINT NOT NULL REFERENCES working.item_grades(id) ON DELETE RESTRICT,
  variant_code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (item_id, grade_id)
);

ALTER TABLE working.item_variants
  ADD COLUMN IF NOT EXISTS item_id BIGINT REFERENCES working.items(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS grade_id BIGINT REFERENCES working.item_grades(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS variant_code VARCHAR(64);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM working.item_variants
    WHERE item_id IS NULL OR grade_id IS NULL OR variant_code IS NULL
  ) THEN
    RAISE EXCEPTION 'item variant catalog columns cannot be null';
  END IF;
END;
$$;

ALTER TABLE working.item_variants
  ALTER COLUMN item_id SET NOT NULL,
  ALTER COLUMN grade_id SET NOT NULL,
  ALTER COLUMN variant_code SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'working.item_variants'::regclass
      AND conname = 'item_variants_item_id_grade_id_key'
  ) THEN
    ALTER TABLE working.item_variants
      ADD CONSTRAINT item_variants_item_id_grade_id_key UNIQUE (item_id, grade_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'working.item_variants'::regclass
      AND conname = 'item_variants_variant_code_key'
  ) THEN
    ALTER TABLE working.item_variants
      ADD CONSTRAINT item_variants_variant_code_key UNIQUE (variant_code);
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_items_active_name
  ON working.items(is_active, name);
CREATE INDEX IF NOT EXISTS idx_item_variants_item_active
  ON working.item_variants(item_id, is_active);

DO $$
DECLARE
  target_table TEXT;
BEGIN
  FOREACH target_table IN ARRAY ARRAY['units', 'item_grades', 'items', 'item_variants'] LOOP
    IF NOT EXISTS (
      SELECT 1
      FROM pg_trigger
      WHERE tgrelid = format('working.%I', target_table)::regclass
        AND tgname = 'set_updated_at'
        AND NOT tgisinternal
    ) THEN
      EXECUTE format(
        'CREATE TRIGGER set_updated_at BEFORE UPDATE ON working.%I '
        'FOR EACH ROW EXECUTE FUNCTION working.set_updated_at()',
        target_table
      );
    END IF;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION working.upsert_catalog_item(
  p_item_id BIGINT,
  p_name TEXT,
  p_code TEXT,
  p_grade_codes TEXT[],
  p_primary_unit_code TEXT DEFAULT 'CRATE',
  p_secondary_unit_code TEXT DEFAULT 'KG',
  p_inventory_unit_code TEXT DEFAULT 'KG',
  p_default_kg_per_crate NUMERIC DEFAULT 35
)
RETURNS BIGINT
LANGUAGE plpgsql
SET search_path = working
AS $$
DECLARE
  v_item_id BIGINT;
  v_name TEXT := btrim(p_name);
  v_code TEXT := upper(regexp_replace(btrim(p_code), '[^A-Za-z0-9]+', '-', 'g'));
  v_grade_codes TEXT[];
  v_primary_unit_id BIGINT;
  v_secondary_unit_id BIGINT;
  v_inventory_unit_id BIGINT;
  v_grade working.item_grades%ROWTYPE;
  v_grade_count INTEGER := 0;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can manage catalog items';
  END IF;

  IF v_name = '' OR v_code = '' THEN
    RAISE EXCEPTION 'Item name and code are required';
  END IF;

  SELECT array_agg(DISTINCT upper(btrim(grade_code)))
  INTO v_grade_codes
  FROM unnest(p_grade_codes) AS selected_grades(grade_code);

  IF coalesce(cardinality(v_grade_codes), 0) = 0 THEN
    RAISE EXCEPTION 'Select at least one item grade';
  END IF;

  SELECT id INTO v_primary_unit_id
  FROM working.units
  WHERE code = upper(p_primary_unit_code) AND is_active;

  SELECT id INTO v_secondary_unit_id
  FROM working.units
  WHERE code = upper(p_secondary_unit_code) AND is_active;

  SELECT id INTO v_inventory_unit_id
  FROM working.units
  WHERE code = upper(p_inventory_unit_code) AND is_active;

  IF v_primary_unit_id IS NULL OR v_inventory_unit_id IS NULL THEN
    RAISE EXCEPTION 'Primary and inventory units must be active catalog units';
  END IF;

  IF v_primary_unit_id = v_secondary_unit_id THEN
    RAISE EXCEPTION 'Primary and secondary units must be different';
  END IF;

  IF upper(p_primary_unit_code) = 'CRATE'
     AND upper(p_secondary_unit_code) = 'KG'
     AND coalesce(p_default_kg_per_crate, 0) <= 0 THEN
    RAISE EXCEPTION 'Default kilograms per crate must be greater than zero';
  END IF;

  IF p_item_id IS NULL THEN
    INSERT INTO working.items (
      code, name, primary_unit_id, secondary_unit_id, inventory_unit_id,
      default_kg_per_crate
    )
    VALUES (
      v_code, v_name, v_primary_unit_id, v_secondary_unit_id, v_inventory_unit_id,
      p_default_kg_per_crate
    )
    RETURNING id INTO v_item_id;
  ELSE
    UPDATE working.items
    SET code = v_code,
        name = v_name,
        primary_unit_id = v_primary_unit_id,
        secondary_unit_id = v_secondary_unit_id,
        inventory_unit_id = v_inventory_unit_id,
        default_kg_per_crate = p_default_kg_per_crate,
        is_active = TRUE
    WHERE id = p_item_id
    RETURNING id INTO v_item_id;

    IF v_item_id IS NULL THEN
      RAISE EXCEPTION 'Catalog item % was not found', p_item_id;
    END IF;
  END IF;

  UPDATE working.item_variants variant
  SET is_active = FALSE
  FROM working.item_grades grade
  WHERE variant.item_id = v_item_id
    AND variant.grade_id = grade.id
    AND NOT (grade.code = ANY(v_grade_codes));

  FOR v_grade IN
    SELECT *
    FROM working.item_grades
    WHERE code = ANY(v_grade_codes) AND is_active
    ORDER BY sort_order
  LOOP
    v_grade_count := v_grade_count + 1;

    INSERT INTO working.item_variants (
      item_id, grade_id, variant_code, name, is_active
    )
    VALUES (
      v_item_id,
      v_grade.id,
      v_code || '-' || v_grade.code,
      v_name || ' - ' || v_grade.code,
      TRUE
    )
    ON CONFLICT (item_id, grade_id) DO UPDATE
    SET variant_code = EXCLUDED.variant_code,
        name = EXCLUDED.name,
        is_active = TRUE;
  END LOOP;

  IF v_grade_count <> cardinality(v_grade_codes) THEN
    RAISE EXCEPTION 'One or more selected grades are invalid or inactive';
  END IF;

  RETURN v_item_id;
END;
$$;

CREATE OR REPLACE FUNCTION working.archive_catalog_item(p_item_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = working
AS $$
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can manage catalog items';
  END IF;

  UPDATE working.items SET is_active = FALSE WHERE id = p_item_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Catalog item % was not found', p_item_id;
  END IF;

  UPDATE working.item_variants SET is_active = FALSE WHERE item_id = p_item_id;
END;
$$;

GRANT SELECT, INSERT, UPDATE, DELETE ON working.units TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON working.item_grades TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON working.items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON working.item_variants TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA working TO authenticated;
REVOKE ALL ON FUNCTION working.upsert_catalog_item(
  BIGINT, TEXT, TEXT, TEXT[], TEXT, TEXT, TEXT, NUMERIC
) FROM PUBLIC;
REVOKE ALL ON FUNCTION working.archive_catalog_item(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.upsert_catalog_item(
  BIGINT, TEXT, TEXT, TEXT[], TEXT, TEXT, TEXT, NUMERIC
) TO authenticated;
GRANT EXECUTE ON FUNCTION working.archive_catalog_item(BIGINT) TO authenticated;

DO $$
DECLARE
  target_table TEXT;
  read_role TEXT;
BEGIN
  FOREACH target_table IN ARRAY ARRAY['units', 'item_grades', 'items', 'item_variants'] LOOP
    EXECUTE format('ALTER TABLE working.%I ENABLE ROW LEVEL SECURITY', target_table);

    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'working'
        AND tablename = target_table
        AND policyname = 'admin_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY admin_access ON working.%I FOR ALL TO authenticated '
        'USING (working.current_app_role() = ''admin'') '
        'WITH CHECK (working.current_app_role() = ''admin'')',
        target_table
      );
    END IF;

    FOREACH read_role IN ARRAY ARRAY['viewer', 'packer'] LOOP
      IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'working'
          AND tablename = target_table
          AND policyname = read_role || '_read_catalog'
      ) THEN
        EXECUTE format(
          'CREATE POLICY %I ON working.%I FOR SELECT TO authenticated '
          'USING (working.current_app_role() = %L)',
          read_role || '_read_catalog',
          target_table,
          read_role
        );
      END IF;
    END LOOP;
  END LOOP;
END;
$$;
