-- Correct the purchase domain: mediators are payable accounts; farmers are sources.
-- This migration targets only the isolated working schema and preserves existing records.

DO $$
BEGIN
  IF to_regclass('working.mediators') IS NULL
     AND to_regclass('working.farmers') IS NOT NULL THEN
    ALTER TABLE working.farmers RENAME TO mediators;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'working' AND table_name = 'purchases' AND column_name = 'farmer_id'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'working' AND table_name = 'purchases' AND column_name = 'mediator_id'
  ) THEN
    ALTER TABLE working.purchases RENAME COLUMN farmer_id TO mediator_id;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'working' AND table_name = 'purchase_bills' AND column_name = 'farmer_id'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'working' AND table_name = 'purchase_bills' AND column_name = 'mediator_id'
  ) THEN
    ALTER TABLE working.purchase_bills RENAME COLUMN farmer_id TO mediator_id;
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'working.purchases'::regclass
      AND conname = 'purchases_farmer_id_fkey'
  ) THEN
    ALTER TABLE working.purchases
      RENAME CONSTRAINT purchases_farmer_id_fkey TO purchases_mediator_id_fkey;
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'working.purchase_bills'::regclass
      AND conname = 'purchase_bills_farmer_id_fkey'
  ) THEN
    ALTER TABLE working.purchase_bills
      RENAME CONSTRAINT purchase_bills_farmer_id_fkey TO purchase_bills_mediator_id_fkey;
  END IF;
END;
$$;

DROP INDEX IF EXISTS working.idx_purchases_date_farmer;
DROP INDEX IF EXISTS working.idx_purchase_bills_farmer_date;

CREATE TABLE IF NOT EXISTS working.farmers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  location VARCHAR(255),
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS farmers_normalized_name_key
  ON working.farmers (lower(regexp_replace(btrim(name), '[[:space:]]+', ' ', 'g')));

ALTER TABLE working.purchases
  ADD COLUMN IF NOT EXISTS farmer_id BIGINT REFERENCES working.farmers(id) ON DELETE RESTRICT;

INSERT INTO working.farmers (name)
SELECT DISTINCT ON (lower(regexp_replace(btrim(secondary_name), '[[:space:]]+', ' ', 'g')))
  regexp_replace(btrim(secondary_name), '[[:space:]]+', ' ', 'g')
FROM working.purchases
WHERE secondary_name IS NOT NULL AND btrim(secondary_name) <> ''
ON CONFLICT DO NOTHING;

UPDATE working.purchases purchase
SET farmer_id = farmer.id
FROM working.farmers farmer
WHERE purchase.farmer_id IS NULL
  AND lower(regexp_replace(btrim(purchase.secondary_name), '[[:space:]]+', ' ', 'g'))
    = lower(regexp_replace(btrim(farmer.name), '[[:space:]]+', ' ', 'g'));

DO $$
DECLARE
  fallback_farmer_id BIGINT;
BEGIN
  IF EXISTS (SELECT 1 FROM working.purchases WHERE farmer_id IS NULL) THEN
    INSERT INTO working.farmers (name, notes)
    VALUES ('Unspecified legacy farmer', 'Created during mediator/farmer migration; review these purchases.')
    ON CONFLICT DO NOTHING;

    SELECT id INTO fallback_farmer_id
    FROM working.farmers
    WHERE lower(name) = 'unspecified legacy farmer';

    UPDATE working.purchases
    SET farmer_id = fallback_farmer_id
    WHERE farmer_id IS NULL;
  END IF;
END;
$$;

ALTER TABLE working.purchases ALTER COLUMN farmer_id SET NOT NULL;

COMMENT ON TABLE working.mediators IS
  'Payable purchase accounts that receive purchase bills and payments.';
COMMENT ON TABLE working.farmers IS
  'Physical farmers or sources from whom the purchased stock originated.';
COMMENT ON COLUMN working.purchases.secondary_name IS
  'Deprecated legacy farmer-name snapshot; use farmer_id for new records.';

CREATE INDEX IF NOT EXISTS idx_purchases_date_mediator
  ON working.purchases(purchase_date DESC, mediator_id);
CREATE INDEX IF NOT EXISTS idx_purchases_date_farmer
  ON working.purchases(purchase_date DESC, farmer_id);
CREATE INDEX IF NOT EXISTS idx_purchase_bills_mediator_date
  ON working.purchase_bills(mediator_id, bill_date DESC, id DESC);

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON working.farmers
FOR EACH ROW EXECUTE FUNCTION working.set_updated_at();

ALTER TABLE working.farmers ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_access ON working.farmers
FOR ALL TO authenticated
USING (working.current_app_role() = 'admin')
WITH CHECK (working.current_app_role() = 'admin');

CREATE POLICY viewer_read_farmers ON working.farmers
FOR SELECT TO authenticated
USING (working.current_app_role() = 'viewer');

CREATE POLICY packer_read_farmers ON working.farmers
FOR SELECT TO authenticated
USING (working.current_app_role() = 'packer');

GRANT SELECT, INSERT, UPDATE, DELETE ON working.mediators TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON working.farmers TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA working TO authenticated;

CREATE OR REPLACE FUNCTION working.create_purchase_batch(
  p_mediator_id BIGINT,
  p_farmer_id BIGINT,
  p_purchase_date DATE,
  p_location TEXT,
  p_items JSONB
)
RETURNS SETOF working.purchases
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = working
AS $$
DECLARE
  item JSONB;
  item_count INTEGER;
  distinct_item_count INTEGER;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can create purchases';
  END IF;

  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'At least one purchase item is required';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM working.mediators WHERE id = p_mediator_id AND is_active) THEN
    RAISE EXCEPTION 'Select an active mediator';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM working.farmers WHERE id = p_farmer_id AND is_active) THEN
    RAISE EXCEPTION 'Select an active farmer';
  END IF;

  SELECT count(*), count(DISTINCT (value ->> 'fish_variety_id'))
  INTO item_count, distinct_item_count
  FROM jsonb_array_elements(p_items);

  IF item_count <> distinct_item_count THEN
    RAISE EXCEPTION 'Each item and grade can appear only once in a purchase batch';
  END IF;

  FOR item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    IF coalesce((item ->> 'quantity_crates')::INTEGER, 0) < 0
       OR coalesce((item ->> 'quantity_kg')::NUMERIC, 0) <= 0 THEN
      RAISE EXCEPTION 'Crates cannot be negative and actual kilograms must be greater than zero';
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM working.item_variants variant
      JOIN working.items catalog_item ON catalog_item.id = variant.item_id
      WHERE variant.id = (item ->> 'fish_variety_id')::BIGINT
        AND variant.is_active
        AND catalog_item.is_active
    ) THEN
      RAISE EXCEPTION 'A selected item or grade is inactive';
    END IF;
  END LOOP;

  RETURN QUERY
  INSERT INTO working.purchases (
    mediator_id, farmer_id, fish_variety_id, quantity_crates, quantity_kg,
    purchase_date, location, secondary_name
  )
  SELECT
    p_mediator_id,
    p_farmer_id,
    (value ->> 'fish_variety_id')::BIGINT,
    coalesce((value ->> 'quantity_crates')::INTEGER, 0),
    (value ->> 'quantity_kg')::NUMERIC,
    p_purchase_date,
    nullif(btrim(p_location), ''),
    (SELECT name FROM working.farmers WHERE id = p_farmer_id)
  FROM jsonb_array_elements(p_items)
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION working.protect_billed_purchase()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = working
AS $$
BEGIN
  IF TG_OP = 'DELETE' AND OLD.billing_status = 'billed' THEN
    RAISE EXCEPTION 'Billed purchases cannot be deleted';
  END IF;

  IF TG_OP = 'UPDATE'
     AND OLD.billing_status = 'billed'
     AND (
       NEW.mediator_id IS DISTINCT FROM OLD.mediator_id
       OR NEW.farmer_id IS DISTINCT FROM OLD.farmer_id
       OR NEW.fish_variety_id IS DISTINCT FROM OLD.fish_variety_id
       OR NEW.quantity_crates IS DISTINCT FROM OLD.quantity_crates
       OR NEW.quantity_kg IS DISTINCT FROM OLD.quantity_kg
       OR NEW.purchase_date IS DISTINCT FROM OLD.purchase_date
       OR NEW.location IS DISTINCT FROM OLD.location
     ) THEN
    RAISE EXCEPTION 'Billed purchase details cannot be changed';
  END IF;

  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_billed_purchase ON working.purchases;
CREATE TRIGGER protect_billed_purchase
BEFORE UPDATE OR DELETE ON working.purchases
FOR EACH ROW EXECUTE FUNCTION working.protect_billed_purchase();

DROP FUNCTION IF EXISTS working.create_purchase_bill(
  BIGINT, DATE, JSONB, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TEXT, TEXT
);

CREATE FUNCTION working.create_purchase_bill(
  p_mediator_id BIGINT,
  p_bill_date DATE,
  p_items JSONB,
  p_commission_amount NUMERIC DEFAULT 0,
  p_advance_amount NUMERIC DEFAULT 0,
  p_other_charges_addition NUMERIC DEFAULT 0,
  p_other_charges_deduction NUMERIC DEFAULT 0,
  p_notes TEXT DEFAULT NULL,
  p_location TEXT DEFAULT NULL
)
RETURNS working.purchase_bills
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = working
AS $$
DECLARE
  item JSONB;
  created_bill working.purchase_bills%ROWTYPE;
  purchase_id_value BIGINT;
  gross_amount_value NUMERIC(14,2) := 0;
  subtotal_value NUMERIC(14,2) := 0;
  weight_deduction_value NUMERIC(14,2);
  deductions JSONB := '[]'::JSONB;
  deductions_total NUMERIC(14,2);
  total_value NUMERIC(14,2);
  bill_number_value TEXT;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can create purchase bills';
  END IF;
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'At least one purchase bill item is required';
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtextextended('working-purchase-bill:' || p_mediator_id::TEXT, 0)
  );

  FOR item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    purchase_id_value := (item ->> 'purchase_id')::BIGINT;

    PERFORM 1
    FROM working.purchases
    WHERE id = purchase_id_value
      AND mediator_id = p_mediator_id
      AND fish_variety_id = (item ->> 'fish_variety_id')::BIGINT
      AND quantity_crates = (item ->> 'quantity_crates')::INTEGER
      AND quantity_kg = (item ->> 'quantity_kg')::NUMERIC
      AND billing_status = 'unbilled'
      AND billed_in_bill_id IS NULL
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Purchase % is unavailable or does not match the bill', purchase_id_value;
    END IF;

    gross_amount_value := gross_amount_value
      + (item ->> 'actual_weight')::NUMERIC * (item ->> 'rate_per_kg')::NUMERIC;
    subtotal_value := subtotal_value + (item ->> 'amount')::NUMERIC;
  END LOOP;

  weight_deduction_value := gross_amount_value - subtotal_value;
  deductions_total := coalesce(p_advance_amount, 0) + coalesce(p_other_charges_deduction, 0);
  total_value := subtotal_value + coalesce(p_commission_amount, 0)
    + coalesce(p_other_charges_addition, 0) - deductions_total;

  IF coalesce(p_advance_amount, 0) > 0 THEN
    deductions := deductions || jsonb_build_array(
      jsonb_build_object('type', 'advance', 'amount', p_advance_amount)
    );
  END IF;
  IF coalesce(p_other_charges_addition, 0) > 0 THEN
    deductions := deductions || jsonb_build_array(
      jsonb_build_object('type', 'other_charges_addition', 'amount', p_other_charges_addition)
    );
  END IF;
  IF coalesce(p_other_charges_deduction, 0) > 0 THEN
    deductions := deductions || jsonb_build_array(
      jsonb_build_object('type', 'other_charges_deduction', 'amount', p_other_charges_deduction)
    );
  END IF;

  bill_number_value := 'PB-'
    || lpad(nextval('working.purchase_bill_number_seq')::TEXT, 4, '0');

  INSERT INTO working.purchase_bills (
    bill_number, mediator_id, bill_date, gross_amount, weight_deduction_percentage,
    weight_deduction_amount, subtotal, commission_per_kg, commission_amount,
    other_deductions, other_deductions_total, total, payment_status,
    amount_paid, balance_due, notes, location, secondary_name
  ) VALUES (
    bill_number_value, p_mediator_id, p_bill_date, gross_amount_value, 5,
    weight_deduction_value, subtotal_value, 0, coalesce(p_commission_amount, 0),
    deductions, deductions_total, total_value, 'pending', 0, total_value,
    p_notes, nullif(btrim(p_location), ''), NULL
  ) RETURNING * INTO created_bill;

  FOR item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    purchase_id_value := (item ->> 'purchase_id')::BIGINT;

    INSERT INTO working.purchase_bill_items (
      purchase_bill_id, purchase_id, fish_variety_id, fish_variety_name,
      quantity_crates, quantity_kg, actual_weight, billable_weight, rate_per_kg, amount
    ) VALUES (
      created_bill.id,
      purchase_id_value,
      (item ->> 'fish_variety_id')::BIGINT,
      item ->> 'fish_variety_name',
      (item ->> 'quantity_crates')::INTEGER,
      (item ->> 'quantity_kg')::NUMERIC,
      (item ->> 'actual_weight')::NUMERIC,
      (item ->> 'billable_weight')::NUMERIC,
      (item ->> 'rate_per_kg')::NUMERIC,
      (item ->> 'amount')::NUMERIC
    );

    UPDATE working.purchases
    SET billing_status = 'billed', billed_in_bill_id = created_bill.id
    WHERE id = purchase_id_value;
  END LOOP;

  RETURN created_bill;
END;
$$;

REVOKE ALL ON FUNCTION working.create_purchase_batch(BIGINT, BIGINT, DATE, TEXT, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION working.protect_billed_purchase() FROM PUBLIC;
REVOKE ALL ON FUNCTION working.create_purchase_bill(
  BIGINT, DATE, JSONB, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TEXT
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.create_purchase_batch(BIGINT, BIGINT, DATE, TEXT, JSONB)
  TO authenticated;
GRANT EXECUTE ON FUNCTION working.create_purchase_bill(
  BIGINT, DATE, JSONB, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TEXT
) TO authenticated;
