-- Cumulative, auditable inventory ledger with source synchronization and reconciliation.

CREATE TABLE working.stock_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO working.stock_locations (code, name)
VALUES ('MAIN', 'Main stock')
ON CONFLICT (code) DO NOTHING;

CREATE TABLE working.stock_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movement_date DATE NOT NULL,
  location_id BIGINT NOT NULL REFERENCES working.stock_locations(id) ON DELETE RESTRICT,
  item_variant_id BIGINT NOT NULL REFERENCES working.item_variants(id) ON DELETE RESTRICT,
  movement_type VARCHAR(32) NOT NULL CHECK (movement_type IN (
    'opening', 'purchase', 'sale', 'adjustment_in', 'adjustment_out',
    'wastage', 'sale_return', 'purchase_return', 'reconciliation'
  )),
  crates_delta INTEGER NOT NULL DEFAULT 0,
  kg_delta NUMERIC(12,2) NOT NULL DEFAULT 0,
  source_type VARCHAR(24) CHECK (source_type IN ('purchase', 'sale', 'manual')),
  source_id BIGINT,
  reason VARCHAR(255),
  notes TEXT,
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  voided_at TIMESTAMPTZ,
  voided_by UUID,
  void_reason TEXT,
  CHECK (crates_delta <> 0 OR kg_delta <> 0),
  CHECK (
    (movement_type IN ('opening', 'purchase', 'adjustment_in', 'sale_return')
      AND crates_delta >= 0 AND kg_delta >= 0)
    OR (movement_type IN ('sale', 'adjustment_out', 'wastage', 'purchase_return')
      AND crates_delta <= 0 AND kg_delta <= 0)
    OR movement_type = 'reconciliation'
  ),
  CHECK (
    (source_type IN ('purchase', 'sale') AND source_id IS NOT NULL)
    OR source_type = 'manual'
  )
);

CREATE UNIQUE INDEX uq_active_stock_source_movement
  ON working.stock_movements(source_type, source_id)
  WHERE source_type IN ('purchase', 'sale') AND voided_at IS NULL;

CREATE INDEX idx_stock_movements_variant_location_date
  ON working.stock_movements(item_variant_id, location_id, movement_date, id)
  WHERE voided_at IS NULL;

CREATE INDEX idx_stock_movements_recent
  ON working.stock_movements(movement_date DESC, id DESC);

ALTER TABLE working.stock_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.stock_movements ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_access ON working.stock_locations
FOR ALL TO authenticated
USING (working.current_app_role() = 'admin')
WITH CHECK (working.current_app_role() = 'admin');

CREATE POLICY admin_read_stock_movements ON working.stock_movements
FOR SELECT TO authenticated
USING (working.current_app_role() = 'admin');

CREATE POLICY viewer_read_stock_locations ON working.stock_locations
FOR SELECT TO authenticated
USING (working.current_app_role() IN ('viewer', 'packer'));

CREATE POLICY viewer_read_stock_movements ON working.stock_movements
FOR SELECT TO authenticated
USING (working.current_app_role() IN ('viewer', 'packer'));

GRANT SELECT, INSERT, UPDATE, DELETE ON working.stock_locations TO authenticated;
GRANT SELECT ON working.stock_movements TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON working.stock_movements FROM authenticated;
GRANT USAGE, SELECT ON SEQUENCE working.stock_locations_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE working.stock_movements_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION working.assert_stock_delta_available(
  p_item_variant_id BIGINT,
  p_location_id BIGINT,
  p_crates_delta INTEGER,
  p_kg_delta NUMERIC
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working
AS $$
DECLARE
  current_crates BIGINT;
  current_kg NUMERIC(14,2);
BEGIN
  PERFORM pg_advisory_xact_lock(
    hashtextextended('working-stock:' || p_location_id::TEXT || ':' || p_item_variant_id::TEXT, 0)
  );

  SELECT coalesce(sum(crates_delta), 0), coalesce(sum(kg_delta), 0)
  INTO current_crates, current_kg
  FROM working.stock_movements
  WHERE item_variant_id = p_item_variant_id
    AND location_id = p_location_id
    AND voided_at IS NULL;

  IF current_crates + p_crates_delta < 0 THEN
    RAISE EXCEPTION 'Insufficient crate stock. Available: %, requested: %',
      current_crates, abs(p_crates_delta);
  END IF;

  IF current_kg + p_kg_delta < 0 THEN
    RAISE EXCEPTION 'Insufficient kilogram stock. Available: %, requested: %',
      current_kg, abs(p_kg_delta);
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION working.sync_source_stock_movement()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working
AS $$
DECLARE
  default_location_id BIGINT;
  source_kind TEXT := CASE WHEN TG_TABLE_NAME = 'purchases' THEN 'purchase' ELSE 'sale' END;
  variant_id BIGINT;
  record_id BIGINT;
  record_date DATE;
  crates_value INTEGER;
  kg_value NUMERIC;
  old_crates_delta INTEGER;
  old_kg_delta NUMERIC;
BEGIN
  SELECT id INTO default_location_id
  FROM working.stock_locations
  WHERE code = 'MAIN' AND is_active;

  IF default_location_id IS NULL THEN
    RAISE EXCEPTION 'Main stock location is unavailable';
  END IF;

  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    SELECT crates_delta, kg_delta
    INTO old_crates_delta, old_kg_delta
    FROM working.stock_movements
    WHERE source_type = source_kind
      AND source_id = OLD.id
      AND voided_at IS NULL
    FOR UPDATE;

    IF TG_OP = 'DELETE' AND (coalesce(old_crates_delta, 0) > 0 OR coalesce(old_kg_delta, 0) > 0) THEN
      PERFORM working.assert_stock_delta_available(
        OLD.fish_variety_id,
        default_location_id,
        -coalesce(old_crates_delta, 0),
        -coalesce(old_kg_delta, 0)
      );
    END IF;

    UPDATE working.stock_movements
    SET voided_at = now(),
        void_reason = CASE WHEN TG_OP = 'DELETE' THEN 'Source record deleted' ELSE 'Source record changed' END
    WHERE source_type = source_kind
      AND source_id = OLD.id
      AND voided_at IS NULL;
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  record_id := NEW.id;
  variant_id := NEW.fish_variety_id;
  crates_value := NEW.quantity_crates;

  IF source_kind = 'purchase' THEN
    record_date := NEW.purchase_date;
    kg_value := NEW.quantity_kg;
  ELSE
    record_date := NEW.sale_date;
    crates_value := -crates_value;
    kg_value := -NEW.quantity_kg;
  END IF;

  PERFORM working.assert_stock_delta_available(
    variant_id, default_location_id, crates_value, kg_value
  );

  INSERT INTO working.stock_movements (
    movement_date, location_id, item_variant_id, movement_type,
    crates_delta, kg_delta, source_type, source_id, reason, created_by
  ) VALUES (
    record_date, default_location_id, variant_id, source_kind,
    crates_value, kg_value, source_kind, record_id,
    CASE WHEN source_kind = 'purchase' THEN 'Purchase stock received' ELSE 'Customer sale dispatched' END,
    auth.uid()
  );

  RETURN NEW;
END;
$$;

-- Backfill the isolated development data before enabling automatic synchronization.
INSERT INTO working.stock_movements (
  movement_date, location_id, item_variant_id, movement_type,
  crates_delta, kg_delta, source_type, source_id, reason, created_at
)
SELECT
  purchase.purchase_date,
  location.id,
  purchase.fish_variety_id,
  'purchase',
  purchase.quantity_crates,
  purchase.quantity_kg,
  'purchase',
  purchase.id,
  'Backfilled purchase',
  purchase.created_at
FROM working.purchases purchase
CROSS JOIN working.stock_locations location
WHERE location.code = 'MAIN'
  AND NOT EXISTS (
    SELECT 1 FROM working.stock_movements movement
    WHERE movement.source_type = 'purchase'
      AND movement.source_id = purchase.id
      AND movement.voided_at IS NULL
  );

INSERT INTO working.stock_movements (
  movement_date, location_id, item_variant_id, movement_type,
  crates_delta, kg_delta, source_type, source_id, reason, created_at
)
SELECT
  sale.sale_date,
  location.id,
  sale.fish_variety_id,
  'sale',
  -sale.quantity_crates,
  -sale.quantity_kg,
  'sale',
  sale.id,
  'Backfilled sale',
  sale.created_at
FROM working.sales sale
CROSS JOIN working.stock_locations location
WHERE location.code = 'MAIN'
  AND NOT EXISTS (
    SELECT 1 FROM working.stock_movements movement
    WHERE movement.source_type = 'sale'
      AND movement.source_id = sale.id
      AND movement.voided_at IS NULL
  );

CREATE TRIGGER sync_purchase_stock_after_insert
AFTER INSERT ON working.purchases
FOR EACH ROW EXECUTE FUNCTION working.sync_source_stock_movement();

CREATE TRIGGER sync_purchase_stock_after_update
AFTER UPDATE OF fish_variety_id, quantity_crates, quantity_kg, purchase_date ON working.purchases
FOR EACH ROW
WHEN (
  OLD.fish_variety_id IS DISTINCT FROM NEW.fish_variety_id
  OR OLD.quantity_crates IS DISTINCT FROM NEW.quantity_crates
  OR OLD.quantity_kg IS DISTINCT FROM NEW.quantity_kg
  OR OLD.purchase_date IS DISTINCT FROM NEW.purchase_date
)
EXECUTE FUNCTION working.sync_source_stock_movement();

CREATE TRIGGER sync_purchase_stock_after_delete
AFTER DELETE ON working.purchases
FOR EACH ROW EXECUTE FUNCTION working.sync_source_stock_movement();

CREATE TRIGGER sync_sale_stock_after_insert
AFTER INSERT ON working.sales
FOR EACH ROW EXECUTE FUNCTION working.sync_source_stock_movement();

CREATE TRIGGER sync_sale_stock_after_update
AFTER UPDATE OF fish_variety_id, quantity_crates, quantity_kg, sale_date ON working.sales
FOR EACH ROW
WHEN (
  OLD.fish_variety_id IS DISTINCT FROM NEW.fish_variety_id
  OR OLD.quantity_crates IS DISTINCT FROM NEW.quantity_crates
  OR OLD.quantity_kg IS DISTINCT FROM NEW.quantity_kg
  OR OLD.sale_date IS DISTINCT FROM NEW.sale_date
)
EXECUTE FUNCTION working.sync_source_stock_movement();

CREATE TRIGGER sync_sale_stock_after_delete
AFTER DELETE ON working.sales
FOR EACH ROW EXECUTE FUNCTION working.sync_source_stock_movement();

CREATE OR REPLACE FUNCTION working.record_stock_adjustment(
  p_item_variant_id BIGINT,
  p_movement_date DATE,
  p_adjustment_type VARCHAR,
  p_quantity_crates INTEGER,
  p_quantity_kg NUMERIC,
  p_reason TEXT,
  p_notes TEXT DEFAULT NULL
)
RETURNS working.stock_movements
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working
AS $$
DECLARE
  default_location_id BIGINT;
  created_movement working.stock_movements%ROWTYPE;
  crates_value INTEGER := coalesce(p_quantity_crates, 0);
  kg_value NUMERIC := coalesce(p_quantity_kg, 0);
  reason_value TEXT := nullif(btrim(p_reason), '');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can adjust stock';
  END IF;

  IF p_adjustment_type NOT IN ('adjustment_in', 'adjustment_out', 'wastage', 'sale_return', 'purchase_return') THEN
    RAISE EXCEPTION 'Invalid stock adjustment type';
  END IF;
  IF crates_value < 0 OR kg_value < 0 OR (crates_value = 0 AND kg_value = 0) THEN
    RAISE EXCEPTION 'Enter a positive crate or kilogram quantity';
  END IF;
  IF reason_value IS NULL THEN
    RAISE EXCEPTION 'A reason is required for every stock adjustment';
  END IF;
  IF p_movement_date > current_date THEN
    RAISE EXCEPTION 'Stock adjustment date cannot be in the future';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM working.item_variants variant
    JOIN working.items item ON item.id = variant.item_id
    WHERE variant.id = p_item_variant_id AND variant.is_active AND item.is_active
  ) THEN
    RAISE EXCEPTION 'Select an active item and grade';
  END IF;

  SELECT id INTO default_location_id FROM working.stock_locations WHERE code = 'MAIN' AND is_active;
  IF default_location_id IS NULL THEN RAISE EXCEPTION 'Main stock location is unavailable'; END IF;

  IF p_adjustment_type IN ('adjustment_out', 'wastage', 'purchase_return') THEN
    crates_value := -crates_value;
    kg_value := -kg_value;
  END IF;

  PERFORM working.assert_stock_delta_available(
    p_item_variant_id, default_location_id, crates_value, kg_value
  );

  INSERT INTO working.stock_movements (
    movement_date, location_id, item_variant_id, movement_type,
    crates_delta, kg_delta, source_type, reason, notes, created_by
  ) VALUES (
    p_movement_date, default_location_id, p_item_variant_id, p_adjustment_type,
    crates_value, kg_value, 'manual', reason_value, nullif(btrim(p_notes), ''), auth.uid()
  ) RETURNING * INTO created_movement;

  RETURN created_movement;
END;
$$;

CREATE OR REPLACE FUNCTION working.reconcile_stock(
  p_item_variant_id BIGINT,
  p_movement_date DATE,
  p_counted_crates INTEGER,
  p_counted_kg NUMERIC,
  p_reason TEXT,
  p_notes TEXT DEFAULT NULL
)
RETURNS working.stock_movements
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working
AS $$
DECLARE
  default_location_id BIGINT;
  current_crates BIGINT;
  current_kg NUMERIC(14,2);
  crates_difference INTEGER;
  kg_difference NUMERIC(14,2);
  created_movement working.stock_movements%ROWTYPE;
  reason_value TEXT := nullif(btrim(p_reason), '');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can reconcile stock';
  END IF;
  IF coalesce(p_counted_crates, -1) < 0 OR coalesce(p_counted_kg, -1) < 0 THEN
    RAISE EXCEPTION 'Counted stock cannot be negative';
  END IF;
  IF reason_value IS NULL THEN
    RAISE EXCEPTION 'A reconciliation reason is required';
  END IF;
  IF p_movement_date > current_date THEN
    RAISE EXCEPTION 'Reconciliation date cannot be in the future';
  END IF;

  SELECT id INTO default_location_id FROM working.stock_locations WHERE code = 'MAIN' AND is_active;
  IF default_location_id IS NULL THEN RAISE EXCEPTION 'Main stock location is unavailable'; END IF;
  PERFORM pg_advisory_xact_lock(
    hashtextextended('working-stock:' || default_location_id::TEXT || ':' || p_item_variant_id::TEXT, 0)
  );

  SELECT coalesce(sum(crates_delta), 0), coalesce(sum(kg_delta), 0)
  INTO current_crates, current_kg
  FROM working.stock_movements
  WHERE item_variant_id = p_item_variant_id
    AND location_id = default_location_id
    AND movement_date <= p_movement_date
    AND voided_at IS NULL;

  crates_difference := p_counted_crates - current_crates;
  kg_difference := p_counted_kg - current_kg;
  IF crates_difference = 0 AND kg_difference = 0 THEN
    RAISE EXCEPTION 'Counted stock already matches the ledger';
  END IF;

  INSERT INTO working.stock_movements (
    movement_date, location_id, item_variant_id, movement_type,
    crates_delta, kg_delta, source_type, reason, notes, created_by
  ) VALUES (
    p_movement_date, default_location_id, p_item_variant_id, 'reconciliation',
    crates_difference, kg_difference, 'manual', reason_value,
    nullif(btrim(p_notes), ''), auth.uid()
  ) RETURNING * INTO created_movement;

  RETURN created_movement;
END;
$$;

CREATE OR REPLACE FUNCTION working.void_stock_adjustment(
  p_movement_id BIGINT,
  p_void_reason TEXT
)
RETURNS working.stock_movements
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working
AS $$
DECLARE
  target working.stock_movements%ROWTYPE;
  reason_value TEXT := nullif(btrim(p_void_reason), '');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can void stock adjustments';
  END IF;
  IF reason_value IS NULL THEN
    RAISE EXCEPTION 'A void reason is required';
  END IF;

  SELECT * INTO target FROM working.stock_movements WHERE id = p_movement_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Stock movement not found'; END IF;
  IF target.source_type <> 'manual' THEN
    RAISE EXCEPTION 'Purchase and sale movements must be corrected from their source record';
  END IF;
  IF target.voided_at IS NOT NULL THEN RAISE EXCEPTION 'Stock adjustment is already voided'; END IF;

  PERFORM working.assert_stock_delta_available(
    target.item_variant_id, target.location_id, -target.crates_delta, -target.kg_delta
  );

  UPDATE working.stock_movements
  SET voided_at = now(), voided_by = auth.uid(), void_reason = reason_value
  WHERE id = p_movement_id
  RETURNING * INTO target;

  RETURN target;
END;
$$;

CREATE OR REPLACE FUNCTION working.save_sales_batch(
  p_customer_id BIGINT,
  p_sale_date DATE,
  p_items JSONB
)
RETURNS SETOF working.sales
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = working
AS $$
DECLARE
  item JSONB;
  item_count INTEGER;
  distinct_item_count INTEGER;
  saved_sale working.sales%ROWTYPE;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can create sales';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM working.customers WHERE id = p_customer_id AND is_active) THEN
    RAISE EXCEPTION 'Select an active customer';
  END IF;
  IF p_sale_date > current_date THEN
    RAISE EXCEPTION 'Sale date cannot be in the future';
  END IF;
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'At least one sale item is required';
  END IF;

  SELECT count(*), count(DISTINCT (value ->> 'fish_variety_id'))
  INTO item_count, distinct_item_count
  FROM jsonb_array_elements(p_items);
  IF item_count <> distinct_item_count THEN
    RAISE EXCEPTION 'Each item and grade can appear only once';
  END IF;

  FOR item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    IF coalesce((item ->> 'quantity_crates')::INTEGER, 0) < 0
       OR coalesce((item ->> 'quantity_kg')::NUMERIC, 0) <= 0 THEN
      RAISE EXCEPTION 'Crates cannot be negative and actual kilograms must be greater than zero';
    END IF;

    saved_sale := NULL;
    INSERT INTO working.sales (
      customer_id, fish_variety_id, quantity_crates, quantity_kg, sale_date
    ) VALUES (
      p_customer_id,
      (item ->> 'fish_variety_id')::BIGINT,
      coalesce((item ->> 'quantity_crates')::INTEGER, 0),
      (item ->> 'quantity_kg')::NUMERIC,
      p_sale_date
    )
    ON CONFLICT (customer_id, fish_variety_id, sale_date)
    DO UPDATE SET
      quantity_crates = EXCLUDED.quantity_crates,
      quantity_kg = EXCLUDED.quantity_kg
    WHERE sales.billing_status = 'unbilled'
    RETURNING * INTO saved_sale;

    IF saved_sale.id IS NULL THEN
      RAISE EXCEPTION 'A billed sale cannot be changed';
    END IF;
    RETURN NEXT saved_sale;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION working.update_sales_group(
  p_customer_id BIGINT,
  p_sale_date DATE,
  p_items JSONB
)
RETURNS SETOF working.sales
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = working
AS $$
DECLARE
  item JSONB;
  item_count INTEGER;
  distinct_item_count INTEGER;
  saved_sale working.sales%ROWTYPE;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can edit sales';
  END IF;
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'A sale group must retain at least one item';
  END IF;

  PERFORM 1 FROM working.sales
  WHERE customer_id = p_customer_id AND sale_date = p_sale_date
  ORDER BY id FOR UPDATE;

  IF EXISTS (
    SELECT 1 FROM working.sales
    WHERE customer_id = p_customer_id
      AND sale_date = p_sale_date
      AND billing_status <> 'unbilled'
  ) THEN
    RAISE EXCEPTION 'Billed sales cannot be edited';
  END IF;

  SELECT count(*), count(DISTINCT (value ->> 'fish_variety_id'))
  INTO item_count, distinct_item_count
  FROM jsonb_array_elements(p_items);
  IF item_count <> distinct_item_count THEN
    RAISE EXCEPTION 'Each item and grade can appear only once';
  END IF;

  DELETE FROM working.sales sale
  WHERE sale.customer_id = p_customer_id
    AND sale.sale_date = p_sale_date
    AND sale.billing_status = 'unbilled'
    AND NOT EXISTS (
      SELECT 1 FROM jsonb_array_elements(p_items) submitted
      WHERE (submitted ->> 'fish_variety_id')::BIGINT = sale.fish_variety_id
    );

  FOR item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    IF coalesce((item ->> 'quantity_crates')::INTEGER, 0) < 0
       OR coalesce((item ->> 'quantity_kg')::NUMERIC, 0) <= 0 THEN
      RAISE EXCEPTION 'Crates cannot be negative and actual kilograms must be greater than zero';
    END IF;

    INSERT INTO working.sales (
      customer_id, fish_variety_id, quantity_crates, quantity_kg, sale_date
    ) VALUES (
      p_customer_id,
      (item ->> 'fish_variety_id')::BIGINT,
      coalesce((item ->> 'quantity_crates')::INTEGER, 0),
      (item ->> 'quantity_kg')::NUMERIC,
      p_sale_date
    )
    ON CONFLICT (customer_id, fish_variety_id, sale_date)
    DO UPDATE SET
      quantity_crates = EXCLUDED.quantity_crates,
      quantity_kg = EXCLUDED.quantity_kg
    RETURNING * INTO saved_sale;

    RETURN NEXT saved_sale;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION working.get_stock_snapshot(p_as_of_date DATE DEFAULT current_date)
RETURNS TABLE (
  item_variant_id BIGINT,
  variant_name VARCHAR,
  opening_crates BIGINT,
  opening_kg NUMERIC,
  inward_crates BIGINT,
  inward_kg NUMERIC,
  outward_crates BIGINT,
  outward_kg NUMERIC,
  closing_crates BIGINT,
  closing_kg NUMERIC
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = working
AS $$
  SELECT
    variant.id,
    variant.name,
    coalesce(sum(movement.crates_delta) FILTER (WHERE movement.movement_date < p_as_of_date), 0)::BIGINT,
    coalesce(sum(movement.kg_delta) FILTER (WHERE movement.movement_date < p_as_of_date), 0),
    coalesce(sum(greatest(movement.crates_delta, 0)) FILTER (WHERE movement.movement_date = p_as_of_date), 0)::BIGINT,
    coalesce(sum(greatest(movement.kg_delta, 0)) FILTER (WHERE movement.movement_date = p_as_of_date), 0),
    coalesce(sum(abs(least(movement.crates_delta, 0))) FILTER (WHERE movement.movement_date = p_as_of_date), 0)::BIGINT,
    coalesce(sum(abs(least(movement.kg_delta, 0))) FILTER (WHERE movement.movement_date = p_as_of_date), 0),
    coalesce(sum(movement.crates_delta) FILTER (WHERE movement.movement_date <= p_as_of_date), 0)::BIGINT,
    coalesce(sum(movement.kg_delta) FILTER (WHERE movement.movement_date <= p_as_of_date), 0)
  FROM working.item_variants variant
  JOIN working.stock_movements movement ON movement.item_variant_id = variant.id AND movement.voided_at IS NULL
  GROUP BY variant.id, variant.name
  HAVING
    coalesce(sum(movement.crates_delta) FILTER (WHERE movement.movement_date <= p_as_of_date), 0) <> 0
    OR coalesce(sum(movement.kg_delta) FILTER (WHERE movement.movement_date <= p_as_of_date), 0) <> 0
    OR count(*) FILTER (WHERE movement.movement_date = p_as_of_date) > 0
  ORDER BY variant.name;
$$;

REVOKE ALL ON FUNCTION working.assert_stock_delta_available(BIGINT, BIGINT, INTEGER, NUMERIC) FROM PUBLIC;
REVOKE ALL ON FUNCTION working.sync_source_stock_movement() FROM PUBLIC;

REVOKE ALL ON FUNCTION working.record_stock_adjustment(BIGINT, DATE, VARCHAR, INTEGER, NUMERIC, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.record_stock_adjustment(BIGINT, DATE, VARCHAR, INTEGER, NUMERIC, TEXT, TEXT) TO authenticated;

REVOKE ALL ON FUNCTION working.reconcile_stock(BIGINT, DATE, INTEGER, NUMERIC, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.reconcile_stock(BIGINT, DATE, INTEGER, NUMERIC, TEXT, TEXT) TO authenticated;

REVOKE ALL ON FUNCTION working.void_stock_adjustment(BIGINT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.void_stock_adjustment(BIGINT, TEXT) TO authenticated;

REVOKE ALL ON FUNCTION working.get_stock_snapshot(DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.get_stock_snapshot(DATE) TO authenticated;

REVOKE ALL ON FUNCTION working.save_sales_batch(BIGINT, DATE, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.save_sales_batch(BIGINT, DATE, JSONB) TO authenticated;

REVOKE ALL ON FUNCTION working.update_sales_group(BIGINT, DATE, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.update_sales_group(BIGINT, DATE, JSONB) TO authenticated;

COMMENT ON TABLE working.stock_movements IS
  'Immutable inventory ledger. Source edits void prior movements and append replacements; manual corrections are voided, never deleted.';
