-- Auditable operating expenses for a configurable single-trader deployment.

CREATE TABLE working.expense_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE
    CHECK (code ~ '^[A-Z][A-Z0-9_-]{1,31}$'),
  name VARCHAR(80) NOT NULL CHECK (btrim(name) <> ''),
  sort_order SMALLINT NOT NULL DEFAULT 100 CHECK (sort_order >= 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_expense_category_normalized_name
  ON working.expense_categories (lower(regexp_replace(btrim(name), '\s+', ' ', 'g')));

CREATE TABLE working.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  category_id BIGINT NOT NULL REFERENCES working.expense_categories(id) ON DELETE RESTRICT,
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
  payment_method VARCHAR(20) NOT NULL DEFAULT 'cash'
    CHECK (payment_method IN ('cash', 'bank_transfer', 'upi', 'cheque', 'other')),
  payee VARCHAR(160),
  reference_number VARCHAR(120),
  notes TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  voided_at TIMESTAMPTZ,
  voided_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  void_reason TEXT,
  CHECK (
    (voided_at IS NULL AND voided_by IS NULL AND void_reason IS NULL)
    OR
    (voided_at IS NOT NULL AND void_reason IS NOT NULL AND btrim(void_reason) <> '')
  )
);

CREATE INDEX idx_expenses_active_date
  ON working.expenses (expense_date DESC, id DESC)
  WHERE voided_at IS NULL;

CREATE UNIQUE INDEX uq_expense_non_cash_reference
  ON working.expenses (payment_method, lower(btrim(reference_number)))
  WHERE reference_number IS NOT NULL AND voided_at IS NULL;

INSERT INTO working.expense_categories (code, name, sort_order)
VALUES
  ('TRANSPORT', 'Transport', 10),
  ('ICE', 'Ice', 20),
  ('LOADING', 'Loading & unloading', 30),
  ('LABOUR', 'Labour', 40),
  ('FUEL', 'Fuel', 50),
  ('SHOP', 'Shop expense', 60),
  ('FOOD', 'Food & refreshments', 70),
  ('OTHER', 'Other', 999);

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON working.expense_categories
FOR EACH ROW EXECUTE FUNCTION working.set_updated_at();

ALTER TABLE working.expense_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.expenses ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON working.expense_categories, working.expenses TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON working.expense_categories FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON working.expenses FROM authenticated;

CREATE POLICY admin_read_expense_categories ON working.expense_categories
FOR SELECT TO authenticated
USING (working.current_app_role() = 'admin');

CREATE POLICY admin_read_expenses ON working.expenses
FOR SELECT TO authenticated
USING (working.current_app_role() = 'admin');

CREATE OR REPLACE FUNCTION working.upsert_expense_category(
  p_category_id BIGINT,
  p_code TEXT,
  p_name TEXT,
  p_sort_order SMALLINT DEFAULT 100
)
RETURNS working.expense_categories
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  category_value working.expense_categories%ROWTYPE;
  code_value TEXT := upper(btrim(p_code));
  name_value TEXT := regexp_replace(btrim(p_name), '\s+', ' ', 'g');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can manage expense categories'
      USING ERRCODE = '42501';
  END IF;
  IF code_value !~ '^[A-Z][A-Z0-9_-]{1,31}$' THEN
    RAISE EXCEPTION 'Category code must contain 2-32 letters, numbers, underscores, or hyphens';
  END IF;
  IF name_value IS NULL OR name_value = '' THEN
    RAISE EXCEPTION 'Category name is required';
  END IF;

  IF p_category_id IS NULL THEN
    INSERT INTO working.expense_categories (code, name, sort_order)
    VALUES (code_value, name_value, coalesce(p_sort_order, 100))
    RETURNING * INTO category_value;
  ELSE
    UPDATE working.expense_categories
    SET code = code_value,
        name = name_value,
        sort_order = coalesce(p_sort_order, sort_order),
        is_active = TRUE
    WHERE id = p_category_id
    RETURNING * INTO category_value;

    IF NOT FOUND THEN RAISE EXCEPTION 'Expense category not found'; END IF;
  END IF;

  RETURN category_value;
END;
$$;

CREATE OR REPLACE FUNCTION working.archive_expense_category(p_category_id BIGINT)
RETURNS working.expense_categories
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  category_value working.expense_categories%ROWTYPE;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can manage expense categories'
      USING ERRCODE = '42501';
  END IF;

  UPDATE working.expense_categories
  SET is_active = FALSE
  WHERE id = p_category_id
  RETURNING * INTO category_value;

  IF NOT FOUND THEN RAISE EXCEPTION 'Expense category not found'; END IF;
  RETURN category_value;
END;
$$;

CREATE OR REPLACE FUNCTION working.record_expense(
  p_expense_date DATE,
  p_category_id BIGINT,
  p_amount NUMERIC,
  p_payment_method VARCHAR,
  p_payee TEXT DEFAULT NULL,
  p_reference_number TEXT DEFAULT NULL,
  p_notes TEXT DEFAULT NULL
)
RETURNS working.expenses
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  expense_value working.expenses%ROWTYPE;
  reference_value TEXT := nullif(btrim(p_reference_number), '');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can record expenses'
      USING ERRCODE = '42501';
  END IF;
  IF p_expense_date IS NULL OR p_expense_date > CURRENT_DATE THEN
    RAISE EXCEPTION 'Expense date cannot be in the future';
  END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Expense amount must be greater than zero';
  END IF;
  IF p_payment_method NOT IN ('cash', 'bank_transfer', 'upi', 'cheque', 'other') THEN
    RAISE EXCEPTION 'Invalid payment method';
  END IF;
  IF p_payment_method <> 'cash' AND reference_value IS NULL THEN
    RAISE EXCEPTION 'Reference number is required for non-cash expenses';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM working.expense_categories
    WHERE id = p_category_id AND is_active
  ) THEN
    RAISE EXCEPTION 'Select an active expense category';
  END IF;

  INSERT INTO working.expenses (
    expense_date, category_id, amount, payment_method,
    payee, reference_number, notes, created_by
  ) VALUES (
    p_expense_date, p_category_id, round(p_amount, 2), p_payment_method,
    nullif(btrim(p_payee), ''), reference_value,
    nullif(btrim(p_notes), ''), auth.uid()
  ) RETURNING * INTO expense_value;

  RETURN expense_value;
END;
$$;

CREATE OR REPLACE FUNCTION working.void_expense(
  p_expense_id BIGINT,
  p_void_reason TEXT
)
RETURNS working.expenses
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  expense_value working.expenses%ROWTYPE;
  reason_value TEXT := nullif(btrim(p_void_reason), '');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can void expenses'
      USING ERRCODE = '42501';
  END IF;
  IF reason_value IS NULL OR char_length(reason_value) < 3 THEN
    RAISE EXCEPTION 'Enter a clear reason to void this expense';
  END IF;

  SELECT * INTO expense_value
  FROM working.expenses
  WHERE id = p_expense_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Expense not found'; END IF;
  IF expense_value.voided_at IS NOT NULL THEN RAISE EXCEPTION 'Expense has already been voided'; END IF;

  UPDATE working.expenses
  SET voided_at = NOW(),
      voided_by = auth.uid(),
      void_reason = reason_value
  WHERE id = p_expense_id
  RETURNING * INTO expense_value;

  RETURN expense_value;
END;
$$;

UPDATE working.business_preferences
SET enabled_modules = enabled_modules || jsonb_build_object('expenses', TRUE)
WHERE id = 1 AND NOT (enabled_modules ? 'expenses');

REVOKE ALL ON FUNCTION working.upsert_expense_category(BIGINT, TEXT, TEXT, SMALLINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.upsert_expense_category(BIGINT, TEXT, TEXT, SMALLINT) TO authenticated;
REVOKE ALL ON FUNCTION working.archive_expense_category(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.archive_expense_category(BIGINT) TO authenticated;
REVOKE ALL ON FUNCTION working.record_expense(DATE, BIGINT, NUMERIC, VARCHAR, TEXT, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.record_expense(DATE, BIGINT, NUMERIC, VARCHAR, TEXT, TEXT, TEXT) TO authenticated;
REVOKE ALL ON FUNCTION working.void_expense(BIGINT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.void_expense(BIGINT, TEXT) TO authenticated;

COMMENT ON TABLE working.expenses IS
  'Immutable operating expense records. Corrections are voided with an audit reason.';
