BEGIN;

CREATE TABLE working.cash_adjustments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_date DATE NOT NULL DEFAULT CURRENT_DATE,
  direction VARCHAR(3) NOT NULL CHECK (direction IN ('in', 'out')),
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
  reason VARCHAR(180) NOT NULL CHECK (char_length(btrim(reason)) >= 3),
  reference_number VARCHAR(120),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  voided_at TIMESTAMPTZ,
  voided_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  void_reason TEXT,
  CHECK (
    (voided_at IS NULL AND voided_by IS NULL AND void_reason IS NULL)
    OR
    (voided_at IS NOT NULL AND void_reason IS NOT NULL AND btrim(void_reason) <> '')
  )
);

CREATE TABLE working.cash_day_closings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_date DATE NOT NULL,
  opening_cash NUMERIC(14,2) NOT NULL,
  cash_received NUMERIC(14,2) NOT NULL DEFAULT 0,
  cash_supplier_payments NUMERIC(14,2) NOT NULL DEFAULT 0,
  cash_expenses NUMERIC(14,2) NOT NULL DEFAULT 0,
  cash_adjustments_in NUMERIC(14,2) NOT NULL DEFAULT 0,
  cash_adjustments_out NUMERIC(14,2) NOT NULL DEFAULT 0,
  expected_closing_cash NUMERIC(14,2) NOT NULL,
  counted_cash NUMERIC(14,2) NOT NULL CHECK (counted_cash >= 0),
  difference NUMERIC(14,2) GENERATED ALWAYS AS (counted_cash - expected_closing_cash) STORED,
  notes TEXT,
  closed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  closed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  voided_at TIMESTAMPTZ,
  voided_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  void_reason TEXT,
  CHECK (
    (voided_at IS NULL AND voided_by IS NULL AND void_reason IS NULL)
    OR
    (voided_at IS NOT NULL AND void_reason IS NOT NULL AND btrim(void_reason) <> '')
  )
);

CREATE UNIQUE INDEX uq_active_cash_day_closing
  ON working.cash_day_closings (business_date)
  WHERE voided_at IS NULL;
CREATE INDEX idx_cash_adjustments_active_date
  ON working.cash_adjustments (business_date DESC, id DESC)
  WHERE voided_at IS NULL;
CREATE INDEX idx_cash_day_closings_date
  ON working.cash_day_closings (business_date DESC, id DESC);

ALTER TABLE working.cash_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.cash_day_closings ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON working.cash_adjustments, working.cash_day_closings TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON working.cash_adjustments, working.cash_day_closings FROM anon, authenticated;

CREATE POLICY admin_read_cash_adjustments ON working.cash_adjustments
FOR SELECT TO authenticated USING (working.current_app_role() = 'admin');
CREATE POLICY admin_read_cash_day_closings ON working.cash_day_closings
FOR SELECT TO authenticated USING (working.current_app_role() = 'admin');

CREATE OR REPLACE FUNCTION working.guard_closed_cash_day()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  target_date DATE;
  affects_cash BOOLEAN := TRUE;
BEGIN
  IF TG_NARGS > 1 THEN
    affects_cash := CASE
      WHEN TG_OP = 'INSERT' THEN to_jsonb(NEW) ->> TG_ARGV[1] = 'cash'
      WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ->> TG_ARGV[1] = 'cash'
      ELSE (to_jsonb(OLD) ->> TG_ARGV[1] = 'cash')
        OR (to_jsonb(NEW) ->> TG_ARGV[1] = 'cash')
    END;
  END IF;

  IF NOT affects_cash THEN
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
  END IF;

  target_date := CASE
    WHEN TG_OP = 'DELETE' THEN (to_jsonb(OLD) ->> TG_ARGV[0])::DATE
    ELSE (to_jsonb(NEW) ->> TG_ARGV[0])::DATE
  END;

  IF EXISTS (
    SELECT 1 FROM working.cash_day_closings
    WHERE business_date = target_date AND voided_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Cash day % is closed. Reopen it before changing cash transactions.', target_date
      USING ERRCODE = '55000';
  END IF;

  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER guard_closed_customer_cash
BEFORE INSERT OR UPDATE OR DELETE ON working.payments
FOR EACH ROW EXECUTE FUNCTION working.guard_closed_cash_day('payment_date', 'payment_method');
CREATE TRIGGER guard_closed_supplier_cash
BEFORE INSERT OR UPDATE OR DELETE ON working.purchase_bill_payments
FOR EACH ROW EXECUTE FUNCTION working.guard_closed_cash_day('payment_date', 'payment_mode');
CREATE TRIGGER guard_closed_expense_cash
BEFORE INSERT OR UPDATE OR DELETE ON working.expenses
FOR EACH ROW EXECUTE FUNCTION working.guard_closed_cash_day('expense_date', 'payment_method');
CREATE TRIGGER guard_closed_adjustment_cash
BEFORE INSERT OR UPDATE OR DELETE ON working.cash_adjustments
FOR EACH ROW EXECUTE FUNCTION working.guard_closed_cash_day('business_date');

CREATE OR REPLACE FUNCTION working.get_cashbook_day(p_business_date DATE)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  opening_value NUMERIC(14,2) := 0;
  received_value NUMERIC(14,2) := 0;
  supplier_value NUMERIC(14,2) := 0;
  expense_value NUMERIC(14,2) := 0;
  adjustment_in_value NUMERIC(14,2) := 0;
  adjustment_out_value NUMERIC(14,2) := 0;
  expected_value NUMERIC(14,2);
  closing_value working.cash_day_closings%ROWTYPE;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can view the cashbook' USING ERRCODE = '42501';
  END IF;
  IF p_business_date IS NULL THEN RAISE EXCEPTION 'Business date is required'; END IF;

  SELECT counted_cash INTO opening_value
  FROM working.cash_day_closings
  WHERE business_date < p_business_date AND voided_at IS NULL
  ORDER BY business_date DESC, id DESC
  LIMIT 1;
  opening_value := coalesce(opening_value, 0);

  SELECT coalesce(sum(amount), 0) INTO received_value
  FROM working.payments
  WHERE payment_date = p_business_date AND payment_method = 'cash' AND voided_at IS NULL;

  SELECT coalesce(sum(amount), 0) INTO supplier_value
  FROM working.purchase_bill_payments
  WHERE payment_date = p_business_date AND payment_mode = 'cash' AND voided_at IS NULL;

  SELECT coalesce(sum(amount), 0) INTO expense_value
  FROM working.expenses
  WHERE expense_date = p_business_date AND payment_method = 'cash' AND voided_at IS NULL;

  SELECT
    coalesce(sum(amount) FILTER (WHERE direction = 'in'), 0),
    coalesce(sum(amount) FILTER (WHERE direction = 'out'), 0)
  INTO adjustment_in_value, adjustment_out_value
  FROM working.cash_adjustments
  WHERE business_date = p_business_date AND voided_at IS NULL;

  expected_value := opening_value + received_value + adjustment_in_value
    - supplier_value - expense_value - adjustment_out_value;

  SELECT * INTO closing_value
  FROM working.cash_day_closings
  WHERE business_date = p_business_date AND voided_at IS NULL
  ORDER BY id DESC LIMIT 1;

  RETURN jsonb_build_object(
    'business_date', p_business_date,
    'opening_cash', opening_value,
    'cash_received', received_value,
    'cash_supplier_payments', supplier_value,
    'cash_expenses', expense_value,
    'cash_adjustments_in', adjustment_in_value,
    'cash_adjustments_out', adjustment_out_value,
    'expected_closing_cash', expected_value,
    'is_closed', closing_value.id IS NOT NULL,
    'closing', CASE WHEN closing_value.id IS NULL THEN NULL ELSE to_jsonb(closing_value) END
  );
END;
$$;

CREATE OR REPLACE FUNCTION working.record_cash_adjustment(
  p_business_date DATE,
  p_direction VARCHAR,
  p_amount NUMERIC,
  p_reason TEXT,
  p_reference_number TEXT DEFAULT NULL
)
RETURNS working.cash_adjustments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  adjustment_value working.cash_adjustments%ROWTYPE;
  reason_value TEXT := regexp_replace(btrim(p_reason), '\s+', ' ', 'g');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can record cash adjustments' USING ERRCODE = '42501';
  END IF;
  IF p_business_date IS NULL OR p_business_date > CURRENT_DATE THEN
    RAISE EXCEPTION 'Adjustment date cannot be in the future';
  END IF;
  IF p_direction NOT IN ('in', 'out') THEN RAISE EXCEPTION 'Select cash in or cash out'; END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Amount must be greater than zero'; END IF;
  IF reason_value IS NULL OR char_length(reason_value) < 3 THEN
    RAISE EXCEPTION 'Enter a clear reason for the adjustment';
  END IF;

  INSERT INTO working.cash_adjustments (
    business_date, direction, amount, reason, reference_number, created_by
  ) VALUES (
    p_business_date, p_direction, round(p_amount, 2), reason_value,
    nullif(btrim(p_reference_number), ''), auth.uid()
  ) RETURNING * INTO adjustment_value;
  RETURN adjustment_value;
END;
$$;

CREATE OR REPLACE FUNCTION working.void_cash_adjustment(p_adjustment_id BIGINT, p_void_reason TEXT)
RETURNS working.cash_adjustments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  adjustment_value working.cash_adjustments%ROWTYPE;
  reason_value TEXT := nullif(btrim(p_void_reason), '');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can void cash adjustments' USING ERRCODE = '42501';
  END IF;
  IF reason_value IS NULL OR char_length(reason_value) < 3 THEN
    RAISE EXCEPTION 'Enter a clear reason to void this adjustment';
  END IF;

  SELECT * INTO adjustment_value FROM working.cash_adjustments
  WHERE id = p_adjustment_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Cash adjustment not found'; END IF;
  IF adjustment_value.voided_at IS NOT NULL THEN RAISE EXCEPTION 'Adjustment is already voided'; END IF;

  UPDATE working.cash_adjustments
  SET voided_at = NOW(), voided_by = auth.uid(), void_reason = reason_value
  WHERE id = p_adjustment_id
  RETURNING * INTO adjustment_value;
  RETURN adjustment_value;
END;
$$;

CREATE OR REPLACE FUNCTION working.close_cash_day(
  p_business_date DATE,
  p_counted_cash NUMERIC,
  p_notes TEXT DEFAULT NULL
)
RETURNS working.cash_day_closings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  summary_value JSONB;
  closing_value working.cash_day_closings%ROWTYPE;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can close a cash day' USING ERRCODE = '42501';
  END IF;
  IF p_business_date IS NULL OR p_business_date > CURRENT_DATE THEN
    RAISE EXCEPTION 'Cash day cannot be in the future';
  END IF;
  IF p_counted_cash IS NULL OR p_counted_cash < 0 THEN
    RAISE EXCEPTION 'Counted cash cannot be negative';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended('working-cash-day:' || p_business_date::TEXT, 0));
  IF EXISTS (
    SELECT 1 FROM working.cash_day_closings
    WHERE business_date = p_business_date AND voided_at IS NULL
  ) THEN RAISE EXCEPTION 'Cash day is already closed'; END IF;
  IF EXISTS (
    SELECT 1 FROM working.cash_day_closings
    WHERE business_date > p_business_date AND voided_at IS NULL
  ) THEN
    RAISE EXCEPTION 'A later cash day is already closed. Close days in chronological order.';
  END IF;

  summary_value := working.get_cashbook_day(p_business_date);
  INSERT INTO working.cash_day_closings (
    business_date, opening_cash, cash_received, cash_supplier_payments,
    cash_expenses, cash_adjustments_in, cash_adjustments_out,
    expected_closing_cash, counted_cash, notes, closed_by
  ) VALUES (
    p_business_date,
    (summary_value ->> 'opening_cash')::NUMERIC,
    (summary_value ->> 'cash_received')::NUMERIC,
    (summary_value ->> 'cash_supplier_payments')::NUMERIC,
    (summary_value ->> 'cash_expenses')::NUMERIC,
    (summary_value ->> 'cash_adjustments_in')::NUMERIC,
    (summary_value ->> 'cash_adjustments_out')::NUMERIC,
    (summary_value ->> 'expected_closing_cash')::NUMERIC,
    round(p_counted_cash, 2), nullif(btrim(p_notes), ''), auth.uid()
  ) RETURNING * INTO closing_value;
  RETURN closing_value;
END;
$$;

CREATE OR REPLACE FUNCTION working.reopen_cash_day(p_closing_id BIGINT, p_reason TEXT)
RETURNS working.cash_day_closings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  closing_value working.cash_day_closings%ROWTYPE;
  reason_value TEXT := nullif(btrim(p_reason), '');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can reopen a cash day' USING ERRCODE = '42501';
  END IF;
  IF reason_value IS NULL OR char_length(reason_value) < 3 THEN
    RAISE EXCEPTION 'Enter a clear reason to reopen the day';
  END IF;

  SELECT * INTO closing_value FROM working.cash_day_closings
  WHERE id = p_closing_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Cash closing not found'; END IF;
  IF closing_value.voided_at IS NOT NULL THEN RAISE EXCEPTION 'Cash day is already reopened'; END IF;
  IF EXISTS (
    SELECT 1 FROM working.cash_day_closings
    WHERE business_date > closing_value.business_date AND voided_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Reopen later cash days first to preserve the opening-balance chain';
  END IF;

  UPDATE working.cash_day_closings
  SET voided_at = NOW(), voided_by = auth.uid(), void_reason = reason_value
  WHERE id = p_closing_id
  RETURNING * INTO closing_value;
  RETURN closing_value;
END;
$$;

CREATE VIEW working.cashbook_entries
WITH (security_invoker = TRUE)
AS
SELECT
  'customer_receipt'::TEXT AS entry_type,
  p.id AS source_id,
  p.payment_date AS business_date,
  'in'::TEXT AS direction,
  p.amount,
  c.name::TEXT AS label,
  'Customer receipt'::TEXT AS detail,
  p.reference_number::TEXT,
  p.created_at AS occurred_at,
  p.voided_at,
  p.void_reason
FROM working.payments p
JOIN working.customers c ON c.id = p.customer_id
WHERE p.payment_method = 'cash'
UNION ALL
SELECT
  'supplier_payment', pp.id, pp.payment_date, 'out', pp.amount,
  s.name, 'Supplier payment', pp.reference_number, pp.created_at,
  pp.voided_at, pp.void_reason
FROM working.purchase_bill_payments pp
JOIN working.purchase_bills pb ON pb.id = pp.purchase_bill_id
JOIN working.suppliers s ON s.id = pb.supplier_id
WHERE pp.payment_mode = 'cash'
UNION ALL
SELECT
  'expense', e.id, e.expense_date, 'out', e.amount,
  ec.name, 'Operating expense', e.reference_number, e.created_at,
  e.voided_at, e.void_reason
FROM working.expenses e
JOIN working.expense_categories ec ON ec.id = e.category_id
WHERE e.payment_method = 'cash'
UNION ALL
SELECT
  'adjustment', a.id, a.business_date, a.direction, a.amount,
  a.reason, 'Cash adjustment', a.reference_number, a.created_at,
  a.voided_at, a.void_reason
FROM working.cash_adjustments a;

GRANT SELECT ON working.cashbook_entries TO authenticated;

UPDATE working.business_preferences
SET enabled_modules = enabled_modules || jsonb_build_object('cashbook', TRUE)
WHERE id = 1 AND NOT (enabled_modules ? 'cashbook');

REVOKE ALL ON FUNCTION working.guard_closed_cash_day() FROM PUBLIC;
REVOKE ALL ON FUNCTION working.get_cashbook_day(DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.get_cashbook_day(DATE) TO authenticated;
REVOKE ALL ON FUNCTION working.record_cash_adjustment(DATE, VARCHAR, NUMERIC, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.record_cash_adjustment(DATE, VARCHAR, NUMERIC, TEXT, TEXT) TO authenticated;
REVOKE ALL ON FUNCTION working.void_cash_adjustment(BIGINT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.void_cash_adjustment(BIGINT, TEXT) TO authenticated;
REVOKE ALL ON FUNCTION working.close_cash_day(DATE, NUMERIC, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.close_cash_day(DATE, NUMERIC, TEXT) TO authenticated;
REVOKE ALL ON FUNCTION working.reopen_cash_day(BIGINT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.reopen_cash_day(BIGINT, TEXT) TO authenticated;

COMMENT ON TABLE working.cash_day_closings IS
  'Immutable daily cash snapshots. Reopening voids a snapshot while preserving its audit history.';
COMMENT ON VIEW working.cashbook_entries IS
  'Unified cash-only ledger sourced from customer receipts, supplier payments, expenses, and adjustments.';

COMMIT;
