BEGIN;

CREATE TABLE working.inventory_costing_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  costing_method VARCHAR(32) NOT NULL DEFAULT 'weighted_average'
    CHECK (costing_method = 'weighted_average'),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  source_purchase_count INTEGER NOT NULL DEFAULT 0,
  source_sale_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE working.inventory_cost_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES working.inventory_costing_runs(id) ON DELETE CASCADE,
  event_type VARCHAR(12) NOT NULL CHECK (event_type IN ('purchase', 'sale')),
  source_id BIGINT NOT NULL,
  event_date DATE NOT NULL,
  item_variant_id BIGINT NOT NULL REFERENCES working.item_variants(id) ON DELETE RESTRICT,
  item_name VARCHAR(255) NOT NULL,
  counterparty_name VARCHAR(255),
  quantity_kg NUMERIC(14,2) NOT NULL CHECK (quantity_kg > 0),
  unit_cost NUMERIC(16,6),
  total_cost NUMERIC(16,2),
  revenue NUMERIC(16,2),
  gross_profit NUMERIC(16,2),
  cost_status VARCHAR(32) NOT NULL CHECK (cost_status IN (
    'costed', 'missing_purchase_bill', 'missing_purchase_cost', 'insufficient_stock'
  )),
  revenue_status VARCHAR(20) NOT NULL CHECK (revenue_status IN (
    'not_applicable', 'billed', 'unbilled', 'missing_rate'
  )),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (run_id, event_type, source_id)
);

CREATE INDEX idx_inventory_cost_events_run_date
  ON working.inventory_cost_events (run_id, event_date, event_type, source_id);
CREATE INDEX idx_inventory_cost_events_run_variant
  ON working.inventory_cost_events (run_id, item_variant_id, event_date);

ALTER TABLE working.inventory_costing_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.inventory_cost_events ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON working.inventory_costing_runs, working.inventory_cost_events TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON working.inventory_costing_runs, working.inventory_cost_events FROM anon, authenticated;

CREATE POLICY admin_read_inventory_costing_runs ON working.inventory_costing_runs
FOR SELECT TO authenticated USING (working.current_app_role() = 'admin');
CREATE POLICY admin_read_inventory_cost_events ON working.inventory_cost_events
FOR SELECT TO authenticated USING (working.current_app_role() = 'admin');

CREATE VIEW working.purchase_cost_sources
WITH (security_invoker = TRUE)
AS
WITH source_rows AS (
  SELECT
    p.id AS source_id,
    p.purchase_date AS event_date,
    p.fish_variety_id AS item_variant_id,
    iv.name::VARCHAR(255) AS item_name,
    s.name::VARCHAR(255) AS counterparty_name,
    COALESCE(
      pbi.actual_weight,
      p.quantity_crates * COALESCE(i.default_kg_per_crate, bp.default_crate_weight_kg)
        + p.quantity_kg
    )::NUMERIC(14,2) AS quantity_kg,
    pbi.amount AS base_cost,
    pb.id AS purchase_bill_id,
    pb.subtotal AS bill_items_total,
    pb.commission_amount,
    COALESCE((
      SELECT SUM((entry ->> 'amount')::NUMERIC)
      FROM jsonb_array_elements(pb.other_deductions) entry
      WHERE entry ->> 'type' = 'other_charges_addition'
    ), 0) AS addition_total,
    COALESCE((
      SELECT SUM((entry ->> 'amount')::NUMERIC)
      FROM jsonb_array_elements(pb.other_deductions) entry
      WHERE entry ->> 'type' = 'other_charges_deduction'
    ), 0) AS deduction_total,
    SUM(pbi.actual_weight) OVER (PARTITION BY pb.id) AS bill_weight_total
  FROM working.purchases p
  JOIN working.item_variants iv ON iv.id = p.fish_variety_id
  JOIN working.items i ON i.id = iv.item_id
  JOIN working.business_preferences bp ON bp.id = 1
  LEFT JOIN working.suppliers s ON s.id = p.supplier_id
  LEFT JOIN working.purchase_bill_items pbi ON pbi.purchase_id = p.id
  LEFT JOIN working.purchase_bills pb ON pb.id = pbi.purchase_bill_id
)
SELECT
  source_id, event_date, item_variant_id, item_name, counterparty_name, quantity_kg,
  CASE WHEN purchase_bill_id IS NULL THEN NULL ELSE ROUND(
    base_cost + (commission_amount + addition_total - deduction_total) *
      CASE
        WHEN bill_items_total > 0 THEN base_cost / bill_items_total
        WHEN bill_weight_total > 0 THEN quantity_kg / bill_weight_total
        ELSE 0
      END,
    2
  ) END AS landed_cost,
  CASE WHEN purchase_bill_id IS NULL THEN 'missing_purchase_bill' ELSE 'costed' END::TEXT AS source_status
FROM source_rows;

CREATE VIEW working.sale_revenue_sources
WITH (security_invoker = TRUE)
AS
WITH bill_item_context AS (
  SELECT
    bi.*,
    (bi.quantity_crates * bi.crate_weight + bi.quantity_kg)::NUMERIC AS item_weight,
    ROUND((bi.quantity_crates * bi.crate_weight + bi.quantity_kg) * bi.rate_per_kg, 2) AS corrected_base_revenue,
    SUM(ROUND((bi.quantity_crates * bi.crate_weight + bi.quantity_kg) * bi.rate_per_kg, 2))
      OVER (PARTITION BY bi.bill_id) AS bill_item_revenue,
    SUM((bi.quantity_crates * bi.crate_weight + bi.quantity_kg))
      OVER (PARTITION BY bi.bill_id) AS bill_item_weight,
    COALESCE((SELECT SUM(c.amount) FROM working.bill_other_charges c WHERE c.bill_id = bi.bill_id), 0) AS bill_charges,
    b.discount,
    b.customer_id
  FROM working.bill_items bi
  JOIN working.bills b ON b.id = bi.bill_id
), linked_sales AS (
  SELECT
    context.*,
    link.sale_id,
    sale.quantity_crates * context.crate_weight + sale.quantity_kg AS sale_weight,
    SUM(sale.quantity_crates * context.crate_weight + sale.quantity_kg)
      OVER (PARTITION BY context.id) AS linked_weight
  FROM bill_item_context context
  JOIN working.bill_item_sales link ON link.bill_item_id = context.id
  JOIN working.sales sale ON sale.id = link.sale_id
)
SELECT
  sale.id AS source_id,
  sale.sale_date AS event_date,
  sale.fish_variety_id AS item_variant_id,
  variant.name::VARCHAR(255) AS item_name,
  customer.name::VARCHAR(255) AS counterparty_name,
  COALESCE(
    linked.sale_weight,
    sale.quantity_crates * COALESCE(item.default_kg_per_crate, preferences.default_crate_weight_kg)
      + sale.quantity_kg
  )::NUMERIC(14,2) AS quantity_kg,
  CASE WHEN linked.sale_id IS NULL THEN NULL ELSE ROUND(
    (
      linked.corrected_base_revenue
      + (linked.bill_charges - linked.discount) *
        CASE
          WHEN linked.bill_item_revenue > 0 THEN linked.corrected_base_revenue / linked.bill_item_revenue
          WHEN linked.bill_item_weight > 0 THEN linked.item_weight / linked.bill_item_weight
          ELSE 0
        END
    ) * CASE WHEN linked.linked_weight > 0 THEN linked.sale_weight / linked.linked_weight ELSE 0 END,
    2
  ) END AS revenue,
  CASE
    WHEN linked.sale_id IS NULL THEN 'unbilled'
    WHEN linked.rate_per_kg <= 0 THEN 'missing_rate'
    ELSE 'billed'
  END::TEXT AS revenue_status
FROM working.sales sale
JOIN working.item_variants variant ON variant.id = sale.fish_variety_id
JOIN working.items item ON item.id = variant.item_id
JOIN working.customers customer ON customer.id = sale.customer_id
JOIN working.business_preferences preferences ON preferences.id = 1
LEFT JOIN linked_sales linked ON linked.sale_id = sale.id;

GRANT SELECT ON working.purchase_cost_sources, working.sale_revenue_sources TO authenticated;

CREATE OR REPLACE FUNCTION working.refresh_inventory_costing()
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  run_value working.inventory_costing_runs%ROWTYPE;
  event_value RECORD;
  known_qty NUMERIC(18,6);
  known_cost NUMERIC(18,6);
  unknown_qty NUMERIC(18,6);
  available_qty NUMERIC(18,6);
  average_cost NUMERIC(18,6);
  known_consumed NUMERIC(18,6);
  event_cost NUMERIC(18,2);
  event_cost_status TEXT;
  event_profit NUMERIC(18,2);
  actor_id UUID := auth.uid();
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can refresh inventory costing' USING ERRCODE = '42501';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('working-inventory-costing', 0));
  IF actor_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users WHERE id = actor_id) THEN actor_id := NULL; END IF;

  INSERT INTO working.inventory_costing_runs (created_by, source_purchase_count, source_sale_count)
  VALUES (
    actor_id,
    (SELECT count(*) FROM working.purchase_cost_sources),
    (SELECT count(*) FROM working.sale_revenue_sources)
  ) RETURNING * INTO run_value;

  CREATE TEMP TABLE costing_state (
    item_variant_id BIGINT PRIMARY KEY,
    known_qty NUMERIC(18,6) NOT NULL DEFAULT 0,
    known_cost NUMERIC(18,6) NOT NULL DEFAULT 0,
    unknown_qty NUMERIC(18,6) NOT NULL DEFAULT 0
  ) ON COMMIT DROP;

  FOR event_value IN
    SELECT * FROM (
      SELECT
        'purchase'::TEXT AS event_type, source_id, event_date, item_variant_id,
        item_name, counterparty_name, quantity_kg, landed_cost AS source_cost,
        NULL::NUMERIC AS source_revenue, source_status, 'not_applicable'::TEXT AS revenue_status,
        0 AS event_order
      FROM working.purchase_cost_sources
      UNION ALL
      SELECT
        'sale', source_id, event_date, item_variant_id,
        item_name, counterparty_name, quantity_kg, NULL,
        revenue, NULL, revenue_status, 1
      FROM working.sale_revenue_sources
    ) event_stream
    ORDER BY event_date, event_order, source_id
  LOOP
    INSERT INTO costing_state (item_variant_id) VALUES (event_value.item_variant_id)
    ON CONFLICT (item_variant_id) DO NOTHING;
    SELECT state.known_qty, state.known_cost, state.unknown_qty
    INTO known_qty, known_cost, unknown_qty
    FROM costing_state state WHERE state.item_variant_id = event_value.item_variant_id FOR UPDATE;

    IF event_value.event_type = 'purchase' THEN
      IF event_value.source_cost IS NULL THEN
        unknown_qty := unknown_qty + event_value.quantity_kg;
      ELSE
        known_qty := known_qty + event_value.quantity_kg;
        known_cost := known_cost + event_value.source_cost;
      END IF;
      UPDATE costing_state SET known_qty = known_qty, known_cost = known_cost, unknown_qty = unknown_qty
      WHERE item_variant_id = event_value.item_variant_id;

      INSERT INTO working.inventory_cost_events (
        run_id, event_type, source_id, event_date, item_variant_id, item_name,
        counterparty_name, quantity_kg, unit_cost, total_cost, revenue,
        gross_profit, cost_status, revenue_status
      ) VALUES (
        run_value.id, 'purchase', event_value.source_id, event_value.event_date,
        event_value.item_variant_id, event_value.item_name, event_value.counterparty_name,
        event_value.quantity_kg,
        CASE WHEN event_value.source_cost IS NULL THEN NULL ELSE event_value.source_cost / event_value.quantity_kg END,
        event_value.source_cost, NULL, NULL, event_value.source_status, 'not_applicable'
      );
    ELSE
      available_qty := known_qty + unknown_qty;
      average_cost := CASE WHEN known_qty > 0 THEN known_cost / known_qty ELSE NULL END;
      event_cost := NULL;

      IF event_value.quantity_kg > available_qty OR available_qty <= 0 THEN
        event_cost_status := 'insufficient_stock';
        known_qty := 0; known_cost := 0; unknown_qty := 0;
      ELSIF unknown_qty > 0 THEN
        event_cost_status := 'missing_purchase_cost';
        known_consumed := event_value.quantity_kg * known_qty / available_qty;
        IF average_cost IS NOT NULL THEN known_cost := GREATEST(0, known_cost - known_consumed * average_cost); END IF;
        known_qty := GREATEST(0, known_qty - known_consumed);
        unknown_qty := GREATEST(0, unknown_qty - (event_value.quantity_kg - known_consumed));
      ELSE
        event_cost_status := 'costed';
        event_cost := ROUND(event_value.quantity_kg * average_cost, 2);
        known_qty := GREATEST(0, known_qty - event_value.quantity_kg);
        known_cost := GREATEST(0, known_cost - event_cost);
      END IF;

      event_profit := CASE
        WHEN event_cost_status = 'costed' AND event_value.revenue_status = 'billed'
          THEN event_value.source_revenue - event_cost
        ELSE NULL
      END;
      UPDATE costing_state SET known_qty = known_qty, known_cost = known_cost, unknown_qty = unknown_qty
      WHERE item_variant_id = event_value.item_variant_id;

      INSERT INTO working.inventory_cost_events (
        run_id, event_type, source_id, event_date, item_variant_id, item_name,
        counterparty_name, quantity_kg, unit_cost, total_cost, revenue,
        gross_profit, cost_status, revenue_status
      ) VALUES (
        run_value.id, 'sale', event_value.source_id, event_value.event_date,
        event_value.item_variant_id, event_value.item_name, event_value.counterparty_name,
        event_value.quantity_kg,
        CASE WHEN event_cost IS NULL THEN NULL ELSE event_cost / event_value.quantity_kg END,
        event_cost, event_value.source_revenue, event_profit,
        event_cost_status, event_value.revenue_status
      );
    END IF;
  END LOOP;

  UPDATE working.inventory_costing_runs SET completed_at = NOW() WHERE id = run_value.id;
  RETURN run_value.id;
END;
$$;

CREATE OR REPLACE FUNCTION working.get_profitability_report(p_date_from DATE, p_date_to DATE)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  run_id_value BIGINT;
  report_value JSONB;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can view profitability' USING ERRCODE = '42501';
  END IF;
  IF p_date_from IS NULL OR p_date_to IS NULL OR p_date_from > p_date_to THEN
    RAISE EXCEPTION 'Select a valid profitability date range';
  END IF;
  IF p_date_to > CURRENT_DATE THEN RAISE EXCEPTION 'Profitability cannot include future dates'; END IF;

  run_id_value := working.refresh_inventory_costing();

  WITH sale_events AS (
    SELECT * FROM working.inventory_cost_events
    WHERE run_id = run_id_value AND event_type = 'sale'
      AND event_date BETWEEN p_date_from AND p_date_to
  ), expense_total AS (
    SELECT coalesce(sum(amount), 0)::NUMERIC AS value
    FROM working.expenses
    WHERE expense_date BETWEEN p_date_from AND p_date_to AND voided_at IS NULL
  ), totals AS (
    SELECT
      coalesce(sum(revenue) FILTER (WHERE revenue_status = 'billed'), 0) AS revenue,
      coalesce(sum(total_cost) FILTER (WHERE cost_status = 'costed'), 0) AS cogs,
      coalesce(sum(gross_profit), 0) AS recognized_gross_profit,
      count(*) AS sale_count,
      count(*) FILTER (WHERE cost_status = 'costed' AND revenue_status = 'billed') AS complete_sale_count,
      count(*) FILTER (WHERE cost_status <> 'costed' OR revenue_status <> 'billed') AS unresolved_sale_count,
      coalesce(sum(quantity_kg), 0) AS total_sale_weight,
      coalesce(sum(quantity_kg) FILTER (WHERE cost_status = 'costed' AND revenue_status = 'billed'), 0) AS complete_sale_weight
    FROM sale_events
  ), item_rows AS (
    SELECT coalesce(jsonb_agg(to_jsonb(item_data) ORDER BY item_data.revenue DESC), '[]'::JSONB) AS value
    FROM (
      SELECT item_variant_id, item_name,
        round(coalesce(sum(revenue) FILTER (WHERE revenue_status = 'billed'), 0), 2) AS revenue,
        round(coalesce(sum(total_cost) FILTER (WHERE cost_status = 'costed'), 0), 2) AS cogs,
        round(coalesce(sum(gross_profit), 0), 2) AS gross_profit,
        count(*) AS sale_count,
        count(*) FILTER (WHERE cost_status <> 'costed' OR revenue_status <> 'billed') AS unresolved_count
      FROM sale_events GROUP BY item_variant_id, item_name
    ) item_data
  ), day_rows AS (
    SELECT coalesce(jsonb_agg(to_jsonb(day_data) ORDER BY day_data.business_date), '[]'::JSONB) AS value
    FROM (
      SELECT event_date AS business_date,
        round(coalesce(sum(revenue) FILTER (WHERE revenue_status = 'billed'), 0), 2) AS revenue,
        round(coalesce(sum(total_cost) FILTER (WHERE cost_status = 'costed'), 0), 2) AS cogs,
        round(coalesce(sum(gross_profit), 0), 2) AS gross_profit,
        count(*) FILTER (WHERE cost_status <> 'costed' OR revenue_status <> 'billed') AS unresolved_count
      FROM sale_events GROUP BY event_date
    ) day_data
  )
  SELECT jsonb_build_object(
    'run_id', run_id_value,
    'costing_method', 'weighted_average',
    'date_from', p_date_from,
    'date_to', p_date_to,
    'revenue', round(totals.revenue, 2),
    'cogs', round(totals.cogs, 2),
    'gross_profit', round(totals.recognized_gross_profit, 2),
    'operating_expenses', round(expense_total.value, 2),
    'net_profit', round(totals.recognized_gross_profit - expense_total.value, 2),
    'sale_count', totals.sale_count,
    'complete_sale_count', totals.complete_sale_count,
    'unresolved_sale_count', totals.unresolved_sale_count,
    'coverage_percent', CASE WHEN totals.total_sale_weight > 0
      THEN round(totals.complete_sale_weight / totals.total_sale_weight * 100, 1) ELSE 100 END,
    'is_complete', totals.unresolved_sale_count = 0,
    'items', item_rows.value,
    'days', day_rows.value
  ) INTO report_value
  FROM totals, expense_total, item_rows, day_rows;

  RETURN report_value;
END;
$$;

UPDATE working.business_preferences
SET enabled_modules = enabled_modules || jsonb_build_object('profitability', TRUE)
WHERE id = 1 AND NOT (enabled_modules ? 'profitability');

REVOKE ALL ON FUNCTION working.refresh_inventory_costing() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.refresh_inventory_costing() TO authenticated;
REVOKE ALL ON FUNCTION working.get_profitability_report(DATE, DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.get_profitability_report(DATE, DATE) TO authenticated;

COMMENT ON TABLE working.inventory_costing_runs IS
  'Immutable weighted-average costing snapshots. Each refresh preserves the prior calculation run.';
COMMENT ON COLUMN working.inventory_cost_events.gross_profit IS
  'Recognized only when both weighted-average cost and billed sales revenue are complete.';

COMMIT;
