BEGIN;

CREATE TABLE working.bill_corrections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type TEXT NOT NULL CHECK (document_type IN ('customer_bill', 'purchase_bill')),
  correction_action TEXT NOT NULL CHECK (correction_action IN ('revised', 'released_for_rebill')),
  original_bill_id BIGINT NOT NULL,
  original_bill_number TEXT NOT NULL,
  counterparty_id BIGINT NOT NULL,
  counterparty_name TEXT NOT NULL,
  bill_date DATE NOT NULL,
  reason TEXT NOT NULL CHECK (char_length(btrim(reason)) >= 5),
  original_snapshot JSONB NOT NULL,
  replacement_bill_id BIGINT,
  replacement_bill_number TEXT,
  corrected_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  corrected_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_bill_corrections_document
  ON working.bill_corrections(document_type, original_bill_id, corrected_at DESC);
CREATE INDEX idx_bill_corrections_counterparty
  ON working.bill_corrections(document_type, counterparty_id, corrected_at DESC);

ALTER TABLE working.bill_corrections ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON working.bill_corrections TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON working.bill_corrections FROM anon, authenticated;

CREATE POLICY admin_read_bill_corrections ON working.bill_corrections
FOR SELECT TO authenticated
USING (working.current_app_role() = 'admin');

CREATE OR REPLACE FUNCTION working.guard_finalized_bill_deletion()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  expected_context TEXT := TG_TABLE_NAME || ':' || OLD.id::TEXT;
BEGIN
  IF current_setting('working.bill_correction_context', TRUE) IS DISTINCT FROM expected_context THEN
    RAISE EXCEPTION 'Finalized bills cannot be deleted directly. Use the controlled correction action.'
      USING ERRCODE = '55000';
  END IF;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS guard_finalized_customer_bill_deletion ON working.bills;
CREATE TRIGGER guard_finalized_customer_bill_deletion
BEFORE DELETE ON working.bills
FOR EACH ROW EXECUTE FUNCTION working.guard_finalized_bill_deletion();

DROP TRIGGER IF EXISTS guard_finalized_purchase_bill_deletion ON working.purchase_bills;
CREATE TRIGGER guard_finalized_purchase_bill_deletion
BEFORE DELETE ON working.purchase_bills
FOR EACH ROW EXECUTE FUNCTION working.guard_finalized_bill_deletion();

CREATE OR REPLACE FUNCTION working.release_customer_bill_for_correction(
  p_bill_id BIGINT,
  p_reason TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  target_bill working.bills%ROWTYPE;
  customer_name_value TEXT;
  correction_id_value BIGINT;
  reason_value TEXT := regexp_replace(btrim(coalesce(p_reason, '')), '[[:space:]]+', ' ', 'g');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can correct customer bills' USING ERRCODE = '42501';
  END IF;
  IF char_length(reason_value) < 5 THEN
    RAISE EXCEPTION 'Enter a correction reason of at least 5 characters';
  END IF;

  SELECT bill.*
  INTO target_bill
  FROM working.bills bill
  WHERE bill.id = p_bill_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Customer bill not found'; END IF;
  SELECT name INTO customer_name_value
  FROM working.customers WHERE id = target_bill.customer_id;
  IF target_bill.is_active IS NOT TRUE THEN
    RAISE EXCEPTION 'Only the latest customer bill can be corrected because later bills carry its balance';
  END IF;
  IF EXISTS (
    SELECT 1 FROM working.payments
    WHERE bill_id = p_bill_id AND voided_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Void active receipts linked to this bill before correcting it';
  END IF;

  INSERT INTO working.bill_corrections (
    document_type, correction_action, original_bill_id, original_bill_number,
    counterparty_id, counterparty_name, bill_date, reason, original_snapshot, corrected_by
  ) VALUES (
    'customer_bill', 'released_for_rebill', target_bill.id, target_bill.bill_number,
    target_bill.customer_id, customer_name_value, target_bill.bill_date, reason_value,
    jsonb_build_object(
      'bill', to_jsonb(target_bill),
      'items', coalesce((
        SELECT jsonb_agg(to_jsonb(item) ORDER BY item.id)
        FROM working.bill_items item WHERE item.bill_id = target_bill.id
      ), '[]'::JSONB),
      'sale_links', coalesce((
        SELECT jsonb_agg(to_jsonb(link) ORDER BY link.bill_item_id, link.sale_id)
        FROM working.bill_item_sales link
        JOIN working.bill_items item ON item.id = link.bill_item_id
        WHERE item.bill_id = target_bill.id
      ), '[]'::JSONB),
      'other_charges', coalesce((
        SELECT jsonb_agg(to_jsonb(charge) ORDER BY charge.id)
        FROM working.bill_other_charges charge WHERE charge.bill_id = target_bill.id
      ), '[]'::JSONB),
      'payments', coalesce((
        SELECT jsonb_agg(to_jsonb(payment) ORDER BY payment.id)
        FROM working.payments payment WHERE payment.bill_id = target_bill.id
      ), '[]'::JSONB)
    ),
    auth.uid()
  ) RETURNING id INTO correction_id_value;

  PERFORM set_config('working.bill_correction_context', 'bills:' || target_bill.id::TEXT, TRUE);
  IF working.delete_customer_bill(target_bill.id) IS NOT TRUE THEN
    RAISE EXCEPTION 'Customer bill could not be released for correction';
  END IF;

  RETURN jsonb_build_object(
    'correction_id', correction_id_value,
    'customer_id', target_bill.customer_id,
    'bill_date', target_bill.bill_date,
    'original_bill_number', target_bill.bill_number
  );
END;
$$;

CREATE OR REPLACE FUNCTION working.revise_customer_bill(
  p_bill_id BIGINT,
  p_reason TEXT,
  p_customer_id BIGINT,
  p_bill_date DATE,
  p_items JSONB,
  p_other_charges JSONB DEFAULT '[]'::JSONB,
  p_discount NUMERIC DEFAULT 0,
  p_notes TEXT DEFAULT NULL,
  p_payments JSONB DEFAULT '[]'::JSONB,
  p_mark_as_paid BOOLEAN DEFAULT FALSE
)
RETURNS working.bills
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  target_bill working.bills%ROWTYPE;
  customer_name_value TEXT;
  correction_id_value BIGINT;
  replacement_bill working.bills%ROWTYPE;
  reason_value TEXT := regexp_replace(btrim(coalesce(p_reason, '')), '[[:space:]]+', ' ', 'g');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can revise customer bills' USING ERRCODE = '42501';
  END IF;
  IF char_length(reason_value) < 5 THEN
    RAISE EXCEPTION 'Enter a correction reason of at least 5 characters';
  END IF;

  SELECT bill.*
  INTO target_bill
  FROM working.bills bill
  WHERE bill.id = p_bill_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Customer bill not found'; END IF;
  SELECT name INTO customer_name_value
  FROM working.customers WHERE id = target_bill.customer_id;
  IF target_bill.customer_id <> p_customer_id OR target_bill.bill_date <> p_bill_date THEN
    RAISE EXCEPTION 'A correction cannot change the customer or bill date';
  END IF;
  IF target_bill.is_active IS NOT TRUE THEN
    RAISE EXCEPTION 'Only the latest customer bill can be revised because later bills carry its balance';
  END IF;
  IF EXISTS (
    SELECT 1 FROM working.payments
    WHERE bill_id = p_bill_id AND voided_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Void active receipts linked to this bill before revising it';
  END IF;

  INSERT INTO working.bill_corrections (
    document_type, correction_action, original_bill_id, original_bill_number,
    counterparty_id, counterparty_name, bill_date, reason, original_snapshot, corrected_by
  ) VALUES (
    'customer_bill', 'revised', target_bill.id, target_bill.bill_number,
    target_bill.customer_id, customer_name_value, target_bill.bill_date, reason_value,
    jsonb_build_object(
      'bill', to_jsonb(target_bill),
      'items', coalesce((
        SELECT jsonb_agg(to_jsonb(item) ORDER BY item.id)
        FROM working.bill_items item WHERE item.bill_id = target_bill.id
      ), '[]'::JSONB),
      'sale_links', coalesce((
        SELECT jsonb_agg(to_jsonb(link) ORDER BY link.bill_item_id, link.sale_id)
        FROM working.bill_item_sales link
        JOIN working.bill_items item ON item.id = link.bill_item_id
        WHERE item.bill_id = target_bill.id
      ), '[]'::JSONB),
      'other_charges', coalesce((
        SELECT jsonb_agg(to_jsonb(charge) ORDER BY charge.id)
        FROM working.bill_other_charges charge WHERE charge.bill_id = target_bill.id
      ), '[]'::JSONB),
      'payments', coalesce((
        SELECT jsonb_agg(to_jsonb(payment) ORDER BY payment.id)
        FROM working.payments payment WHERE payment.bill_id = target_bill.id
      ), '[]'::JSONB)
    ),
    auth.uid()
  ) RETURNING id INTO correction_id_value;

  PERFORM set_config('working.bill_correction_context', 'bills:' || target_bill.id::TEXT, TRUE);
  SELECT * INTO replacement_bill
  FROM working.create_customer_bill(
    p_customer_id, p_bill_date, p_items, p_other_charges, p_discount,
    p_notes, p_payments, p_mark_as_paid, p_bill_id
  );

  UPDATE working.bill_corrections
  SET replacement_bill_id = replacement_bill.id,
      replacement_bill_number = replacement_bill.bill_number
  WHERE id = correction_id_value;

  RETURN replacement_bill;
END;
$$;

CREATE OR REPLACE FUNCTION working.release_purchase_bill_for_correction(
  p_purchase_bill_id BIGINT,
  p_reason TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  target_bill working.purchase_bills%ROWTYPE;
  supplier_name_value TEXT;
  correction_id_value BIGINT;
  reason_value TEXT := regexp_replace(btrim(coalesce(p_reason, '')), '[[:space:]]+', ' ', 'g');
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can correct purchase bills' USING ERRCODE = '42501';
  END IF;
  IF char_length(reason_value) < 5 THEN
    RAISE EXCEPTION 'Enter a correction reason of at least 5 characters';
  END IF;

  SELECT bill.*
  INTO target_bill
  FROM working.purchase_bills bill
  WHERE bill.id = p_purchase_bill_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Purchase bill not found'; END IF;
  SELECT name INTO supplier_name_value
  FROM working.suppliers WHERE id = target_bill.supplier_id;
  IF EXISTS (
    SELECT 1 FROM working.purchase_bill_payments
    WHERE purchase_bill_id = p_purchase_bill_id AND voided_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Void active supplier payments linked to this bill before correcting it';
  END IF;

  INSERT INTO working.bill_corrections (
    document_type, correction_action, original_bill_id, original_bill_number,
    counterparty_id, counterparty_name, bill_date, reason, original_snapshot, corrected_by
  ) VALUES (
    'purchase_bill', 'released_for_rebill', target_bill.id, target_bill.bill_number,
    target_bill.supplier_id, supplier_name_value, target_bill.bill_date, reason_value,
    jsonb_build_object(
      'bill', to_jsonb(target_bill),
      'items', coalesce((
        SELECT jsonb_agg(to_jsonb(item) ORDER BY item.id)
        FROM working.purchase_bill_items item WHERE item.purchase_bill_id = target_bill.id
      ), '[]'::JSONB),
      'payments', coalesce((
        SELECT jsonb_agg(to_jsonb(payment) ORDER BY payment.id)
        FROM working.purchase_bill_payments payment
        WHERE payment.purchase_bill_id = target_bill.id
      ), '[]'::JSONB)
    ),
    auth.uid()
  ) RETURNING id INTO correction_id_value;

  PERFORM set_config(
    'working.bill_correction_context',
    'purchase_bills:' || target_bill.id::TEXT,
    TRUE
  );
  IF working.delete_purchase_bill(target_bill.id) IS NOT TRUE THEN
    RAISE EXCEPTION 'Purchase bill could not be released for correction';
  END IF;

  RETURN jsonb_build_object(
    'correction_id', correction_id_value,
    'supplier_id', target_bill.supplier_id,
    'bill_date', target_bill.bill_date,
    'original_bill_number', target_bill.bill_number
  );
END;
$$;

REVOKE ALL ON FUNCTION working.guard_finalized_bill_deletion() FROM PUBLIC;
REVOKE ALL ON FUNCTION working.delete_customer_bill(BIGINT) FROM authenticated;
REVOKE ALL ON FUNCTION working.delete_purchase_bill(BIGINT) FROM authenticated;

REVOKE ALL ON FUNCTION working.release_customer_bill_for_correction(BIGINT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.release_customer_bill_for_correction(BIGINT, TEXT) TO authenticated;
REVOKE ALL ON FUNCTION working.revise_customer_bill(BIGINT, TEXT, BIGINT, DATE, JSONB, JSONB, NUMERIC, TEXT, JSONB, BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.revise_customer_bill(BIGINT, TEXT, BIGINT, DATE, JSONB, JSONB, NUMERIC, TEXT, JSONB, BOOLEAN) TO authenticated;
REVOKE ALL ON FUNCTION working.release_purchase_bill_for_correction(BIGINT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.release_purchase_bill_for_correction(BIGINT, TEXT) TO authenticated;

COMMENT ON TABLE working.bill_corrections IS
  'Immutable before-state and reason for every finalized customer or purchase bill correction.';
COMMENT ON FUNCTION working.revise_customer_bill(BIGINT, TEXT, BIGINT, DATE, JSONB, JSONB, NUMERIC, TEXT, JSONB, BOOLEAN) IS
  'Atomically snapshots and replaces the latest unpaid customer bill with a reason and audit link.';
COMMENT ON FUNCTION working.release_purchase_bill_for_correction(BIGINT, TEXT) IS
  'Snapshots an unpaid purchase bill and releases its purchases for corrected rebilling.';

COMMIT;
