BEGIN;

ALTER TABLE working.customers
  ADD COLUMN IF NOT EXISTS opening_balance NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS opening_balance_date DATE,
  ADD COLUMN IF NOT EXISTS opening_balance_updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS opening_balance_updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS working.customer_opening_balance_changes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES working.customers(id) ON DELETE RESTRICT,
  previous_balance NUMERIC(14,2) NOT NULL,
  new_balance NUMERIC(14,2) NOT NULL,
  previous_date DATE,
  new_date DATE,
  reason TEXT,
  changed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE working.customer_opening_balance_changes ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON working.customer_opening_balance_changes TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON working.customer_opening_balance_changes FROM anon, authenticated;
CREATE POLICY admin_read_customer_opening_balance_changes
ON working.customer_opening_balance_changes FOR SELECT TO authenticated
USING (working.current_app_role() = 'admin');

CREATE OR REPLACE FUNCTION working.set_customer_opening_balance(
  p_customer_id BIGINT, p_balance NUMERIC, p_effective_date DATE, p_reason TEXT DEFAULT NULL
)
RETURNS working.customers LANGUAGE plpgsql SECURITY DEFINER SET search_path = working, pg_temp AS $$
DECLARE
  target working.customers%ROWTYPE;
  reason_value TEXT := nullif(regexp_replace(btrim(coalesce(p_reason, '')), '[[:space:]]+', ' ', 'g'), '');
BEGIN
  IF working.current_app_role() <> 'admin' THEN RAISE EXCEPTION 'Only administrators can set opening balances' USING ERRCODE = '42501'; END IF;
  IF p_balance IS NULL OR p_effective_date IS NULL THEN RAISE EXCEPTION 'Balance and effective date are required'; END IF;
  IF p_effective_date > CURRENT_DATE THEN RAISE EXCEPTION 'Opening balance date cannot be in the future'; END IF;
  SELECT * INTO target FROM working.customers WHERE id = p_customer_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Customer not found'; END IF;
  IF EXISTS (SELECT 1 FROM working.bills WHERE customer_id = p_customer_id)
     OR EXISTS (SELECT 1 FROM working.payments WHERE customer_id = p_customer_id) THEN
    RAISE EXCEPTION 'Opening balance is locked after billing or payment activity begins';
  END IF;
  IF (target.opening_balance <> 0 OR target.opening_balance_date IS NOT NULL)
     AND char_length(coalesce(reason_value, '')) < 5 THEN
    RAISE EXCEPTION 'Enter a correction reason of at least 5 characters';
  END IF;

  INSERT INTO working.customer_opening_balance_changes
    (customer_id, previous_balance, new_balance, previous_date, new_date, reason, changed_by)
  VALUES (target.id, target.opening_balance, p_balance, target.opening_balance_date,
    CASE WHEN p_balance = 0 THEN NULL ELSE p_effective_date END, reason_value, auth.uid());

  UPDATE working.customers
  SET opening_balance = p_balance,
      opening_balance_date = CASE WHEN p_balance = 0 THEN NULL ELSE p_effective_date END,
      opening_balance_updated_at = NOW(), opening_balance_updated_by = auth.uid()
  WHERE id = target.id RETURNING * INTO target;
  RETURN target;
END;
$$;

CREATE OR REPLACE FUNCTION working.apply_opening_balance_to_first_bill()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = working, pg_temp AS $$
DECLARE opening_value NUMERIC(14,2);
BEGIN
  IF NOT EXISTS (SELECT 1 FROM working.bills WHERE customer_id = NEW.customer_id) THEN
    SELECT CASE WHEN opening_balance_date <= NEW.bill_date THEN opening_balance ELSE 0 END
    INTO opening_value FROM working.customers WHERE id = NEW.customer_id;
    opening_value := coalesce(opening_value, 0);
    NEW.previous_balance := NEW.previous_balance + opening_value;
    NEW.balance_due := NEW.balance_due + opening_value;
    NEW.total := NEW.total + opening_value;
    NEW.status := CASE WHEN NEW.total <= 0 THEN 'paid' ELSE 'unpaid' END;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS apply_opening_balance_to_first_bill ON working.bills;
CREATE TRIGGER apply_opening_balance_to_first_bill BEFORE INSERT ON working.bills
FOR EACH ROW EXECUTE FUNCTION working.apply_opening_balance_to_first_bill();

CREATE OR REPLACE FUNCTION working.get_customer_account_summary(p_customer_id BIGINT, p_as_of_date DATE DEFAULT CURRENT_DATE)
RETURNS TABLE (total_charged NUMERIC, total_paid NUMERIC, account_balance NUMERIC, outstanding_amount NUMERIC,
  advance_credit NUMERIC, unpaid_bills_count BIGINT, oldest_bill_date DATE)
LANGUAGE sql STABLE SECURITY INVOKER SET search_path = working AS $$
  WITH opening AS (
    SELECT CASE WHEN opening_balance_date <= p_as_of_date THEN opening_balance ELSE 0 END AS value,
           opening_balance_date AS effective_date FROM working.customers WHERE id = p_customer_id
  ), charges AS (
    SELECT coalesce(sum(subtotal - discount), 0)::NUMERIC AS value FROM working.bills
    WHERE customer_id = p_customer_id AND bill_date <= p_as_of_date
  ), receipts AS (
    SELECT coalesce(sum(amount), 0)::NUMERIC AS value FROM working.payments
    WHERE customer_id = p_customer_id AND payment_date <= p_as_of_date AND voided_at IS NULL
  ), balance AS (
    SELECT charges.value + greatest(opening.value, 0) AS charged,
      receipts.value + greatest(-opening.value, 0) AS paid,
      opening.value + charges.value - receipts.value AS value, opening.effective_date FROM opening, charges, receipts
  )
  SELECT charged, paid, value, greatest(value, 0), greatest(-value, 0),
    CASE WHEN value > 0 THEN 1 ELSE 0 END::BIGINT,
    CASE WHEN value > 0 THEN coalesce((SELECT min(bill_date) FROM working.bills
      WHERE customer_id = p_customer_id AND bill_date <= p_as_of_date), effective_date) ELSE NULL END
  FROM balance;
$$;

REVOKE ALL ON FUNCTION working.set_customer_opening_balance(BIGINT, NUMERIC, DATE, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.set_customer_opening_balance(BIGINT, NUMERIC, DATE, TEXT) TO authenticated;
REVOKE ALL ON FUNCTION working.apply_opening_balance_to_first_bill() FROM PUBLIC;
COMMENT ON COLUMN working.customers.opening_balance IS 'Signed starting balance: positive is receivable; negative is customer credit.';
COMMENT ON TABLE working.customer_opening_balance_changes IS 'Immutable audit history for customer opening balances.';

COMMIT;
