BEGIN;

CREATE TABLE working.packing_share_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token_hash TEXT NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  packing_date DATE NOT NULL,
  customer_ids BIGINT[] NOT NULL CHECK (cardinality(customer_ids) > 0),
  allow_updates BOOLEAN NOT NULL DEFAULT TRUE,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (expires_at > created_at)
);

CREATE TABLE working.packing_share_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  share_id UUID NOT NULL REFERENCES working.packing_share_links(id) ON DELETE CASCADE,
  sale_id BIGINT NOT NULL REFERENCES working.sales(id) ON DELETE CASCADE,
  loaded BOOLEAN NOT NULL,
  session_id VARCHAR(64),
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX packing_share_links_active_idx
  ON working.packing_share_links (packing_date, expires_at)
  WHERE revoked_at IS NULL;

CREATE INDEX packing_share_activity_share_idx
  ON working.packing_share_activity (share_id, changed_at DESC);

ALTER TABLE working.packing_share_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.packing_share_activity ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON working.packing_share_links, working.packing_share_activity FROM anon, authenticated;
REVOKE ALL ON SEQUENCE working.packing_share_activity_id_seq FROM anon, authenticated;

CREATE OR REPLACE FUNCTION working.create_packing_share(
  p_packing_date DATE,
  p_customer_ids BIGINT[],
  p_allow_updates BOOLEAN DEFAULT TRUE
)
RETURNS TABLE(token TEXT, share_id UUID, expires_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  business_timezone TEXT;
  business_today DATE;
  normalized_customer_ids BIGINT[];
  raw_token TEXT;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only an administrator can share a packing list';
  END IF;

  SELECT COALESCE(preferences.timezone, 'Asia/Kolkata')
    INTO business_timezone
    FROM working.business_preferences preferences
   WHERE preferences.id = 1;

  business_timezone := COALESCE(business_timezone, 'Asia/Kolkata');
  business_today := (NOW() AT TIME ZONE business_timezone)::DATE;

  IF p_packing_date IS DISTINCT FROM business_today THEN
    RAISE EXCEPTION 'Only today''s packing list can be shared';
  END IF;

  IF COALESCE(cardinality(p_customer_ids), 0) = 0 THEN
    RAISE EXCEPTION 'Select at least one customer';
  END IF;

  IF EXISTS (
    SELECT 1
      FROM unnest(p_customer_ids) selected(customer_id)
     WHERE NOT EXISTS (
       SELECT 1
         FROM working.sales sale
        WHERE sale.sale_date = p_packing_date
          AND sale.customer_id = selected.customer_id
     )
  ) THEN
    RAISE EXCEPTION 'The selection contains a customer without sales for this date';
  END IF;

  SELECT array_agg(DISTINCT selected.customer_id ORDER BY selected.customer_id)
    INTO normalized_customer_ids
    FROM unnest(p_customer_ids) selected(customer_id);

  UPDATE working.packing_share_links
     SET revoked_at = NOW()
   WHERE packing_date = p_packing_date
     AND created_by = auth.uid()
     AND revoked_at IS NULL;

  raw_token := encode(extensions.gen_random_bytes(24), 'hex');

  INSERT INTO working.packing_share_links (
    token_hash,
    packing_date,
    customer_ids,
    allow_updates,
    expires_at,
    created_by
  )
  VALUES (
    encode(extensions.digest(raw_token, 'sha256'), 'hex'),
    p_packing_date,
    normalized_customer_ids,
    COALESCE(p_allow_updates, TRUE),
    (p_packing_date + 1 + TIME '06:00') AT TIME ZONE business_timezone,
    auth.uid()
  )
  RETURNING id, packing_share_links.expires_at
       INTO share_id, expires_at;

  token := raw_token;

  RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION working.get_packing_share(p_token TEXT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  active_share working.packing_share_links%ROWTYPE;
  customers_payload JSONB;
  business_name TEXT;
BEGIN
  IF p_token IS NULL OR length(p_token) < 32 THEN
    RAISE EXCEPTION 'Packing link is invalid or expired';
  END IF;

  SELECT share.*
    INTO active_share
    FROM working.packing_share_links share
   WHERE share.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
     AND share.revoked_at IS NULL
     AND share.expires_at > NOW();

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Packing link is invalid or expired';
  END IF;

  SELECT profile.display_name
    INTO business_name
    FROM working.business_profile profile
   WHERE profile.id = 1;

  SELECT COALESCE(jsonb_agg(customer_row.payload ORDER BY customer_row.is_wholesale DESC, customer_row.total_crates DESC, customer_row.total_kg DESC, customer_row.customer_name), '[]'::JSONB)
    INTO customers_payload
    FROM (
      SELECT
        customer.name AS customer_name,
        customer.business_type = 'Wholesale Market' AS is_wholesale,
        SUM(sale.quantity_crates) AS total_crates,
        SUM(sale.quantity_kg) AS total_kg,
        jsonb_build_object(
          'customerId', customer.id,
          'customerName', customer.name,
          'totalCrates', SUM(sale.quantity_crates),
          'totalKg', SUM(sale.quantity_kg),
          'items', jsonb_agg(
            jsonb_build_object(
              'saleId', sale.id,
              'name', variant.name,
              'crates', sale.quantity_crates,
              'kg', sale.quantity_kg,
              'loaded', COALESCE(status.loaded, FALSE)
            )
            ORDER BY item.name, grade.sort_order, sale.id
          )
        ) AS payload
      FROM working.sales sale
      JOIN working.customers customer ON customer.id = sale.customer_id
      JOIN working.item_variants variant ON variant.id = sale.fish_variety_id
      JOIN working.items item ON item.id = variant.item_id
      JOIN working.item_grades grade ON grade.id = variant.grade_id
      LEFT JOIN working.packing_status status ON status.sale_id = sale.id
      WHERE sale.sale_date = active_share.packing_date
        AND sale.customer_id = ANY(active_share.customer_ids)
      GROUP BY customer.id, customer.name, customer.business_type
    ) customer_row;

  RETURN jsonb_build_object(
    'businessName', COALESCE(business_name, 'Packing List'),
    'packingDate', active_share.packing_date,
    'expiresAt', active_share.expires_at,
    'allowUpdates', active_share.allow_updates,
    'customers', customers_payload
  );
END;
$$;

CREATE OR REPLACE FUNCTION working.update_shared_packing_status(
  p_token TEXT,
  p_sale_id BIGINT,
  p_loaded BOOLEAN,
  p_session_id TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  active_share working.packing_share_links%ROWTYPE;
  changed_at TIMESTAMPTZ := NOW();
BEGIN
  SELECT share.*
    INTO active_share
    FROM working.packing_share_links share
   WHERE share.token_hash = encode(extensions.digest(COALESCE(p_token, ''), 'sha256'), 'hex')
     AND share.revoked_at IS NULL
     AND share.expires_at > NOW()
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Packing link is invalid or expired';
  END IF;

  IF NOT active_share.allow_updates THEN
    RAISE EXCEPTION 'This packing link is view only';
  END IF;

  IF NOT EXISTS (
    SELECT 1
      FROM working.sales sale
     WHERE sale.id = p_sale_id
       AND sale.sale_date = active_share.packing_date
       AND sale.customer_id = ANY(active_share.customer_ids)
  ) THEN
    RAISE EXCEPTION 'This item is not available through the packing link';
  END IF;

  INSERT INTO working.packing_status (sale_id, loaded, loaded_at, loaded_by, updated_at)
  VALUES (
    p_sale_id,
    p_loaded,
    CASE WHEN p_loaded THEN changed_at ELSE NULL END,
    CASE WHEN p_loaded THEN 'shared:' || active_share.id::TEXT ELSE NULL END,
    changed_at
  )
  ON CONFLICT (sale_id) DO UPDATE
    SET loaded = EXCLUDED.loaded,
        loaded_at = EXCLUDED.loaded_at,
        loaded_by = EXCLUDED.loaded_by,
        updated_at = EXCLUDED.updated_at;

  INSERT INTO working.packing_share_activity (share_id, sale_id, loaded, session_id, changed_at)
  VALUES (active_share.id, p_sale_id, p_loaded, NULLIF(left(trim(COALESCE(p_session_id, '')), 64), ''), changed_at);

  RETURN jsonb_build_object('saleId', p_sale_id, 'loaded', p_loaded, 'changedAt', changed_at);
END;
$$;

CREATE OR REPLACE FUNCTION working.revoke_packing_shares(p_packing_date DATE)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  revoked_count INTEGER;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only an administrator can revoke packing links';
  END IF;

  UPDATE working.packing_share_links
     SET revoked_at = NOW()
   WHERE packing_date = p_packing_date
     AND revoked_at IS NULL;

  GET DIAGNOSTICS revoked_count = ROW_COUNT;
  RETURN revoked_count;
END;
$$;

REVOKE ALL ON FUNCTION working.create_packing_share(DATE, BIGINT[], BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION working.get_packing_share(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION working.update_shared_packing_status(TEXT, BIGINT, BOOLEAN, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION working.revoke_packing_shares(DATE) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION working.create_packing_share(DATE, BIGINT[], BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION working.get_packing_share(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION working.update_shared_packing_status(TEXT, BIGINT, BOOLEAN, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION working.revoke_packing_shares(DATE) TO authenticated;

COMMENT ON TABLE working.packing_share_links IS 'Hashed, expiring access grants for selected customers on one packing date.';
COMMENT ON TABLE working.packing_share_activity IS 'Immutable audit trail of packing changes made through temporary links.';

COMMIT;
