-- Independent Ice Plant can grid. No Fish Trading tables are referenced.

CREATE TABLE working.ice_cans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  row_number SMALLINT NOT NULL CHECK (row_number BETWEEN 1 AND 19),
  column_code CHAR(1) NOT NULL CHECK (column_code BETWEEN 'A' AND 'M'),
  label VARCHAR(4) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  unavailable_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (row_number, column_code)
);

CREATE TABLE working.ice_can_daily_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  can_id BIGINT NOT NULL REFERENCES working.ice_cans(id) ON DELETE RESTRICT,
  check_date DATE NOT NULL,
  status VARCHAR(16) NOT NULL CHECK (status IN ('water', 'quarter', 'half', 'three_quarter', 'full')),
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  checked_at TIMESTAMPTZ,
  checked_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (can_id, check_date)
);

CREATE INDEX idx_ice_can_daily_checks_date
  ON working.ice_can_daily_checks(check_date DESC, can_id);

INSERT INTO working.ice_cans (row_number, column_code, label, is_active, unavailable_reason)
SELECT
  row_value,
  column_value,
  column_value || row_value::TEXT,
  NOT (column_value = 'M' AND row_value = 19),
  CASE WHEN column_value = 'M' AND row_value = 19 THEN 'Removed from service' END
FROM generate_series(1, 19) AS row_value
CROSS JOIN unnest(ARRAY['A','B','C','D','E','F','G','H','I','J','K','L','M']) AS column_value
ON CONFLICT (row_number, column_code) DO NOTHING;

ALTER TABLE working.ice_cans ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.ice_can_daily_checks ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_access ON working.ice_cans
FOR ALL TO authenticated
USING (working.current_app_role() = 'admin')
WITH CHECK (working.current_app_role() = 'admin');

CREATE POLICY admin_access ON working.ice_can_daily_checks
FOR ALL TO authenticated
USING (working.current_app_role() = 'admin')
WITH CHECK (working.current_app_role() = 'admin');

GRANT SELECT, INSERT, UPDATE, DELETE ON working.ice_cans TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON working.ice_can_daily_checks TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE working.ice_cans_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE working.ice_can_daily_checks_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION working.get_ice_can_grid(p_check_date DATE)
RETURNS TABLE (
  can_id BIGINT,
  row_number SMALLINT,
  column_code TEXT,
  label TEXT,
  is_active BOOLEAN,
  unavailable_reason TEXT,
  status TEXT,
  verified BOOLEAN,
  checked_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can access the Ice Plant grid' USING ERRCODE = '42501';
  END IF;
  IF p_check_date IS NULL OR p_check_date > CURRENT_DATE THEN
    RAISE EXCEPTION 'Choose today or an earlier date';
  END IF;

  INSERT INTO working.ice_can_daily_checks (can_id, check_date, status, verified)
  SELECT
    can_row.id,
    p_check_date,
    COALESCE((
      SELECT previous.status
      FROM working.ice_can_daily_checks previous
      WHERE previous.can_id = can_row.id
        AND previous.check_date < p_check_date
      ORDER BY previous.check_date DESC
      LIMIT 1
    ), 'water'),
    FALSE
  FROM working.ice_cans can_row
  WHERE can_row.is_active
  ON CONFLICT ON CONSTRAINT ice_can_daily_checks_can_id_check_date_key DO NOTHING;

  RETURN QUERY
  SELECT
    can_row.id,
    can_row.row_number,
    can_row.column_code::TEXT,
    can_row.label::TEXT,
    can_row.is_active,
    can_row.unavailable_reason,
    COALESCE(daily.status, 'removed')::TEXT,
    COALESCE(daily.verified, FALSE),
    daily.checked_at
  FROM working.ice_cans can_row
  LEFT JOIN working.ice_can_daily_checks daily
    ON daily.can_id = can_row.id AND daily.check_date = p_check_date
  ORDER BY can_row.row_number, can_row.column_code;
END;
$$;

CREATE OR REPLACE FUNCTION working.set_ice_can_status(
  p_can_id BIGINT,
  p_check_date DATE,
  p_status TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can update the Ice Plant grid' USING ERRCODE = '42501';
  END IF;
  IF p_check_date IS NULL OR p_check_date > CURRENT_DATE THEN
    RAISE EXCEPTION 'Choose today or an earlier date';
  END IF;
  IF p_status NOT IN ('water', 'quarter', 'half', 'three_quarter', 'full') THEN
    RAISE EXCEPTION 'Invalid can status';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM working.ice_cans WHERE id = p_can_id AND is_active) THEN
    RAISE EXCEPTION 'This can is unavailable';
  END IF;

  INSERT INTO working.ice_can_daily_checks (
    can_id, check_date, status, verified, checked_at, checked_by, updated_at
  ) VALUES (
    p_can_id, p_check_date, p_status, TRUE, NOW(), auth.uid(), NOW()
  )
  ON CONFLICT (can_id, check_date) DO UPDATE SET
    status = EXCLUDED.status,
    verified = TRUE,
    checked_at = NOW(),
    checked_by = auth.uid(),
    updated_at = NOW();

  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION working.verify_ice_can_grid(p_check_date DATE)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  verified_count INTEGER;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can verify the Ice Plant grid' USING ERRCODE = '42501';
  END IF;
  IF p_check_date IS NULL OR p_check_date > CURRENT_DATE THEN
    RAISE EXCEPTION 'Choose today or an earlier date';
  END IF;

  PERFORM working.get_ice_can_grid(p_check_date);
  UPDATE working.ice_can_daily_checks daily
  SET verified = TRUE, checked_at = NOW(), checked_by = auth.uid(), updated_at = NOW()
  FROM working.ice_cans can_row
  WHERE daily.can_id = can_row.id
    AND daily.check_date = p_check_date
    AND can_row.is_active
    AND NOT daily.verified;

  SELECT count(*)::INTEGER INTO verified_count
  FROM working.ice_can_daily_checks
  WHERE check_date = p_check_date AND verified;
  RETURN verified_count;
END;
$$;

REVOKE ALL ON FUNCTION working.get_ice_can_grid(DATE) FROM PUBLIC;
REVOKE ALL ON FUNCTION working.set_ice_can_status(BIGINT, DATE, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION working.verify_ice_can_grid(DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.get_ice_can_grid(DATE) TO authenticated;
GRANT EXECUTE ON FUNCTION working.set_ice_can_status(BIGINT, DATE, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION working.verify_ice_can_grid(DATE) TO authenticated;

COMMENT ON TABLE working.ice_can_daily_checks IS
  'Independent daily Ice Plant can observations; carried values remain unverified until checked.';
