-- Independent Ice Plant sales, receipts and expenses. No Fish Trading finance tables are referenced.

CREATE TABLE working.ice_sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_date DATE NOT NULL,
  customer_name TEXT,
  block_quantity INTEGER NOT NULL CHECK (block_quantity > 0),
  rate_per_block NUMERIC(12,2) NOT NULL CHECK (rate_per_block >= 0),
  total_amount NUMERIC(14,2) NOT NULL CHECK (total_amount >= 0),
  notes TEXT,
  voided_at TIMESTAMPTZ,
  voided_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE TABLE working.ice_sale_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT NOT NULL REFERENCES working.ice_sales(id) ON DELETE CASCADE,
  payment_date DATE NOT NULL,
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
  payment_method TEXT NOT NULL CHECK (payment_method IN ('cash','upi','bank')),
  reference_number TEXT,
  voided_at TIMESTAMPTZ,
  voided_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE TABLE working.ice_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_date DATE NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('electricity','labour','maintenance','transport','water','other')),
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
  payment_method TEXT NOT NULL CHECK (payment_method IN ('cash','upi','bank')),
  payee TEXT,
  notes TEXT,
  reference_number TEXT,
  voided_at TIMESTAMPTZ,
  voided_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX idx_ice_sales_date ON working.ice_sales(sale_date DESC) WHERE voided_at IS NULL;
CREATE INDEX idx_ice_sale_payments_date ON working.ice_sale_payments(payment_date DESC) WHERE voided_at IS NULL;
CREATE INDEX idx_ice_expenses_date ON working.ice_expenses(expense_date DESC) WHERE voided_at IS NULL;

ALTER TABLE working.ice_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.ice_sale_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.ice_expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY admin_access ON working.ice_sales FOR ALL TO authenticated USING (working.current_app_role() = 'admin') WITH CHECK (working.current_app_role() = 'admin');
CREATE POLICY admin_access ON working.ice_sale_payments FOR ALL TO authenticated USING (working.current_app_role() = 'admin') WITH CHECK (working.current_app_role() = 'admin');
CREATE POLICY admin_access ON working.ice_expenses FOR ALL TO authenticated USING (working.current_app_role() = 'admin') WITH CHECK (working.current_app_role() = 'admin');
GRANT SELECT, INSERT, UPDATE ON working.ice_sales, working.ice_sale_payments, working.ice_expenses TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE working.ice_sales_id_seq, working.ice_sale_payments_id_seq, working.ice_expenses_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION working.record_ice_sale(
  p_sale_date DATE, p_customer_name TEXT, p_block_quantity INTEGER, p_rate_per_block NUMERIC,
  p_amount_received NUMERIC, p_payment_method TEXT, p_notes TEXT, p_reference_number TEXT
) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = working, pg_temp AS $$
DECLARE new_id BIGINT; total NUMERIC(14,2); received NUMERIC(14,2) := COALESCE(p_amount_received, 0);
BEGIN
  IF working.current_app_role() <> 'admin' THEN RAISE EXCEPTION 'Only administrators can record Ice Plant sales' USING ERRCODE = '42501'; END IF;
  IF p_sale_date IS NULL OR p_sale_date > CURRENT_DATE THEN RAISE EXCEPTION 'Choose today or an earlier date'; END IF;
  IF COALESCE(p_block_quantity,0) <= 0 OR COALESCE(p_rate_per_block,-1) < 0 THEN RAISE EXCEPTION 'Enter a valid block quantity and rate'; END IF;
  total := round(p_block_quantity * p_rate_per_block, 2);
  IF received < 0 OR received > total THEN RAISE EXCEPTION 'Received amount cannot exceed sale total'; END IF;
  IF received < total AND NULLIF(trim(p_customer_name),'') IS NULL THEN RAISE EXCEPTION 'Customer name is required for credit sales'; END IF;
  IF received > 0 AND p_payment_method NOT IN ('cash','upi','bank') THEN RAISE EXCEPTION 'Choose how the payment was received'; END IF;
  INSERT INTO working.ice_sales(sale_date,customer_name,block_quantity,rate_per_block,total_amount,notes,created_by)
  VALUES(p_sale_date,NULLIF(trim(p_customer_name),''),p_block_quantity,p_rate_per_block,total,NULLIF(trim(p_notes),''),auth.uid()) RETURNING id INTO new_id;
  IF received > 0 THEN
    INSERT INTO working.ice_sale_payments(sale_id,payment_date,amount,payment_method,reference_number,created_by)
    VALUES(new_id,p_sale_date,received,p_payment_method,NULLIF(trim(p_reference_number),''),auth.uid());
  END IF;
  RETURN new_id;
END; $$;

CREATE OR REPLACE FUNCTION working.record_ice_sale_payment(
  p_sale_id BIGINT, p_payment_date DATE, p_amount NUMERIC, p_payment_method TEXT, p_reference_number TEXT
) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = working, pg_temp AS $$
DECLARE new_id BIGINT; remaining NUMERIC(14,2);
BEGIN
  IF working.current_app_role() <> 'admin' THEN RAISE EXCEPTION 'Only administrators can record Ice Plant payments' USING ERRCODE = '42501'; END IF;
  SELECT sale.total_amount - COALESCE(sum(payment.amount) FILTER (WHERE payment.voided_at IS NULL),0)
  INTO remaining FROM working.ice_sales sale LEFT JOIN working.ice_sale_payments payment ON payment.sale_id=sale.id
  WHERE sale.id=p_sale_id AND sale.voided_at IS NULL GROUP BY sale.id;
  IF remaining IS NULL THEN RAISE EXCEPTION 'Sale was not found'; END IF;
  IF COALESCE(p_amount,0) <= 0 OR p_amount > remaining THEN RAISE EXCEPTION 'Payment cannot exceed the remaining balance'; END IF;
  IF p_payment_date IS NULL OR p_payment_date > CURRENT_DATE THEN RAISE EXCEPTION 'Choose today or an earlier date'; END IF;
  IF p_payment_method NOT IN ('cash','upi','bank') THEN RAISE EXCEPTION 'Choose a payment method'; END IF;
  INSERT INTO working.ice_sale_payments(sale_id,payment_date,amount,payment_method,reference_number,created_by)
  VALUES(p_sale_id,p_payment_date,p_amount,p_payment_method,NULLIF(trim(p_reference_number),''),auth.uid()) RETURNING id INTO new_id;
  RETURN new_id;
END; $$;

CREATE OR REPLACE FUNCTION working.record_ice_expense(
  p_expense_date DATE, p_category TEXT, p_amount NUMERIC, p_payment_method TEXT,
  p_payee TEXT, p_notes TEXT, p_reference_number TEXT
) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = working, pg_temp AS $$
DECLARE new_id BIGINT;
BEGIN
  IF working.current_app_role() <> 'admin' THEN RAISE EXCEPTION 'Only administrators can record Ice Plant expenses' USING ERRCODE = '42501'; END IF;
  IF p_expense_date IS NULL OR p_expense_date > CURRENT_DATE THEN RAISE EXCEPTION 'Choose today or an earlier date'; END IF;
  IF p_category NOT IN ('electricity','labour','maintenance','transport','water','other') THEN RAISE EXCEPTION 'Choose a valid category'; END IF;
  IF COALESCE(p_amount,0) <= 0 THEN RAISE EXCEPTION 'Expense amount must be greater than zero'; END IF;
  IF p_payment_method NOT IN ('cash','upi','bank') THEN RAISE EXCEPTION 'Choose a payment method'; END IF;
  INSERT INTO working.ice_expenses(expense_date,category,amount,payment_method,payee,notes,reference_number,created_by)
  VALUES(p_expense_date,p_category,p_amount,p_payment_method,NULLIF(trim(p_payee),''),NULLIF(trim(p_notes),''),NULLIF(trim(p_reference_number),''),auth.uid()) RETURNING id INTO new_id;
  RETURN new_id;
END; $$;

CREATE OR REPLACE FUNCTION working.void_ice_money_entry(p_entry_type TEXT, p_entry_id BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER SET search_path = working, pg_temp AS $$
BEGIN
  IF working.current_app_role() <> 'admin' THEN RAISE EXCEPTION 'Only administrators can void Ice Plant entries' USING ERRCODE = '42501'; END IF;
  IF p_entry_type='sale' THEN UPDATE working.ice_sales SET voided_at=NOW(),voided_by=auth.uid() WHERE id=p_entry_id AND voided_at IS NULL;
  ELSIF p_entry_type='expense' THEN UPDATE working.ice_expenses SET voided_at=NOW(),voided_by=auth.uid() WHERE id=p_entry_id AND voided_at IS NULL;
  ELSE RAISE EXCEPTION 'Invalid entry type'; END IF;
  RETURN FOUND;
END; $$;

CREATE OR REPLACE FUNCTION working.get_ice_money_activity(p_activity_date DATE)
RETURNS TABLE(entry_type TEXT,id BIGINT,title TEXT,detail TEXT,amount NUMERIC,amount_paid NUMERIC,balance NUMERIC,payment_method TEXT,created_at TIMESTAMPTZ)
LANGUAGE sql SECURITY DEFINER SET search_path = working, pg_temp AS $$
  SELECT 'sale',sale.id,COALESCE(sale.customer_name,'Walk-in'),sale.block_quantity||' blocks × ₹'||trim(to_char(sale.rate_per_block,'FM999999990.00')),
    sale.total_amount,COALESCE(sum(payment.amount) FILTER(WHERE payment.voided_at IS NULL),0),
    sale.total_amount-COALESCE(sum(payment.amount) FILTER(WHERE payment.voided_at IS NULL),0),NULL::TEXT,sale.created_at
  FROM working.ice_sales sale LEFT JOIN working.ice_sale_payments payment ON payment.sale_id=sale.id
  WHERE sale.sale_date=p_activity_date AND sale.voided_at IS NULL GROUP BY sale.id
  UNION ALL
  SELECT 'expense',expense.id,initcap(expense.category),COALESCE(expense.payee,upper(expense.payment_method)),expense.amount,expense.amount,0,expense.payment_method,expense.created_at
  FROM working.ice_expenses expense WHERE expense.expense_date=p_activity_date AND expense.voided_at IS NULL
  ORDER BY created_at DESC;
$$;

CREATE OR REPLACE FUNCTION working.get_ice_finance_summary(p_from_date DATE,p_to_date DATE)
RETURNS TABLE(sales NUMERIC,expenses NUMERIC,net NUMERIC,blocks BIGINT,received NUMERIC,outstanding NUMERIC,cash NUMERIC,upi NUMERIC,bank NUMERIC)
LANGUAGE sql SECURITY DEFINER SET search_path = working, pg_temp AS $$
  WITH sale_totals AS (
    SELECT COALESCE(sum(total_amount),0) sales,COALESCE(sum(block_quantity),0)::BIGINT blocks
    FROM working.ice_sales WHERE sale_date BETWEEN p_from_date AND p_to_date AND voided_at IS NULL
  ), expense_totals AS (
    SELECT COALESCE(sum(amount),0) expenses FROM working.ice_expenses WHERE expense_date BETWEEN p_from_date AND p_to_date AND voided_at IS NULL
  ), receipt_totals AS (
    SELECT COALESCE(sum(payment.amount),0) received,
      COALESCE(sum(payment.amount) FILTER(WHERE payment.payment_method='cash'),0) cash,
      COALESCE(sum(payment.amount) FILTER(WHERE payment.payment_method='upi'),0) upi,
      COALESCE(sum(payment.amount) FILTER(WHERE payment.payment_method='bank'),0) bank
    FROM working.ice_sale_payments payment JOIN working.ice_sales sale ON sale.id=payment.sale_id
    WHERE payment.payment_date BETWEEN p_from_date AND p_to_date AND payment.voided_at IS NULL AND sale.voided_at IS NULL
  ), due AS (
    SELECT COALESCE(sum(sale.total_amount-COALESCE(paid.amount,0)),0) outstanding
    FROM working.ice_sales sale LEFT JOIN (SELECT sale_id,sum(amount) amount FROM working.ice_sale_payments WHERE voided_at IS NULL GROUP BY sale_id) paid ON paid.sale_id=sale.id
    WHERE sale.sale_date BETWEEN p_from_date AND p_to_date AND sale.voided_at IS NULL
  )
  SELECT s.sales,e.expenses,s.sales-e.expenses,s.blocks,r.received,d.outstanding,r.cash,r.upi,r.bank
  FROM sale_totals s CROSS JOIN expense_totals e CROSS JOIN receipt_totals r CROSS JOIN due d;
$$;

DO $$ DECLARE fn REGPROCEDURE; BEGIN
  FOREACH fn IN ARRAY ARRAY[
    'working.record_ice_sale(date,text,integer,numeric,numeric,text,text,text)'::REGPROCEDURE,
    'working.record_ice_sale_payment(bigint,date,numeric,text,text)'::REGPROCEDURE,
    'working.record_ice_expense(date,text,numeric,text,text,text,text)'::REGPROCEDURE,
    'working.void_ice_money_entry(text,bigint)'::REGPROCEDURE,
    'working.get_ice_money_activity(date)'::REGPROCEDURE,
    'working.get_ice_finance_summary(date,date)'::REGPROCEDURE
  ] LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',fn); EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO authenticated',fn); END LOOP;
END $$;
