-- Reusable Ice Plant customers and explicit customer-linked credit sales.

CREATE TABLE working.ice_customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (length(trim(name)) >= 2),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX uq_ice_customers_name ON working.ice_customers(lower(trim(name)));
ALTER TABLE working.ice_customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY admin_access ON working.ice_customers FOR ALL TO authenticated USING (working.current_app_role()='admin') WITH CHECK (working.current_app_role()='admin');
GRANT SELECT,INSERT,UPDATE ON working.ice_customers TO authenticated;
GRANT USAGE,SELECT ON SEQUENCE working.ice_customers_id_seq TO authenticated;

ALTER TABLE working.ice_sales ADD COLUMN customer_id BIGINT REFERENCES working.ice_customers(id) ON DELETE RESTRICT;
INSERT INTO working.ice_customers(name)
SELECT DISTINCT trim(customer_name) FROM working.ice_sales WHERE NULLIF(trim(customer_name),'') IS NOT NULL
ON CONFLICT DO NOTHING;
UPDATE working.ice_sales sale SET customer_id=customer.id
FROM working.ice_customers customer
WHERE sale.customer_id IS NULL AND lower(trim(sale.customer_name))=lower(trim(customer.name));

CREATE OR REPLACE FUNCTION working.create_ice_customer(p_name TEXT)
RETURNS TABLE(id BIGINT,name TEXT) LANGUAGE plpgsql SECURITY DEFINER SET search_path=working,pg_temp AS $$
DECLARE clean_name TEXT := regexp_replace(trim(p_name),'\s+',' ','g');
BEGIN
  IF working.current_app_role()<>'admin' THEN RAISE EXCEPTION 'Only administrators can create Ice Plant customers' USING ERRCODE='42501'; END IF;
  IF length(clean_name)<2 THEN RAISE EXCEPTION 'Enter a valid customer name'; END IF;
  IF EXISTS(SELECT 1 FROM working.ice_customers customer WHERE lower(customer.name)=lower(clean_name)) THEN RAISE EXCEPTION 'This Ice Plant customer already exists'; END IF;
  RETURN QUERY INSERT INTO working.ice_customers(name,created_by) VALUES(clean_name,auth.uid()) RETURNING ice_customers.id,ice_customers.name;
END $$;

CREATE OR REPLACE FUNCTION working.record_ice_sale_v2(
  p_sale_date DATE,p_customer_id BIGINT,p_block_quantity INTEGER,p_rate_per_block NUMERIC,
  p_amount_received NUMERIC,p_payment_method TEXT,p_notes TEXT,p_reference_number TEXT
) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path=working,pg_temp AS $$
DECLARE new_id BIGINT; total NUMERIC(14,2); received NUMERIC(14,2):=COALESCE(p_amount_received,0); selected_name TEXT;
BEGIN
  IF working.current_app_role()<>'admin' THEN RAISE EXCEPTION 'Only administrators can record Ice Plant sales' USING ERRCODE='42501'; END IF;
  IF p_sale_date IS NULL OR p_sale_date>CURRENT_DATE THEN RAISE EXCEPTION 'Choose today or an earlier date'; END IF;
  IF COALESCE(p_block_quantity,0)<=0 OR COALESCE(p_rate_per_block,-1)<0 THEN RAISE EXCEPTION 'Enter a valid block quantity and rate'; END IF;
  total:=round(p_block_quantity*p_rate_per_block,2);
  IF received<0 OR received>total THEN RAISE EXCEPTION 'Received amount cannot exceed sale total'; END IF;
  IF p_customer_id IS NOT NULL THEN SELECT customer.name INTO selected_name FROM working.ice_customers customer WHERE customer.id=p_customer_id AND customer.is_active; IF NOT FOUND THEN RAISE EXCEPTION 'Customer was not found'; END IF; END IF;
  IF received<total AND p_customer_id IS NULL THEN RAISE EXCEPTION 'Select a customer for partial or credit sales'; END IF;
  IF received>0 AND p_payment_method NOT IN ('cash','upi','bank') THEN RAISE EXCEPTION 'Choose how payment was received'; END IF;
  INSERT INTO working.ice_sales(sale_date,customer_id,customer_name,block_quantity,rate_per_block,total_amount,notes,created_by)
  VALUES(p_sale_date,p_customer_id,selected_name,p_block_quantity,p_rate_per_block,total,NULLIF(trim(p_notes),''),auth.uid()) RETURNING ice_sales.id INTO new_id;
  IF received>0 THEN INSERT INTO working.ice_sale_payments(sale_id,payment_date,amount,payment_method,reference_number,created_by)
    VALUES(new_id,p_sale_date,received,p_payment_method,NULLIF(trim(p_reference_number),''),auth.uid()); END IF;
  RETURN new_id;
END $$;

REVOKE ALL ON FUNCTION working.create_ice_customer(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION working.record_ice_sale_v2(DATE,BIGINT,INTEGER,NUMERIC,NUMERIC,TEXT,TEXT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION working.create_ice_customer(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION working.record_ice_sale_v2(DATE,BIGINT,INTEGER,NUMERIC,NUMERIC,TEXT,TEXT,TEXT) TO authenticated;
