-- Isolated historical-demand foundation for harvest forecasting.
-- Historical rows never enter operational sales, stock, billing, or cash tables.

BEGIN;

CREATE TABLE working.forecast_import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  source_project_ref TEXT NOT NULL,
  source_start_date DATE NOT NULL,
  source_end_date DATE NOT NULL,
  cutover_date DATE NOT NULL,
  source_row_count INTEGER NOT NULL CHECK (source_row_count >= 0),
  imported_row_count INTEGER NOT NULL DEFAULT 0 CHECK (imported_row_count >= 0),
  status TEXT NOT NULL DEFAULT 'staged'
    CHECK (status IN ('staged', 'validated', 'imported', 'rejected')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  CHECK (source_start_date <= source_end_date),
  CHECK (source_end_date < cutover_date),
  CHECK (imported_row_count <= source_row_count),
  UNIQUE (id, source_system)
);

CREATE TABLE working.forecast_customer_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  legacy_customer_id BIGINT NOT NULL,
  legacy_name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  customer_id BIGINT REFERENCES working.customers(id) ON DELETE RESTRICT,
  match_status TEXT NOT NULL DEFAULT 'proposed'
    CHECK (match_status IN ('proposed', 'confirmed', 'unmapped', 'ignored')),
  match_method TEXT NOT NULL DEFAULT 'none'
    CHECK (match_method IN ('none', 'exact', 'alias', 'fuzzy', 'ai', 'manual')),
  confidence NUMERIC(5,4) CHECK (confidence BETWEEN 0 AND 1),
  reviewed_at TIMESTAMPTZ,
  reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (btrim(legacy_name) <> ''),
  CHECK (btrim(normalized_name) <> ''),
  UNIQUE (source_system, legacy_customer_id)
);

CREATE TABLE working.forecast_item_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  legacy_item_id BIGINT NOT NULL,
  legacy_name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  item_variant_id BIGINT REFERENCES working.item_variants(id) ON DELETE RESTRICT,
  match_status TEXT NOT NULL DEFAULT 'proposed'
    CHECK (match_status IN ('proposed', 'confirmed', 'unmapped', 'ignored')),
  match_method TEXT NOT NULL DEFAULT 'none'
    CHECK (match_method IN ('none', 'exact', 'alias', 'fuzzy', 'ai', 'manual')),
  confidence NUMERIC(5,4) CHECK (confidence BETWEEN 0 AND 1),
  reviewed_at TIMESTAMPTZ,
  reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (btrim(legacy_name) <> ''),
  CHECK (btrim(normalized_name) <> ''),
  UNIQUE (source_system, legacy_item_id)
);

CREATE TABLE working.forecast_sales_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_batch_id BIGINT NOT NULL,
  source_system TEXT NOT NULL,
  legacy_sale_id BIGINT NOT NULL,
  sale_date DATE NOT NULL,
  legacy_customer_id BIGINT NOT NULL,
  legacy_customer_name TEXT NOT NULL,
  legacy_item_id BIGINT NOT NULL,
  legacy_item_name TEXT NOT NULL,
  quantity_crates INTEGER NOT NULL CHECK (quantity_crates >= 0),
  quantity_kg NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (quantity_kg >= 0),
  source_fingerprint TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (btrim(legacy_customer_name) <> ''),
  CHECK (btrim(legacy_item_name) <> ''),
  CHECK (source_fingerprint ~ '^[0-9a-f]{64}$'),
  FOREIGN KEY (import_batch_id, source_system)
    REFERENCES working.forecast_import_batches(id, source_system) ON DELETE CASCADE,
  UNIQUE (source_system, legacy_sale_id),
  UNIQUE (source_system, source_fingerprint)
);

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON working.forecast_customer_mappings
FOR EACH ROW EXECUTE FUNCTION working.set_updated_at();

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON working.forecast_item_mappings
FOR EACH ROW EXECUTE FUNCTION working.set_updated_at();

CREATE INDEX idx_forecast_history_date
  ON working.forecast_sales_history(sale_date);
CREATE INDEX idx_forecast_history_customer_date
  ON working.forecast_sales_history(legacy_customer_id, sale_date);
CREATE INDEX idx_forecast_history_item_date
  ON working.forecast_sales_history(legacy_item_id, sale_date);
CREATE INDEX idx_forecast_customer_mapping_status
  ON working.forecast_customer_mappings(match_status, customer_id);
CREATE INDEX idx_forecast_item_mapping_status
  ON working.forecast_item_mappings(match_status, item_variant_id);

ALTER TABLE working.forecast_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.forecast_customer_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.forecast_item_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.forecast_sales_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_access ON working.forecast_import_batches
FOR ALL TO authenticated
USING (working.current_app_role() = 'admin')
WITH CHECK (working.current_app_role() = 'admin');
CREATE POLICY admin_access ON working.forecast_customer_mappings
FOR ALL TO authenticated
USING (working.current_app_role() = 'admin')
WITH CHECK (working.current_app_role() = 'admin');
CREATE POLICY admin_access ON working.forecast_item_mappings
FOR ALL TO authenticated
USING (working.current_app_role() = 'admin')
WITH CHECK (working.current_app_role() = 'admin');
CREATE POLICY admin_access ON working.forecast_sales_history
FOR ALL TO authenticated
USING (working.current_app_role() = 'admin')
WITH CHECK (working.current_app_role() = 'admin');

GRANT SELECT, INSERT, UPDATE, DELETE ON
  working.forecast_import_batches,
  working.forecast_customer_mappings,
  working.forecast_item_mappings,
  working.forecast_sales_history
TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE
  working.forecast_import_batches_id_seq,
  working.forecast_customer_mappings_id_seq,
  working.forecast_item_mappings_id_seq,
  working.forecast_sales_history_id_seq
TO authenticated;

CREATE OR REPLACE VIEW working.forecast_training_sales
WITH (security_invoker = TRUE)
AS
SELECT
  history.sale_date,
  customer_mapping.customer_id,
  item_mapping.item_variant_id,
  history.quantity_crates,
  'legacy'::TEXT AS source_system,
  history.legacy_sale_id::TEXT AS source_sale_id
FROM working.forecast_sales_history history
JOIN working.forecast_import_batches batch
  ON batch.id = history.import_batch_id
JOIN working.forecast_item_mappings item_mapping
  ON item_mapping.source_system = history.source_system
 AND item_mapping.legacy_item_id = history.legacy_item_id
 AND item_mapping.match_status = 'confirmed'
LEFT JOIN working.forecast_customer_mappings customer_mapping
  ON customer_mapping.source_system = history.source_system
 AND customer_mapping.legacy_customer_id = history.legacy_customer_id
 AND customer_mapping.match_status = 'confirmed'
WHERE batch.status IN ('validated', 'imported')
  AND history.sale_date < batch.cutover_date
  AND history.quantity_crates > 0

UNION ALL

SELECT
  sale.sale_date,
  sale.customer_id,
  sale.fish_variety_id AS item_variant_id,
  sale.quantity_crates,
  'current'::TEXT AS source_system,
  sale.id::TEXT AS source_sale_id
FROM working.sales sale
WHERE sale.quantity_crates > 0;

GRANT SELECT ON working.forecast_training_sales TO authenticated;
REVOKE ALL ON working.forecast_training_sales FROM anon;

COMMENT ON TABLE working.forecast_sales_history IS
  'Read-only forecasting history imported from legacy systems; never participates in stock, billing, balances, or cashbook calculations.';
COMMENT ON VIEW working.forecast_training_sales IS
  'Crate-only training rows combining confirmed legacy mappings with current operational sales.';

COMMIT;
