-- Seven-day harvest planning. Recommendations are advisory and never mutate stock or purchases.

BEGIN;

ALTER TABLE working.forecast_item_mappings
  ADD COLUMN family_grade_codes TEXT[];

ALTER TABLE working.forecast_item_mappings
  ADD CONSTRAINT forecast_item_mappings_family_grades_require_item
  CHECK (family_grade_codes IS NULL OR item_id IS NOT NULL);

UPDATE working.forecast_item_mappings
SET family_grade_codes = ARRAY['M', 'S']::TEXT[]
WHERE item_id IS NOT NULL
  AND lower(btrim(legacy_name)) = 'jilebi';

CREATE OR REPLACE VIEW working.forecast_training_sales
WITH (security_invoker = TRUE)
AS
SELECT
  history.sale_date,
  customer_mapping.customer_id,
  item_mapping.item_variant_id,
  history.quantity_crates,
  'legacy'::TEXT AS source_system,
  history.legacy_sale_id::TEXT AS source_sale_id,
  coalesce(item_mapping.item_id, mapped_variant.item_id) AS item_id,
  CASE WHEN item_mapping.item_id IS NOT NULL THEN 'item' ELSE 'variant' END::TEXT AS mapping_level,
  item_mapping.family_grade_codes
FROM working.forecast_sales_history history
JOIN working.forecast_import_batches batch
  ON batch.id = history.import_batch_id
JOIN working.forecast_item_mappings item_mapping
  ON item_mapping.source_system = history.source_system
 AND item_mapping.legacy_item_id = history.legacy_item_id
 AND item_mapping.match_status = 'confirmed'
LEFT JOIN working.item_variants mapped_variant
  ON mapped_variant.id = item_mapping.item_variant_id
LEFT JOIN working.forecast_customer_mappings customer_mapping
  ON customer_mapping.source_system = history.source_system
 AND customer_mapping.legacy_customer_id = history.legacy_customer_id
 AND customer_mapping.match_status = 'confirmed'
WHERE batch.status IN ('validated', 'imported')
  AND history.sale_date < batch.cutover_date
  AND history.quantity_crates > 0

UNION ALL

SELECT
  sale.sale_date,
  sale.customer_id,
  sale.fish_variety_id AS item_variant_id,
  sale.quantity_crates,
  'current'::TEXT AS source_system,
  sale.id::TEXT AS source_sale_id,
  current_variant.item_id,
  'variant'::TEXT AS mapping_level,
  NULL::TEXT[] AS family_grade_codes
FROM working.sales sale
JOIN working.item_variants current_variant
  ON current_variant.id = sale.fish_variety_id
WHERE sale.quantity_crates > 0;

CREATE TABLE working.forecast_calendar_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_date DATE NOT NULL UNIQUE,
  name TEXT NOT NULL CHECK (btrim(name) <> ''),
  demand_multiplier NUMERIC(5,3) NOT NULL DEFAULT 1
    CHECK (demand_multiplier BETWEEN 0.25 AND 2.00),
  notes TEXT,
  is_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE working.forecast_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date DATE NOT NULL UNIQUE,
  end_date DATE NOT NULL,
  model_version TEXT NOT NULL DEFAULT 'weekday-v1',
  status TEXT NOT NULL DEFAULT 'ready' CHECK (status IN ('ready', 'archived')),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  generated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  CHECK (end_date = start_date + 6)
);

CREATE TABLE working.forecast_recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES working.forecast_runs(id) ON DELETE CASCADE,
  forecast_date DATE NOT NULL,
  item_variant_id BIGINT NOT NULL REFERENCES working.item_variants(id) ON DELETE RESTRICT,
  baseline_crates NUMERIC(10,2) NOT NULL CHECK (baseline_crates >= 0),
  recommended_crates INTEGER NOT NULL CHECK (recommended_crates >= 0),
  low_crates INTEGER NOT NULL CHECK (low_crates >= 0),
  high_crates INTEGER NOT NULL CHECK (high_crates >= low_crates),
  final_crates INTEGER NOT NULL CHECK (final_crates >= 0),
  confidence_score NUMERIC(5,4) NOT NULL CHECK (confidence_score BETWEEN 0 AND 1),
  confidence_label TEXT NOT NULL CHECK (confidence_label IN ('low', 'medium', 'high')),
  reasons JSONB NOT NULL DEFAULT '[]'::JSONB,
  is_overridden BOOLEAN NOT NULL DEFAULT FALSE,
  override_note TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (run_id, forecast_date, item_variant_id)
);

CREATE TABLE working.forecast_adjustments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recommendation_id BIGINT NOT NULL REFERENCES working.forecast_recommendations(id) ON DELETE CASCADE,
  previous_crates INTEGER NOT NULL,
  new_crates INTEGER NOT NULL CHECK (new_crates >= 0),
  note TEXT,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  changed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE TRIGGER set_updated_at BEFORE UPDATE ON working.forecast_calendar_events
FOR EACH ROW EXECUTE FUNCTION working.set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON working.forecast_recommendations
FOR EACH ROW EXECUTE FUNCTION working.set_updated_at();

CREATE INDEX idx_forecast_recommendations_date
  ON working.forecast_recommendations(forecast_date, item_variant_id);
CREATE INDEX idx_forecast_adjustments_recommendation
  ON working.forecast_adjustments(recommendation_id, changed_at DESC);

ALTER TABLE working.forecast_calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.forecast_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.forecast_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE working.forecast_adjustments ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_access ON working.forecast_calendar_events FOR ALL TO authenticated
USING (working.current_app_role() = 'admin') WITH CHECK (working.current_app_role() = 'admin');
CREATE POLICY admin_access ON working.forecast_runs FOR ALL TO authenticated
USING (working.current_app_role() = 'admin') WITH CHECK (working.current_app_role() = 'admin');
CREATE POLICY admin_access ON working.forecast_recommendations FOR ALL TO authenticated
USING (working.current_app_role() = 'admin') WITH CHECK (working.current_app_role() = 'admin');
CREATE POLICY admin_access ON working.forecast_adjustments FOR ALL TO authenticated
USING (working.current_app_role() = 'admin') WITH CHECK (working.current_app_role() = 'admin');

GRANT SELECT, INSERT, UPDATE, DELETE ON
  working.forecast_calendar_events, working.forecast_runs,
  working.forecast_recommendations, working.forecast_adjustments
TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE
  working.forecast_calendar_events_id_seq, working.forecast_runs_id_seq,
  working.forecast_recommendations_id_seq, working.forecast_adjustments_id_seq
TO authenticated;

CREATE OR REPLACE FUNCTION working.generate_harvest_forecast(p_start_date DATE DEFAULT CURRENT_DATE + 1)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  v_run_id BIGINT;
  v_target_date DATE;
  v_variant RECORD;
  v_values NUMERIC[];
  v_baseline NUMERIC;
  v_deviation NUMERIC;
  v_nonzero_weeks INTEGER;
  v_multiplier NUMERIC;
  v_recommended INTEGER;
  v_low INTEGER;
  v_high INTEGER;
  v_confidence NUMERIC;
  v_confidence_label TEXT;
  v_family_share NUMERIC;
  v_family_grade_codes TEXT[];
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can generate a harvest forecast' USING ERRCODE = '42501';
  END IF;

  IF p_start_date < CURRENT_DATE - 1 THEN
    RAISE EXCEPTION 'Forecast start date cannot be in the past';
  END IF;

  INSERT INTO working.forecast_runs (start_date, end_date, generated_by)
  VALUES (p_start_date, p_start_date + 6, auth.uid())
  ON CONFLICT (start_date) DO UPDATE
    SET end_date = EXCLUDED.end_date,
        model_version = 'weekday-v1',
        status = 'ready',
        generated_at = NOW(),
        generated_by = auth.uid()
  RETURNING id INTO v_run_id;

  FOR v_target_date IN SELECT generate_series(p_start_date, p_start_date + 6, '1 day')::DATE LOOP
    SELECT coalesce(event.demand_multiplier, 1)
      INTO v_multiplier
    FROM (SELECT 1) anchor
    LEFT JOIN working.forecast_calendar_events event
      ON event.event_date = v_target_date AND event.is_confirmed;

    FOR v_variant IN
      SELECT variant.id, variant.item_id, grade.code AS grade_code, variant.name
      FROM working.item_variants variant
      JOIN working.item_grades grade ON grade.id = variant.grade_id
      WHERE variant.is_active AND grade.is_active
      ORDER BY variant.id
    LOOP
      SELECT family_grade_codes INTO v_family_grade_codes
      FROM working.forecast_training_sales
      WHERE mapping_level = 'item' AND item_id = v_variant.item_id
      LIMIT 1;

      IF v_family_grade_codes IS NULL OR NOT (v_variant.grade_code = ANY(v_family_grade_codes)) THEN
        v_family_share := NULL;
      ELSE
        SELECT coalesce(
          (sum(training.quantity_crates) FILTER (WHERE training.item_variant_id = v_variant.id))::NUMERIC
            / nullif(sum(training.quantity_crates), 0),
          1::NUMERIC / greatest(count(DISTINCT allowed_variant.id), 1)
        )
        INTO v_family_share
        FROM working.item_variants allowed_variant
        JOIN working.item_grades allowed_grade ON allowed_grade.id = allowed_variant.grade_id
        LEFT JOIN working.forecast_training_sales training
          ON training.source_system = 'current'
         AND training.mapping_level = 'variant'
         AND training.item_variant_id = allowed_variant.id
         AND training.sale_date >= v_target_date - 56
         AND training.sale_date < v_target_date
        WHERE allowed_variant.item_id = v_variant.item_id
          AND allowed_variant.is_active
          AND allowed_grade.code = ANY(v_family_grade_codes);
      END IF;

      -- Eight matching weekdays. The generated dates preserve zero-demand weeks.
      SELECT array_agg(coalesce(day_quantity, 0) ORDER BY prior_date)
      INTO v_values
      FROM (
        SELECT prior_date,
          coalesce((
            SELECT sum(
              CASE
                WHEN training.mapping_level = 'variant' AND training.item_variant_id = v_variant.id
                  THEN training.quantity_crates
                WHEN training.mapping_level = 'item'
                  AND training.item_id = v_variant.item_id
                  AND (training.family_grade_codes IS NULL OR v_variant.grade_code = ANY(training.family_grade_codes))
                  THEN training.quantity_crates * coalesce(v_family_share, 0)
                ELSE 0
              END
            )
            FROM working.forecast_training_sales training
            WHERE training.sale_date = prior_date
          ), 0) AS day_quantity
        FROM generate_series(v_target_date - 56, v_target_date - 7, '7 days') prior(prior_date)
      ) history;

      SELECT coalesce(avg(value), 0), coalesce(stddev_pop(value), 0), count(*) FILTER (WHERE value > 0)
      INTO v_baseline, v_deviation, v_nonzero_weeks
      FROM unnest(v_values) value;

      v_baseline := v_baseline * v_multiplier;
      v_recommended := greatest(0, round(v_baseline)::INTEGER);
      v_low := greatest(0, floor((v_baseline - (0.75 * v_deviation)))::INTEGER);
      v_high := greatest(v_recommended, ceil(v_baseline + (0.75 * v_deviation))::INTEGER);
      v_confidence := least(1, greatest(0,
        (v_nonzero_weeks::NUMERIC / 8) *
        CASE WHEN v_baseline <= 0 THEN 0 ELSE 1 / (1 + (v_deviation / v_baseline)) END
      ));
      v_confidence_label := CASE
        WHEN v_confidence >= 0.65 THEN 'high'
        WHEN v_confidence >= 0.35 THEN 'medium'
        ELSE 'low'
      END;

      IF v_recommended > 0 OR EXISTS (
        SELECT 1 FROM working.forecast_recommendations existing
        WHERE existing.run_id = v_run_id
          AND existing.forecast_date = v_target_date
          AND existing.item_variant_id = v_variant.id
          AND existing.is_overridden
      ) THEN
        INSERT INTO working.forecast_recommendations (
          run_id, forecast_date, item_variant_id, baseline_crates,
          recommended_crates, low_crates, high_crates, final_crates,
          confidence_score, confidence_label, reasons
        ) VALUES (
          v_run_id, v_target_date, v_variant.id, round(v_baseline, 2),
          v_recommended, v_low, v_high, v_recommended,
          round(v_confidence, 4), v_confidence_label,
          jsonb_build_array(
            'Based on the last 8 matching weekdays',
            CASE WHEN v_multiplier <> 1 THEN 'Confirmed calendar adjustment applied' ELSE 'Includes recorded customer demand' END,
            CASE WHEN v_family_share IS NOT NULL THEN 'Grade-unknown history allocated using current grade mix' ELSE 'Item and grade history matched' END
          )
        )
        ON CONFLICT (run_id, forecast_date, item_variant_id) DO UPDATE
          SET baseline_crates = EXCLUDED.baseline_crates,
              recommended_crates = EXCLUDED.recommended_crates,
              low_crates = EXCLUDED.low_crates,
              high_crates = EXCLUDED.high_crates,
              final_crates = CASE WHEN working.forecast_recommendations.is_overridden
                THEN working.forecast_recommendations.final_crates ELSE EXCLUDED.final_crates END,
              confidence_score = EXCLUDED.confidence_score,
              confidence_label = EXCLUDED.confidence_label,
              reasons = EXCLUDED.reasons;
      ELSE
        DELETE FROM working.forecast_recommendations existing
        WHERE existing.run_id = v_run_id
          AND existing.forecast_date = v_target_date
          AND existing.item_variant_id = v_variant.id
          AND NOT existing.is_overridden;
      END IF;
    END LOOP;
  END LOOP;

  RETURN v_run_id;
END;
$$;

CREATE OR REPLACE FUNCTION working.set_harvest_forecast_quantity(
  p_recommendation_id BIGINT,
  p_final_crates INTEGER,
  p_note TEXT DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  v_previous INTEGER;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can edit a harvest forecast' USING ERRCODE = '42501';
  END IF;
  IF p_final_crates < 0 THEN RAISE EXCEPTION 'Crates cannot be negative'; END IF;

  SELECT final_crates INTO v_previous
  FROM working.forecast_recommendations
  WHERE id = p_recommendation_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Forecast row not found'; END IF;

  IF v_previous <> p_final_crates THEN
    INSERT INTO working.forecast_adjustments (
      recommendation_id, previous_crates, new_crates, note, changed_by
    ) VALUES (p_recommendation_id, v_previous, p_final_crates, nullif(btrim(p_note), ''), auth.uid());
  END IF;

  UPDATE working.forecast_recommendations
  SET final_crates = p_final_crates,
      is_overridden = (p_final_crates <> recommended_crates),
      override_note = CASE WHEN p_final_crates <> recommended_crates THEN nullif(btrim(p_note), '') ELSE NULL END
  WHERE id = p_recommendation_id;
  RETURN TRUE;
END;
$$;

CREATE OR REPLACE VIEW working.harvest_forecast_plan
WITH (security_invoker = TRUE)
AS
SELECT
  recommendation.id,
  recommendation.run_id,
  run.start_date,
  recommendation.forecast_date,
  recommendation.item_variant_id,
  item.name AS item_name,
  grade.code AS grade_code,
  variant.name AS variant_name,
  recommendation.baseline_crates,
  recommendation.recommended_crates,
  recommendation.low_crates,
  recommendation.high_crates,
  recommendation.final_crates,
  recommendation.confidence_score,
  recommendation.confidence_label,
  recommendation.reasons,
  recommendation.is_overridden,
  recommendation.override_note,
  run.generated_at
FROM working.forecast_recommendations recommendation
JOIN working.forecast_runs run ON run.id = recommendation.run_id
JOIN working.item_variants variant ON variant.id = recommendation.item_variant_id
JOIN working.items item ON item.id = variant.item_id
JOIN working.item_grades grade ON grade.id = variant.grade_id;

GRANT SELECT ON working.forecast_training_sales, working.harvest_forecast_plan TO authenticated;
REVOKE ALL ON working.harvest_forecast_plan FROM anon;
GRANT EXECUTE ON FUNCTION working.generate_harvest_forecast(DATE) TO authenticated;
GRANT EXECUTE ON FUNCTION working.set_harvest_forecast_quantity(BIGINT, INTEGER, TEXT) TO authenticated;

COMMENT ON TABLE working.forecast_recommendations IS
  'Advisory crate recommendations only. No row in this table changes inventory, purchases, sales, or accounting.';
COMMENT ON VIEW working.harvest_forecast_plan IS
  'Mobile-ready seven-day harvest plan with model range, confidence, and proprietor overrides.';

COMMIT;
