-- Customer-level demand view for the same seven-day harvest plan.

BEGIN;

CREATE TABLE working.forecast_customer_recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES working.forecast_runs(id) ON DELETE CASCADE,
  forecast_date DATE NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES working.customers(id) ON DELETE RESTRICT,
  item_variant_id BIGINT NOT NULL REFERENCES working.item_variants(id) ON DELETE RESTRICT,
  baseline_crates NUMERIC(10,2) NOT NULL CHECK (baseline_crates >= 0),
  recommended_crates INTEGER NOT NULL CHECK (recommended_crates > 0),
  low_crates INTEGER NOT NULL CHECK (low_crates >= 0),
  high_crates INTEGER NOT NULL CHECK (high_crates >= low_crates),
  confidence_score NUMERIC(5,4) NOT NULL CHECK (confidence_score BETWEEN 0 AND 1),
  confidence_label TEXT NOT NULL CHECK (confidence_label IN ('low', 'medium', 'high')),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (run_id, forecast_date, customer_id, item_variant_id)
);

CREATE INDEX idx_forecast_customer_recommendations_day
  ON working.forecast_customer_recommendations(run_id, forecast_date, customer_id);

ALTER TABLE working.forecast_customer_recommendations ENABLE ROW LEVEL SECURITY;
CREATE POLICY admin_access ON working.forecast_customer_recommendations FOR ALL TO authenticated
USING (working.current_app_role() = 'admin') WITH CHECK (working.current_app_role() = 'admin');
GRANT SELECT, INSERT, UPDATE, DELETE ON working.forecast_customer_recommendations TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE working.forecast_customer_recommendations_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION working.generate_customer_harvest_forecast(p_run_id BIGINT)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  v_start_date DATE;
  v_inserted INTEGER;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can generate a customer forecast' USING ERRCODE = '42501';
  END IF;

  SELECT start_date INTO v_start_date FROM working.forecast_runs WHERE id = p_run_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Forecast run not found'; END IF;

  DELETE FROM working.forecast_customer_recommendations WHERE run_id = p_run_id;

  WITH
  forecast_dates AS (
    SELECT generate_series(v_start_date, v_start_date + 6, '1 day')::DATE AS forecast_date
  ),
  family_configs AS (
    SELECT DISTINCT item_id, family_grade_codes
    FROM working.forecast_training_sales
    WHERE mapping_level = 'item' AND family_grade_codes IS NOT NULL
  ),
  recent_variant_sales AS (
    SELECT training.item_variant_id, sum(training.quantity_crates)::NUMERIC AS crates
    FROM working.forecast_training_sales training
    WHERE training.source_system = 'current'
      AND training.mapping_level = 'variant'
      AND training.sale_date >= v_start_date - 56
      AND training.sale_date < v_start_date
    GROUP BY training.item_variant_id
  ),
  family_allocations AS (
    SELECT
      config.item_id,
      config.family_grade_codes,
      variant.id AS item_variant_id,
      coalesce(
        recent.crates / nullif(sum(recent.crates) OVER (PARTITION BY config.item_id, config.family_grade_codes), 0),
        1::NUMERIC / count(*) OVER (PARTITION BY config.item_id, config.family_grade_codes)
      ) AS allocation_share
    FROM family_configs config
    JOIN working.item_variants variant ON variant.item_id = config.item_id AND variant.is_active
    JOIN working.item_grades grade ON grade.id = variant.grade_id
      AND grade.code = ANY(config.family_grade_codes)
    LEFT JOIN recent_variant_sales recent ON recent.item_variant_id = variant.id
  ),
  expanded_training AS (
    SELECT
      training.sale_date, training.customer_id, training.item_variant_id,
      training.quantity_crates::NUMERIC AS quantity_crates
    FROM working.forecast_training_sales training
    WHERE training.mapping_level = 'variant' AND training.customer_id IS NOT NULL

    UNION ALL

    SELECT
      training.sale_date, training.customer_id, allocation.item_variant_id,
      training.quantity_crates * allocation.allocation_share AS quantity_crates
    FROM working.forecast_training_sales training
    JOIN family_allocations allocation
      ON allocation.item_id = training.item_id
     AND allocation.family_grade_codes = training.family_grade_codes
    WHERE training.mapping_level = 'item' AND training.customer_id IS NOT NULL
  ),
  combinations AS (
    SELECT DISTINCT date.forecast_date, training.customer_id, training.item_variant_id
    FROM forecast_dates date
    JOIN expanded_training training
      ON training.sale_date BETWEEN date.forecast_date - 56 AND date.forecast_date - 7
     AND extract(isodow FROM training.sale_date) = extract(isodow FROM date.forecast_date)
  ),
  history_grid AS (
    SELECT
      combination.forecast_date, combination.customer_id, combination.item_variant_id,
      prior.prior_date,
      coalesce(sum(training.quantity_crates), 0) AS day_crates
    FROM combinations combination
    CROSS JOIN LATERAL generate_series(
      combination.forecast_date - 56, combination.forecast_date - 7, '7 days'
    ) prior(prior_date)
    LEFT JOIN expanded_training training
      ON training.customer_id = combination.customer_id
     AND training.item_variant_id = combination.item_variant_id
     AND training.sale_date = prior.prior_date::DATE
    GROUP BY combination.forecast_date, combination.customer_id,
      combination.item_variant_id, prior.prior_date
  ),
  statistics AS (
    SELECT
      forecast_date, customer_id, item_variant_id,
      avg(day_crates) AS baseline,
      stddev_pop(day_crates) AS deviation,
      count(*) FILTER (WHERE day_crates > 0) AS active_weeks
    FROM history_grid
    GROUP BY forecast_date, customer_id, item_variant_id
  ),
  prepared AS (
    SELECT *,
      greatest(0, round(baseline)::INTEGER) AS recommended,
      least(1, greatest(0,
        (active_weeks::NUMERIC / 8) *
        CASE WHEN baseline <= 0 THEN 0 ELSE 1 / (1 + (deviation / baseline)) END
      )) AS confidence
    FROM statistics
  )
  INSERT INTO working.forecast_customer_recommendations (
    run_id, forecast_date, customer_id, item_variant_id,
    baseline_crates, recommended_crates, low_crates, high_crates,
    confidence_score, confidence_label
  )
  SELECT
    p_run_id, forecast_date, customer_id, item_variant_id,
    round(baseline, 2), recommended,
    greatest(0, floor(baseline - (0.75 * deviation))::INTEGER),
    greatest(recommended, ceil(baseline + (0.75 * deviation))::INTEGER),
    round(confidence, 4),
    CASE WHEN confidence >= 0.65 THEN 'high'
         WHEN confidence >= 0.35 THEN 'medium'
         ELSE 'low' END
  FROM prepared
  WHERE recommended > 0;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  RETURN v_inserted;
END;
$$;

CREATE OR REPLACE VIEW working.harvest_customer_forecast_plan
WITH (security_invoker = TRUE)
AS
SELECT
  recommendation.id,
  recommendation.run_id,
  run.start_date,
  recommendation.forecast_date,
  recommendation.customer_id,
  customer.name AS customer_name,
  customer.city AS customer_location,
  recommendation.item_variant_id,
  item.name AS item_name,
  grade.code AS grade_code,
  variant.name AS variant_name,
  recommendation.baseline_crates,
  recommendation.recommended_crates,
  recommendation.low_crates,
  recommendation.high_crates,
  recommendation.confidence_score,
  recommendation.confidence_label,
  recommendation.generated_at
FROM working.forecast_customer_recommendations recommendation
JOIN working.forecast_runs run ON run.id = recommendation.run_id
JOIN working.customers customer ON customer.id = recommendation.customer_id
JOIN working.item_variants variant ON variant.id = recommendation.item_variant_id
JOIN working.items item ON item.id = variant.item_id
JOIN working.item_grades grade ON grade.id = variant.grade_id;

GRANT SELECT ON working.harvest_customer_forecast_plan TO authenticated;
REVOKE ALL ON working.harvest_customer_forecast_plan FROM anon;
GRANT EXECUTE ON FUNCTION working.generate_customer_harvest_forecast(BIGINT) TO authenticated;

COMMENT ON VIEW working.harvest_customer_forecast_plan IS
  'Known-customer demand estimates by day and item. Unmapped historical customers remain represented only in the item-level plan.';

COMMIT;
