-- Forecast-versus-actual reporting and an auditable proprietor approval workflow.

BEGIN;

ALTER TABLE working.forecast_runs
  DROP CONSTRAINT forecast_runs_status_check;
ALTER TABLE working.forecast_runs
  ADD CONSTRAINT forecast_runs_status_check CHECK (status IN ('ready', 'approved', 'archived'));
ALTER TABLE working.forecast_runs
  ADD COLUMN approved_at TIMESTAMPTZ,
  ADD COLUMN approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE TABLE working.forecast_run_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES working.forecast_runs(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN ('approved', 'reopened')),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX idx_forecast_run_events_run ON working.forecast_run_events(run_id, created_at DESC);
ALTER TABLE working.forecast_run_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY admin_access ON working.forecast_run_events FOR ALL TO authenticated
USING (working.current_app_role() = 'admin') WITH CHECK (working.current_app_role() = 'admin');
GRANT SELECT, INSERT ON working.forecast_run_events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE working.forecast_run_events_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION working.guard_approved_forecast_rows()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  v_run_id BIGINT := coalesce(NEW.run_id, OLD.run_id);
BEGIN
  IF EXISTS (SELECT 1 FROM working.forecast_runs WHERE id = v_run_id AND status = 'approved') THEN
    RAISE EXCEPTION 'Approved forecast is locked. Reopen the plan before changing it.';
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER guard_approved_forecast_rows
BEFORE INSERT OR UPDATE OR DELETE ON working.forecast_recommendations
FOR EACH ROW EXECUTE FUNCTION working.guard_approved_forecast_rows();
CREATE TRIGGER guard_approved_customer_forecast_rows
BEFORE INSERT OR UPDATE OR DELETE ON working.forecast_customer_recommendations
FOR EACH ROW EXECUTE FUNCTION working.guard_approved_forecast_rows();

CREATE OR REPLACE FUNCTION working.approve_harvest_forecast(p_run_id BIGINT, p_note TEXT DEFAULT NULL)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can approve a harvest plan' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM working.forecast_recommendations WHERE run_id = p_run_id) THEN
    RAISE EXCEPTION 'Forecast plan has no recommendations';
  END IF;

  UPDATE working.forecast_runs
  SET status = 'approved', approved_at = NOW(), approved_by = auth.uid()
  WHERE id = p_run_id AND status = 'ready';
  IF NOT FOUND THEN RAISE EXCEPTION 'Only a ready forecast can be approved'; END IF;

  INSERT INTO working.forecast_run_events(run_id, event_type, note, created_by)
  VALUES (p_run_id, 'approved', nullif(btrim(p_note), ''), auth.uid());
  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION working.reopen_harvest_forecast(p_run_id BIGINT, p_note TEXT DEFAULT NULL)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can reopen a harvest plan' USING ERRCODE = '42501';
  END IF;
  UPDATE working.forecast_runs
  SET status = 'ready', approved_at = NULL, approved_by = NULL
  WHERE id = p_run_id AND status = 'approved';
  IF NOT FOUND THEN RAISE EXCEPTION 'Only an approved forecast can be reopened'; END IF;

  INSERT INTO working.forecast_run_events(run_id, event_type, note, created_by)
  VALUES (p_run_id, 'reopened', nullif(btrim(p_note), ''), auth.uid());
  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION working.set_harvest_forecast_quantity(
  p_recommendation_id BIGINT,
  p_final_crates INTEGER,
  p_note TEXT DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  v_previous INTEGER;
  v_run_status TEXT;
BEGIN
  IF working.current_app_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only administrators can edit a harvest forecast' USING ERRCODE = '42501';
  END IF;
  IF p_final_crates < 0 THEN RAISE EXCEPTION 'Crates cannot be negative'; END IF;

  SELECT recommendation.final_crates, run.status
  INTO v_previous, v_run_status
  FROM working.forecast_recommendations recommendation
  JOIN working.forecast_runs run ON run.id = recommendation.run_id
  WHERE recommendation.id = p_recommendation_id
  FOR UPDATE OF recommendation;
  IF NOT FOUND THEN RAISE EXCEPTION 'Forecast row not found'; END IF;
  IF v_run_status = 'approved' THEN RAISE EXCEPTION 'Reopen the approved plan before editing it'; END IF;

  IF v_previous <> p_final_crates THEN
    INSERT INTO working.forecast_adjustments (
      recommendation_id, previous_crates, new_crates, note, changed_by
    ) VALUES (p_recommendation_id, v_previous, p_final_crates, nullif(btrim(p_note), ''), auth.uid());
  END IF;

  UPDATE working.forecast_recommendations
  SET final_crates = p_final_crates,
      is_overridden = (p_final_crates <> recommended_crates),
      override_note = CASE WHEN p_final_crates <> recommended_crates THEN nullif(btrim(p_note), '') ELSE NULL END
  WHERE id = p_recommendation_id;
  RETURN TRUE;
END;
$$;

CREATE OR REPLACE VIEW working.harvest_forecast_plan
WITH (security_invoker = TRUE)
AS
SELECT
  recommendation.id, recommendation.run_id, run.start_date,
  recommendation.forecast_date, recommendation.item_variant_id,
  item.name AS item_name, grade.code AS grade_code, variant.name AS variant_name,
  recommendation.baseline_crates, recommendation.recommended_crates,
  recommendation.low_crates, recommendation.high_crates, recommendation.final_crates,
  recommendation.confidence_score, recommendation.confidence_label,
  recommendation.reasons, recommendation.is_overridden, recommendation.override_note,
  run.generated_at, recommendation.model_name, recommendation.model_accuracy,
  run.status AS run_status, run.approved_at
FROM working.forecast_recommendations recommendation
JOIN working.forecast_runs run ON run.id = recommendation.run_id
JOIN working.item_variants variant ON variant.id = recommendation.item_variant_id
JOIN working.items item ON item.id = variant.item_id
JOIN working.item_grades grade ON grade.id = variant.grade_id;

CREATE OR REPLACE VIEW working.forecast_actual_comparison
WITH (security_invoker = TRUE)
AS
SELECT
  recommendation.id AS recommendation_id,
  recommendation.run_id,
  recommendation.forecast_date,
  recommendation.item_variant_id,
  variant.name AS variant_name,
  recommendation.recommended_crates,
  recommendation.final_crates,
  coalesce(actual.quantity_crates, 0)::NUMERIC(12,2) AS actual_crates,
  abs(coalesce(actual.quantity_crates, 0) - recommendation.recommended_crates)::NUMERIC(12,2) AS model_absolute_error,
  abs(coalesce(actual.quantity_crates, 0) - recommendation.final_crates)::NUMERIC(12,2) AS plan_absolute_error,
  CASE WHEN coalesce(actual.quantity_crates, 0) > 0
    THEN greatest(0, 1 - (abs(actual.quantity_crates - recommendation.final_crates) / actual.quantity_crates))
    ELSE CASE WHEN recommendation.final_crates = 0 THEN 1 ELSE 0 END
  END::NUMERIC(5,4) AS plan_accuracy,
  recommendation.is_overridden,
  run.status AS run_status
FROM working.forecast_recommendations recommendation
JOIN working.forecast_runs run ON run.id = recommendation.run_id
JOIN working.item_variants variant ON variant.id = recommendation.item_variant_id
LEFT JOIN working.forecast_daily_variant_demand actual
  ON actual.sale_date = recommendation.forecast_date
 AND actual.item_variant_id = recommendation.item_variant_id
WHERE recommendation.forecast_date < CURRENT_DATE;

GRANT SELECT ON working.forecast_actual_comparison TO authenticated;
REVOKE ALL ON working.forecast_actual_comparison FROM anon;
GRANT EXECUTE ON FUNCTION working.approve_harvest_forecast(BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION working.reopen_harvest_forecast(BIGINT, TEXT) TO authenticated;

COMMIT;
