-- Keep forecast loading fast on mobile. Forecast accuracy only compares dates
-- generated by the current app, so actuals can come directly from current
-- sales instead of expanding the full legacy training-history view.

BEGIN;

CREATE OR REPLACE VIEW working.forecast_actual_comparison
WITH (security_invoker = TRUE)
AS
WITH current_actuals AS (
  SELECT
    sale.sale_date,
    sale.fish_variety_id AS item_variant_id,
    sum(sale.quantity_crates)::NUMERIC(12,2) AS quantity_crates
  FROM working.sales sale
  WHERE sale.quantity_crates > 0
  GROUP BY sale.sale_date, sale.fish_variety_id
)
SELECT
  recommendation.id AS recommendation_id,
  recommendation.run_id,
  recommendation.forecast_date,
  recommendation.item_variant_id,
  variant.name AS variant_name,
  recommendation.recommended_crates,
  recommendation.final_crates,
  coalesce(actual.quantity_crates, 0)::NUMERIC(12,2) AS actual_crates,
  abs(coalesce(actual.quantity_crates, 0) - recommendation.recommended_crates)::NUMERIC(12,2) AS model_absolute_error,
  abs(coalesce(actual.quantity_crates, 0) - recommendation.final_crates)::NUMERIC(12,2) AS plan_absolute_error,
  CASE WHEN coalesce(actual.quantity_crates, 0) > 0
    THEN greatest(0, 1 - (abs(actual.quantity_crates - recommendation.final_crates) / actual.quantity_crates))
    ELSE CASE WHEN recommendation.final_crates = 0 THEN 1 ELSE 0 END
  END::NUMERIC(5,4) AS plan_accuracy,
  recommendation.is_overridden,
  run.status AS run_status
FROM working.forecast_recommendations recommendation
JOIN working.forecast_runs run ON run.id = recommendation.run_id
JOIN working.item_variants variant ON variant.id = recommendation.item_variant_id
LEFT JOIN current_actuals actual
  ON actual.sale_date = recommendation.forecast_date
 AND actual.item_variant_id = recommendation.item_variant_id
WHERE recommendation.forecast_date < CURRENT_DATE;

GRANT SELECT ON working.forecast_actual_comparison TO authenticated;
REVOKE ALL ON working.forecast_actual_comparison FROM anon;

COMMIT;
