-- Repair cumulative customer-bill snapshots and prevent future bills from
-- being finalized out of chronological order. Source sales, item amounts,
-- discounts and payment rows are never changed by this migration.

BEGIN;

CREATE TABLE IF NOT EXISTS working.customer_bill_balance_repairs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Keep the original identifier even if a later controlled correction
  -- replaces the bill; the audit record must never block that workflow.
  bill_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES working.customers(id) ON DELETE RESTRICT,
  reason TEXT NOT NULL,
  before_values JSONB NOT NULL,
  after_values JSONB NOT NULL,
  repaired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  repaired_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE working.customer_bill_balance_repairs ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON working.customer_bill_balance_repairs TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON working.customer_bill_balance_repairs FROM anon, authenticated;

CREATE POLICY admin_read_customer_bill_balance_repairs
ON working.customer_bill_balance_repairs FOR SELECT TO authenticated
USING (working.current_app_role() = 'admin');

CREATE OR REPLACE FUNCTION working.rebuild_customer_bill_chain(
  p_customer_id BIGINT,
  p_reason TEXT
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  bill_record working.bills%ROWTYPE;
  previous_bill_date DATE := DATE '1900-01-01';
  running_balance NUMERIC(14,2);
  interval_payments NUMERIC(14,2);
  new_total NUMERIC(14,2);
  new_balance_due NUMERIC(14,2);
  account_balance_today NUMERIC(14,2);
  latest_bill_id BIGINT;
  changed_count INTEGER := 0;
  new_status TEXT;
  new_is_active BOOLEAN;
  before_snapshot JSONB;
  after_snapshot JSONB;
BEGIN
  SELECT opening_balance INTO running_balance
  FROM working.customers WHERE id = p_customer_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Customer not found'; END IF;

  SELECT id INTO latest_bill_id
  FROM working.bills
  WHERE customer_id = p_customer_id
  ORDER BY bill_date DESC, id DESC
  LIMIT 1;
  IF latest_bill_id IS NULL THEN RETURN 0; END IF;

  SELECT account_balance INTO account_balance_today
  FROM working.get_customer_account_summary(p_customer_id, CURRENT_DATE);

  FOR bill_record IN
    SELECT * FROM working.bills
    WHERE customer_id = p_customer_id
    ORDER BY bill_date, id
    FOR UPDATE
  LOOP
    SELECT coalesce(sum(amount), 0) INTO interval_payments
    FROM working.payments
    WHERE customer_id = p_customer_id
      AND payment_date > previous_bill_date
      AND payment_date <= bill_record.bill_date
      AND voided_at IS NULL;

    new_total := running_balance - interval_payments
      + bill_record.subtotal - bill_record.discount;
    new_is_active := bill_record.id = latest_bill_id;
    new_balance_due := greatest(
      CASE WHEN new_is_active THEN account_balance_today ELSE new_total END,
      0
    );
    new_status := CASE
      WHEN (CASE WHEN new_is_active THEN account_balance_today ELSE new_total END) <= 0
        THEN 'paid'
      ELSE 'unpaid'
    END;

    before_snapshot := jsonb_build_object(
      'previous_balance', bill_record.previous_balance,
      'amount_paid', bill_record.amount_paid,
      'total', bill_record.total,
      'balance_due', bill_record.balance_due,
      'status', bill_record.status,
      'is_active', bill_record.is_active
    );
    after_snapshot := jsonb_build_object(
      'previous_balance', running_balance,
      'amount_paid', interval_payments,
      'total', new_total,
      'balance_due', new_balance_due,
      'status', new_status,
      'is_active', new_is_active
    );

    IF before_snapshot IS DISTINCT FROM after_snapshot THEN
      INSERT INTO working.customer_bill_balance_repairs (
        bill_id, customer_id, reason, before_values, after_values, repaired_by
      ) VALUES (
        bill_record.id, p_customer_id, p_reason,
        before_snapshot, after_snapshot, auth.uid()
      );

      UPDATE working.bills
      SET previous_balance = running_balance,
          amount_paid = interval_payments,
          total = new_total,
          balance_due = new_balance_due,
          status = new_status,
          is_active = new_is_active
      WHERE id = bill_record.id;
      changed_count := changed_count + 1;
    END IF;

    running_balance := new_total;
    previous_bill_date := bill_record.bill_date;
  END LOOP;

  RETURN changed_count;
END;
$$;

REVOKE ALL ON FUNCTION working.rebuild_customer_bill_chain(BIGINT, TEXT) FROM PUBLIC, anon, authenticated;

-- Repair every existing customer chain in one transaction. Each changed bill
-- retains an immutable before/after record in the audit table above.
DO $$
DECLARE customer_record RECORD;
BEGIN
  FOR customer_record IN
    SELECT DISTINCT customer_id FROM working.bills ORDER BY customer_id
  LOOP
    PERFORM working.rebuild_customer_bill_chain(
      customer_record.customer_id,
      'Production chronological balance repair 2026-10-02'
    );
  END LOOP;
END;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_single_active_bill
  ON working.bills(customer_id) WHERE is_active;

CREATE OR REPLACE FUNCTION working.enforce_customer_bill_chronology()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE
  earliest_unbilled_date DATE;
  later_bill_date DATE;
BEGIN
  SELECT min(sale_date) INTO earliest_unbilled_date
  FROM working.sales
  WHERE customer_id = NEW.customer_id
    AND billing_status = 'unbilled'
    AND sale_date < NEW.bill_date;

  IF earliest_unbilled_date IS NOT NULL THEN
    RAISE EXCEPTION '% has earlier unbilled sales from %. Create that bill before %.',
      (SELECT name FROM working.customers WHERE id = NEW.customer_id),
      to_char(earliest_unbilled_date, 'DD Mon YYYY'),
      to_char(NEW.bill_date, 'DD Mon YYYY');
  END IF;

  SELECT max(bill_date) INTO later_bill_date
  FROM working.bills
  WHERE customer_id = NEW.customer_id
    AND bill_date > NEW.bill_date;

  IF later_bill_date IS NOT NULL THEN
    RAISE EXCEPTION 'A later bill dated % already exists. Bills must be created in date order.',
      to_char(later_bill_date, 'DD Mon YYYY');
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS enforce_customer_bill_chronology ON working.bills;
CREATE TRIGGER enforce_customer_bill_chronology
BEFORE INSERT ON working.bills
FOR EACH ROW EXECUTE FUNCTION working.enforce_customer_bill_chronology();

REVOKE ALL ON FUNCTION working.enforce_customer_bill_chronology() FROM PUBLIC;

-- The bill RPC supplies the closing total. Store the complete outstanding
-- amount, including current charges, rather than only the brought-forward part.
CREATE OR REPLACE FUNCTION working.apply_opening_balance_to_first_bill()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = working, pg_temp
AS $$
DECLARE opening_value NUMERIC(14,2);
BEGIN
  IF NOT EXISTS (SELECT 1 FROM working.bills WHERE customer_id = NEW.customer_id) THEN
    SELECT CASE WHEN opening_balance_date <= NEW.bill_date THEN opening_balance ELSE 0 END
    INTO opening_value FROM working.customers WHERE id = NEW.customer_id;
    opening_value := coalesce(opening_value, 0);
    NEW.previous_balance := NEW.previous_balance + opening_value;
    NEW.total := NEW.total + opening_value;
  END IF;
  NEW.balance_due := greatest(NEW.total, 0);
  NEW.status := CASE WHEN NEW.total <= 0 THEN 'paid' ELSE 'unpaid' END;
  RETURN NEW;
END;
$$;

COMMIT;
